// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface AliasUpdateByIdRequest {
  /**
   * Entity ID to which this alias should be tied to
   */
  canonical_id?: string
  /**
   * Entity ID to which this alias should be tied to. This field is deprecated in favor of 'canonical_id'.
   */
  entity_id?: string
  /**
   * Mount accessor to which this alias belongs to
   */
  mount_accessor?: string
  /**
   * Name of the alias
   */
  name?: string
}

/* @anchor:file:end */
