// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface AuthReadConfigurationResponse {
  accessor?: string
  /**
   * @format map
   */
  config?: Record<string, never>
  deprecation_status?: string
  description?: string
  external_entropy_access?: boolean
  local?: boolean
  /**
   * @format map
   */
  options?: Record<string, never>
  plugin_version?: string
  running_plugin_version?: string
  running_sha256?: string
  seal_wrap?: boolean
  type?: string
  uuid?: string
}

/* @anchor:file:end */
