// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface DecodeRequest {
  /**
   * Specifies the encoded token (result from generate-root).
   */
  encoded_token?: string
  /**
   * Specifies the otp code for decode.
   */
  otp?: string
}

/* @anchor:file:end */
