// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface EncryptionKeyConfigureRotateKeyringConfigRequest {
  /**
   * Whether automatic rotation is enabled.
   */
  enabled?: boolean
  /**
   * How long after installation of an active key term that the key will be automatically rotated.
   * @format seconds
   */
  interval?: number
  /**
   * The number of encryption operations performed before the barrier key is automatically rotated.
   * @format int64
   */
  max_operations?: number
}

/* @anchor:file:end */
