// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface EntityUpdateByNameRequest {
  /**
   * If set true, tokens tied to this identity will not be able to be used (but will not be revoked).
   */
  disabled?: boolean
  /**
   * ID of the entity. If set, updates the corresponding existing entity.
   */
  id?: string
  /**
   * Metadata to be associated with the entity. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
   * @format kvpairs
   */
  metadata?: Record<string, never>
  /**
   * Policies to be tied to the entity.
   */
  policies?: string[]
}

/* @anchor:file:end */
