// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface EntityMergeRequest {
  /**
   * Alias IDs to keep in case of conflicting aliases. Ignored if no conflicting aliases found
   */
  conflicting_alias_ids_to_keep?: string[]
  /**
   * Setting this will follow the 'mine' strategy for merging MFA secrets. If there are secrets of the same type both in entities that are merged from and in entity into which all others are getting merged, secrets in the destination will be unaltered. If not set, this API will throw an error containing all the conflicts.
   */
  force?: boolean
  /**
   * Entity IDs which need to get merged
   */
  from_entity_ids?: string[]
  /**
   * Entity ID into which all the other entities need to get merged
   */
  to_entity_id?: string
}

/* @anchor:file:end */
