// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface EntityCreateAliasRequest {
  /**
   * Entity ID to which this alias belongs
   */
  canonical_id?: string
  /**
   * User provided key-value pairs
   * @format kvpairs
   */
  custom_metadata?: Record<string, never>
  /**
   * Entity ID to which this alias belongs. This field is deprecated, use canonical_id.
   */
  entity_id?: string
  /**
   * ID of the entity alias. If set, updates the corresponding entity alias.
   */
  id?: string
  /**
   * Mount accessor to which this alias belongs to; unused for a modify
   */
  mount_accessor?: string
  /**
   * Name of the alias; unused for a modify
   */
  name?: string
}

/* @anchor:file:end */
