// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface EntityBatchDeleteRequest {
  /**
   * Entity IDs to delete
   */
  entity_ids?: string[]
}

/* @anchor:file:end */
