// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface EntityUpdateAliasByIdRequest {
  /**
   * Entity ID to which this alias should be tied to
   */
  canonical_id?: string
  /**
   * User provided key-value pairs
   * @format kvpairs
   */
  custom_metadata?: Record<string, never>
  /**
   * Entity ID to which this alias belongs to. This field is deprecated, use canonical_id.
   */
  entity_id?: string
  /**
   * (Unused)
   */
  mount_accessor?: string
  /**
   * (Unused)
   */
  name?: string
}

/* @anchor:file:end */
