// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface GroupCreateAliasRequest {
  /**
   * ID of the group to which this is an alias.
   */
  canonical_id?: string
  /**
   * ID of the group alias.
   */
  id?: string
  /**
   * Mount accessor to which this alias belongs to.
   */
  mount_accessor?: string
  /**
   * Alias of the group.
   */
  name?: string
}

/* @anchor:file:end */
