// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface GroupUpdateByNameRequest {
  /**
   * ID of the group. If set, updates the corresponding existing group.
   */
  id?: string
  /**
   * Entity IDs to be assigned as group members.
   */
  member_entity_ids?: string[]
  /**
   * Group IDs to be assigned as group members.
   */
  member_group_ids?: string[]
  /**
   * Metadata to be associated with the group. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
   * @format kvpairs
   */
  metadata?: Record<string, never>
  /**
   * Policies to be tied to the group.
   */
  policies?: string[]
  /**
   * Type of the group, 'internal' or 'external'. Defaults to 'internal'
   */
  type?: string
}

/* @anchor:file:end */
