// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface KubernetesConfigureAuthRequest {
  /**
   * Disable JWT issuer validation (Deprecated, will be removed in a future release)
   * @deprecated
   */
  disable_iss_validation?: boolean
  /**
   * Disable defaulting to the local CA cert and service account JWT when running in a Kubernetes pod
   */
  disable_local_ca_jwt?: boolean
  /**
   * Optional JWT issuer. If no issuer is specified, then this plugin will use kubernetes.io/serviceaccount as the default issuer. (Deprecated, will be removed in a future release)
   * @deprecated
   */
  issuer?: string
  /**
   * PEM encoded CA cert for use by the TLS client used to talk with the API.
   */
  kubernetes_ca_cert?: string
  /**
   * Host must be a host string, a host:port pair, or a URL to the base of the Kubernetes API server.
   */
  kubernetes_host?: string
  /**
   * Optional list of PEM-formated public keys or certificates used to verify the signatures of kubernetes service account JWTs. If a certificate is given, its public key will be extracted. Not every installation of Kubernetes exposes these keys.
   */
  pem_keys?: string[]
  /**
   * A service account JWT (or other token) used as a bearer token to access the TokenReview API to validate other JWTs during login. If not set the JWT used for login will be used to access the API.
   */
  token_reviewer_jwt?: string
}

/* @anchor:file:end */
