// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface KvWriteMetadataPathRequest {
  /**
   * Optional entry to list begin listing after, not required to exist. Only used for listing.
   */
  after?: string
  /**
   * If true the key will require the cas parameter to be set on all write requests. If false, the backend’s configuration will be used.
   */
  cas_required?: boolean
  /**
   * User-provided key-value pairs that are used to describe arbitrary and version-agnostic information about a secret.
   * @format map
   */
  custom_metadata?: Record<string, never>
  /**
   * The length of time before a version is deleted. If not set, the backend's configured delete_version_after is used. Cannot be greater than the backend's delete_version_after. A zero duration clears the current setting. A negative duration will cause an error.
   * @format seconds
   */
  delete_version_after?: number
  /**
   * Optional number of entries to return; defaults to all entries. Only used for listing.
   */
  limit?: number
  /**
   * The number of versions to keep. If not set, the backend’s configured max version is used.
   */
  max_versions?: number
  /**
   * Check-and-set parameter for metadata updates. Must match the current metadata version for the update to succeed. Set to 0 for initial metadata creation.
   */
  metadata_cas?: number
  /**
   * If true the key will require the cas parameter to be set on all metadata update requests. If false, the backend's configuration will be used.
   */
  metadata_cas_required?: boolean
}

/* @anchor:file:end */
