// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface KvWriteConfigRequest {
  /**
   * If true, the backend will require the cas parameter to be set for each write
   */
  cas_required?: boolean
  /**
   * If set, the length of time before a version is deleted. A negative duration disables the use of delete_version_after on all keys. A zero duration clears the current setting. Accepts a Go duration format string.
   * @format seconds
   */
  delete_version_after?: number
  /**
   * The number of versions to keep for each key. Defaults to 10
   */
  max_versions?: number
  /**
   * If true, the backend will require the metadata_cas parameter to be set for each metadata update
   */
  metadata_cas_required?: boolean
}

/* @anchor:file:end */
