// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface KvWriteUndeletePathRequest {
  /**
   * The versions to unarchive. The versions will be restored and their data will be returned on normal get requests.
   */
  versions?: number[]
}

/* @anchor:file:end */
