// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface KvWriteDestroyPathRequest {
  /**
   * The versions to destroy. Their data will be permanently deleted.
   */
  versions?: number[]
}

/* @anchor:file:end */
