// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface LeasesRenewLeaseWithId2Request {
  /**
   * The desired increment in seconds to the lease
   * @format seconds
   */
  increment?: number
  /**
   * The lease identifier to renew. This is included with a lease.
   */
  lease_id?: string
}

/* @anchor:file:end */
