// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface LeasesLookUpWithPrefixResponse {
  /**
   * A list of lease ids
   */
  keys?: string[]
}

/* @anchor:file:end */
