// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface LeasesRevokeLeaseWithPrefixRequest {
  /**
   * Whether or not to perform the revocation synchronously
   */
  sync?: boolean
}

/* @anchor:file:end */
