// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface LeasesRevokeLease2Request {
  /**
   * The lease identifier to renew. This is included with a lease.
   */
  lease_id?: string
  /**
   * Whether or not to perform the revocation synchronously
   */
  sync?: boolean
  /**
   * The lease identifier to renew. This is included with a lease.
   */
  url_lease_id?: string
}

/* @anchor:file:end */
