// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface LeasesListResponse {
  /**
   * Number of matching leases per mount
   */
  counts?: number
  /**
   * Number of matching leases
   */
  lease_count?: number
}

/* @anchor:file:end */
