// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface LoggersUpdateVerbosityLevelForRequest {
  /**
   * Log verbosity level. Supported values (in order of detail) are "trace", "debug", "info", "warn", and "error".
   */
  level?: string
}

/* @anchor:file:end */
