// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface MfaWriteLoginEnforcementRequest {
  /**
   * Array of auth mount accessor IDs
   */
  auth_method_accessors?: string[]
  /**
   * Array of auth mount types
   */
  auth_method_types?: string[]
  /**
   * Array of identity entity IDs
   */
  identity_entity_ids?: string[]
  /**
   * Array of identity group IDs
   */
  identity_group_ids?: string[]
  /**
   * Array of Method IDs that determine what methods will be enforced
   */
  mfa_method_ids: string[]
}

/* @anchor:file:end */
