// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface MfaConfigureTotpMethodRequest {
  /**
   * The hashing algorithm used to generate the TOTP token. Options include SHA1, SHA256 and SHA512.
   */
  algorithm?: string
  /**
   * The number of digits in the generated TOTP token. This value can either be 6 or 8.
   */
  digits?: number
  /**
   * The name of the key's issuing organization.
   */
  issuer?: string
  /**
   * Determines the size in bytes of the generated key.
   */
  key_size?: number
  /**
   * Max number of allowed validation attempts.
   */
  max_validation_attempts?: number
  /**
   * The unique name identifier for this MFA method.
   */
  method_name?: string
  /**
   * The length of time used to generate a counter for the TOTP token calculation.
   * @format seconds
   */
  period?: number
  /**
   * The pixel size of the generated square QR code.
   */
  qr_size?: number
  /**
   * The number of delay periods that are allowed when validating a TOTP token. This value can either be 0 or 1.
   */
  skew?: number
}

/* @anchor:file:end */
