// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface MfaConfigureDuoMethodRequest {
  /**
   * API host name for Duo.
   */
  api_hostname?: string
  /**
   * Integration key for Duo.
   */
  integration_key?: string
  /**
   * The unique name identifier for this MFA method.
   */
  method_name?: string
  /**
   * Push information for Duo.
   */
  push_info?: string
  /**
   * Secret key for Duo.
   */
  secret_key?: string
  /**
   * If true, the user is reminded to use the passcode upon MFA validation. This option does not enforce using the passcode. Defaults to false.
   */
  use_passcode?: boolean
  /**
   * A template string for mapping Identity names to MFA method names. Values to subtitute should be placed in {{}}. For example, "{{alias.name}}@example.com". Currently-supported mappings: alias.name: The name returned by the mount configured via the mount_accessor parameter If blank, the Alias's name field will be used as-is.
   */
  username_format?: string
}

/* @anchor:file:end */
