// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface MfaGenerateTotpSecretRequest {
  /**
   * The unique identifier for this MFA method.
   */
  method_id: string
}

/* @anchor:file:end */
