// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface MfaValidateRequest {
  /**
   * A map from MFA method ID to a slice of passcodes or an empty slice if the method does not use passcodes
   * @format map
   */
  mfa_payload: Record<string, never>
  /**
   * ID for this MFA request
   */
  mfa_request_id: string
}

/* @anchor:file:end */
