// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface MfaAdminGenerateTotpSecretRequest {
  /**
   * Entity ID on which the generated secret needs to get stored.
   */
  entity_id: string
  /**
   * The unique identifier for this MFA method.
   */
  method_id: string
}

/* @anchor:file:end */
