// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface MountsTuneConfigurationParametersRequest {
  allowed_managed_keys?: string[]
  /**
   * A list of headers to whitelist and allow a plugin to set on responses.
   */
  allowed_response_headers?: string[]
  /**
   * The list of keys in the request data object that will not be HMAC'ed by audit devices.
   */
  audit_non_hmac_request_keys?: string[]
  /**
   * The list of keys in the response data object that will not be HMAC'ed by audit devices.
   */
  audit_non_hmac_response_keys?: string[]
  /**
   * The default lease TTL for this mount.
   */
  default_lease_ttl?: string
  /**
   * User-friendly description for this credential backend.
   */
  description?: string
  /**
   * Determines the visibility of the mount in the UI-specific listing endpoint. Accepted value are 'unauth' and 'hidden', with the empty default ('') behaving like 'hidden'.
   */
  listing_visibility?: string
  /**
   * The max lease TTL for this mount.
   */
  max_lease_ttl?: string
  /**
   * The options to pass into the backend. Should be a json object with string keys and values.
   * @format kvpairs
   */
  options?: Record<string, never>
  /**
   * A list of headers to whitelist and pass from the request to the plugin.
   */
  passthrough_request_headers?: string[]
  /**
   * The semantic version of the plugin to use.
   */
  plugin_version?: string
  /**
   * The type of token to issue (service or batch).
   */
  token_type?: string
  /**
   * The user lockout configuration to pass into the backend. Should be a json object with string keys and values.
   * @format map
   */
  user_lockout_config?: Record<string, never>
}

/* @anchor:file:end */
