// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface MountsEnableSecretsEngineRequest {
  /**
   * Configuration for this mount, such as default_lease_ttl and max_lease_ttl.
   * @format map
   */
  config?: Record<string, never>
  /**
   * User-friendly description for this mount.
   */
  description?: string
  /**
   * Whether to give the mount access to OpenBao's external entropy.
   */
  external_entropy_access?: boolean
  /**
   * Mark the mount as a local mount, which is not replicated and is unaffected by replication.
   */
  local?: boolean
  /**
   * The options to pass into the backend. Should be a json object with string keys and values.
   * @format kvpairs
   */
  options?: Record<string, never>
  /**
   * Name of the plugin to mount based from the name registered in the plugin catalog.
   */
  plugin_name?: string
  /**
   * The semantic version of the plugin to use.
   */
  plugin_version?: string
  /**
   * Whether to turn on seal wrapping for the mount.
   */
  seal_wrap?: boolean
  /**
   * The type of the backend. Example: "passthrough"
   */
  type?: string
}

/* @anchor:file:end */
