// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface NamespacesWriteNamespacesPathRequest {
  /**
   * User provided key-value pairs.
   * @format map
   */
  custom_metadata?: Record<string, never>
}

/* @anchor:file:end */
