// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface NamespacesWriteNamespacesPathResponse {
  /**
   * User provided key-value pairs.
   * @format map
   */
  custom_metadata?: Record<string, never>
  /**
   * Accessor ID of the namespace.
   */
  id?: string
  /**
   * Flag representing the lock status of the namespace.
   */
  locked?: boolean
  /**
   * Path of the namespace.
   */
  path?: string
  /**
   * Flag representing the taint status of the namespace.
   */
  tainted?: boolean
  /**
   * Internal UUID of the namespace.
   */
  uuid?: string
}

/* @anchor:file:end */
