// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface NamespacesWriteNamespacesApiLockUnlockRequest {
  /**
   * Path of the namespace.
   */
  path?: string
  /**
   * Unlock key required for unlocking the namespace
   */
  unlock_key: string
}

/* @anchor:file:end */
