// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcIntrospectRequest {
  /**
   * Optional client_id to verify
   */
  client_id?: string
  /**
   * Token to verify
   */
  token?: string
}

/* @anchor:file:end */
