// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcWriteProviderRequest {
  /**
   * The client IDs that are permitted to use the provider
   */
  allowed_client_ids?: string[]
  /**
   * Specifies what will be used for the iss claim of ID tokens.
   */
  issuer?: string
  /**
   * The scopes supported for requesting on the provider
   */
  scopes_supported?: string[]
}

/* @anchor:file:end */
