// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcWriteClientRequest {
  /**
   * The time-to-live for access tokens obtained by the client.
   * @format seconds
   */
  access_token_ttl?: number
  /**
   * Comma separated string or array of assignment resources.
   */
  assignments?: string[]
  /**
   * Whether or not to authorization code flow is allowed in this provider
   */
  authorization_code?: boolean
  /**
   * Whether or not to client credentials flow is allowed in this provider
   */
  client_credentials?: boolean
  /**
   * The client type based on its ability to maintain confidentiality of credentials. The following client types are supported: 'confidential', 'public'. Defaults to 'confidential'.
   */
  client_type?: string
  /**
   * The time-to-live for ID tokens obtained by the client.
   * @format seconds
   */
  id_token_ttl?: number
  /**
   * A reference to a named key resource. Cannot be modified after creation. Defaults to the 'default' key.
   */
  key?: string
  /**
   * Comma separated string or array of redirect URIs used by the client. One of these values must exactly match the redirect_uri parameter value used in each authentication request.
   */
  redirect_uris?: string[]
}

/* @anchor:file:end */
