// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcWriteScopeRequest {
  /**
   * The description of the scope
   */
  description?: string
  /**
   * The template string to use for the scope. This may be in string-ified JSON or base64 format.
   */
  template?: string
}

/* @anchor:file:end */
