// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcWriteRoleRequest {
  /**
   * Optional client_id
   */
  client_id?: string
  /**
   * The OIDC key to use for generating tokens. The specified key must already exist.
   */
  key: string
  /**
   * The template string to use for generating tokens. This may be in string-ified JSON or base64 format.
   */
  template?: string
  /**
   * TTL of the tokens generated against the role.
   * @format seconds
   */
  ttl?: number
}

/* @anchor:file:end */
