// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcConfigureRequest {
  /**
   * Issuer URL to be used in the iss claim of the token. If not set, OpenBao's app_addr will be used.
   */
  issuer?: string
}

/* @anchor:file:end */
