// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcWriteKeyRequest {
  /**
   * Signing algorithm to use. This will default to RS256.
   */
  algorithm?: string
  /**
   * Comma separated string or array of role client ids allowed to use this key for signing. If empty no roles are allowed. If "*" all roles are allowed.
   */
  allowed_client_ids?: string[]
  /**
   * How often to generate a new keypair.
   * @format seconds
   */
  rotation_period?: number
  /**
   * Controls how long the public portion of a key will be available for verification after being rotated.
   * @format seconds
   */
  verification_ttl?: number
}

/* @anchor:file:end */
