// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcWriteAssignmentRequest {
  /**
   * Comma separated string or array of identity entity IDs
   */
  entity_ids?: string[]
  /**
   * Comma separated string or array of identity group IDs
   */
  group_ids?: string[]
}

/* @anchor:file:end */
