// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface OidcRotateKeyRequest {
  /**
   * Controls how long the public portion of a key will be available for verification after being rotated. Setting verification_ttl here will override the verification_ttl set on the key.
   * @format seconds
   */
  verification_ttl?: number
}

/* @anchor:file:end */
