// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface PersonaUpdateByIdRequest {
  /**
   * Entity ID to which this persona should be tied to
   */
  entity_id?: string
  /**
   * Metadata to be associated with the persona. In CLI, this parameter can be repeated multiple times, and it all gets merged together. For example: bao <command> <path> metadata=key1=value1 metadata=key2=value2
   * @format kvpairs
   */
  metadata?: Record<string, never>
  /**
   * Mount accessor to which this persona belongs to
   */
  mount_accessor?: string
  /**
   * Name of the persona
   */
  name?: string
}

/* @anchor:file:end */
