// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface PluginsCatalogListPluginsResponse {
  /**
   * @format map
   */
  detailed?: Record<string, never>
}

/* @anchor:file:end */
