// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface PluginsReloadBackendsRequest {
  /**
   * The mount paths of the plugin backends to reload.
   */
  mounts?: string[]
  /**
   * The name of the plugin to reload, as registered in the plugin catalog.
   */
  plugin?: string
  scope?: string
}

/* @anchor:file:end */
