// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface PluginsCatalogRegisterPluginRequest {
  /**
   * The args passed to plugin command.
   */
  args?: string[]
  /**
   * The command used to start the plugin. The executable defined in this command must exist in OpenBao's plugin directory.
   */
  command?: string
  /**
   * The environment variables passed to plugin command. Each entry is of the form "key=value".
   */
  env?: string[]
  oci?: boolean
  /**
   * The SHA256 sum of the executable used in the command field. This should be HEX encoded.
   */
  sha256?: string
  /**
   * The type of the plugin, may be auth, secret, or database
   */
  type?: string
  /**
   * The semantic version of the plugin to use.
   */
  version?: string
}

/* @anchor:file:end */
