// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface PluginsCatalogListPluginsWithTypeResponse {
  /**
   * List of plugin names in the catalog
   */
  keys?: string[]
}

/* @anchor:file:end */
