// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface PoliciesReadAclPolicy2Response {
  cas_required?: boolean
  /**
   * @format date-time
   */
  expiration?: string
  /**
   * @format date-time
   */
  modified?: string
  name?: string
  policy?: string
  rules?: string
  version?: number
}

/* @anchor:file:end */
