// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface PoliciesWriteAclPolicy2Request {
  /**
   * The rules of the policy.
   */
  cas?: number
  /**
   * The rules of the policy.
   */
  cas_required?: boolean
  /**
   * The rules of the policy.
   * @format date-time
   */
  expiration?: string
  /**
   * The rules of the policy.
   */
  policy?: string
  /**
   * The rules of the policy.
   * @deprecated
   */
  rules?: string
  /**
   * The rules of the policy.
   * @format seconds
   */
  ttl?: number
}

/* @anchor:file:end */
