// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface QueryTokenCapabilitiesRequest {
  /**
   * Use 'paths' instead.
   * @deprecated
   */
  path?: string[]
  /**
   * Paths on which capabilities are being queried.
   */
  paths?: string[]
  /**
   * Token for which capabilities are being queried.
   */
  token?: string
}

/* @anchor:file:end */
