// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface QueryTokenAccessorCapabilitiesRequest {
  /**
   * Accessor of the token for which capabilities are being queried.
   */
  accessor?: string
  /**
   * Use 'paths' instead.
   * @deprecated
   */
  path?: string[]
  /**
   * Paths on which capabilities are being queried.
   */
  paths?: string[]
}

/* @anchor:file:end */
