// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RateLimitQuotasWriteRequest {
  /**
   * If set, when a client reaches a rate limit threshold, the client will be prohibited from any further requests until after the 'block_interval' has elapsed.
   * @format seconds
   */
  block_interval?: number
  /**
   * If set to true, child namespaces will use this quota, unless another more specific quota exists. Can only be set on namespace quotas. A quota on the root namespace will by default be inheritable.
   */
  inheritable?: boolean
  /**
   * The duration to enforce rate limiting for (default '1s').
   * @format seconds
   */
  interval?: number
  /**
   * Path of the mount or namespace to apply the quota. A blank path configures a global quota. For example namespace1/ adds a quota to a full namespace, namespace1/auth/userpass adds a quota to userpass in namespace1.
   */
  path?: string
  /**
   * The maximum number of requests in a given interval to be allowed by the quota rule. The 'rate' must be positive.
   * @format float
   */
  rate?: number
  /**
   * Login role to apply this quota to. Note that when set, path must be configured to a valid auth method with a concept of roles.
   */
  role?: string
  /**
   * Type of the quota rule.
   */
  type?: string
}

/* @anchor:file:end */
