// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RateLimitQuotasReadResponse {
  block_interval?: number
  inheritable?: boolean
  interval?: number
  name?: string
  path?: string
  /**
   * @format float
   */
  rate?: number
  role?: string
  type?: string
}

/* @anchor:file:end */
