// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RateLimitQuotasConfigureRequest {
  /**
   * If set, starts audit logging of requests that get rejected due to rate limit quota rule violations.
   */
  enable_rate_limit_audit_logging?: boolean
  /**
   * If set, additional rate limit quota HTTP headers will be added to responses.
   */
  enable_rate_limit_response_headers?: boolean
  /**
   * Specifies the list of exempt paths from all rate limit quotas. If empty no paths will be exempt.
   */
  rate_limit_exempt_paths?: string[]
}

/* @anchor:file:end */
