// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface ReadWrappingProperties2Response {
  creation_path?: string
  /**
   * @format date-time
   */
  creation_time?: string
  /**
   * @format seconds
   */
  creation_ttl?: number
}

/* @anchor:file:end */
