// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RekeyVerificationCancelResponse {
  n?: number
  nounce?: string
  progress?: number
  started?: string
  t?: number
}

/* @anchor:file:end */
