// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RekeyAttemptInitializeRequest {
  /**
   * Specifies if using PGP-encrypted keys, whether OpenBao should also store a plaintext backup of the PGP-encrypted keys.
   */
  backup?: boolean
  /**
   * Specifies an array of PGP public keys used to encrypt the output unseal keys. Ordering is preserved. The keys must be base64-encoded from their original binary representation. The size of this array must be the same as secret_shares.
   */
  pgp_keys?: string[]
  /**
   * Turns on verification functionality
   */
  require_verification?: boolean
  /**
   * Specifies the number of shares to split the unseal key into.
   */
  secret_shares?: number
  /**
   * Specifies the number of shares required to reconstruct the unseal key. This must be less than or equal secret_shares. If using OpenBao HSM with auto-unsealing, this value must be the same as secret_shares.
   */
  secret_threshold?: number
}

/* @anchor:file:end */
