// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RekeyReadBackupRecoveryKeyResponse {
  /**
   * @format map
   */
  keys?: Record<string, never>
  /**
   * @format map
   */
  keys_base64?: Record<string, never>
  nonce?: string
}

/* @anchor:file:end */
