// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RekeyAttemptInitializeResponse {
  backup?: boolean
  n?: number
  nounce?: string
  pgp_fingerprints?: string[]
  progress?: number
  required?: number
  started?: string
  t?: number
  verification_nonce?: string
  verification_required?: boolean
}

/* @anchor:file:end */
