// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RemountStatusResponse {
  migration_id?: string
  /**
   * @format map
   */
  migration_info?: Record<string, never>
}

/* @anchor:file:end */
