// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RemountRequest {
  /**
   * The previous mount point.
   */
  from?: string
  /**
   * The new mount point.
   */
  to?: string
}

/* @anchor:file:end */
