// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RootTokenGenerationInitialize2Request {
  /**
   * Specifies a base64-encoded PGP public key.
   */
  pgp_key?: string
}

/* @anchor:file:end */
