// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RootTokenGenerationInitialize2Response {
  complete?: boolean
  encoded_root_token?: string
  encoded_token?: string
  nonce?: string
  otp?: string
  otp_length?: number
  pgp_fingerprint?: string
  progress?: number
  required?: number
  started?: boolean
}

/* @anchor:file:end */
