// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RotateVerificationReadRotateRecoveryVerifyResponse {
  n?: number
  nonce?: string
  progress?: number
  started?: boolean
  t?: number
}

/* @anchor:file:end */
