// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RotateReadBackupKeyResponse {
  keys?: string[]
  keys_base64?: string[]
  nonce?: string
}

/* @anchor:file:end */
