// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RotateAttemptUpdateRotateRecoveryUpdateRequest {
  /**
   * Specifies a single unseal key share.
   */
  key?: string
  /**
   * Specifies the nonce of the rotation attempt.
   */
  nonce?: string
}

/* @anchor:file:end */
