// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RotateAttemptReadProgressResponse {
  /**
   * Specifies if using PGP-encrypted keys, whether OpenBao should also store a plaintext backup of the said keys.
   */
  backup?: boolean
  /**
   * Specifies an array of PGP public keys used to encrypt the output unseal keys.
   */
  pgp_keys?: string[]
  /**
   * Enables verification which after successful authorization with the current unseal keys, ensures the new unseal keys are returned but the root key is not actually rotated.
   */
  require_verification?: boolean
  /**
   * Specifies the number of shares to split the root key into.
   */
  secret_shares?: number
  /**
   * Specifies the number of shares required to reconstruct the root key.
   */
  secret_threshold?: number
}

/* @anchor:file:end */
