// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface RotateVerificationUpdateRotateRecoveryVerifyResponse {
  complete?: boolean
  nonce?: string
}

/* @anchor:file:end */
