// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface SetChainRequest {
  /**
   * PEM encoded certificate chain. It should be composed by one or more concatenated PEM blocks and ordered starting from the end-entity certificate.
   */
  certificate_chain: string
  /**
   * Version of the key to import the certificate chain against.
   */
  version?: number
}

/* @anchor:file:end */
