// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TokenLookUpByAccessorRequest {
  /**
   * Accessor of the token to look up (request body)
   */
  accessor?: string
}

/* @anchor:file:end */
