// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TokenRevokeAccessorRequest {
  /**
   * Accessor of the token (request body)
   */
  accessor?: string
}

/* @anchor:file:end */
