// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TokenRenewSelfRequest {
  /**
   * The desired increment in seconds to the token expiration
   * @format seconds
   */
  increment?: number
  /**
   * Token to renew (unused, does not need to be set)
   */
  token?: string
}

/* @anchor:file:end */
