// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TokenCreateAgainstRoleRequest {
  /**
   * Name to associate with this token
   */
  display_name?: string
  /**
   * Name of the entity alias to associate with this token
   */
  entity_alias?: string
  /**
   * Explicit Max TTL of this token
   */
  explicit_max_ttl?: string
  /**
   * Value for the token
   */
  id?: string
  /**
   * Use 'ttl' instead
   * @deprecated
   */
  lease?: string
  /**
   * Arbitrary key=value metadata to associate with the token
   * @format kvpairs
   */
  meta?: Record<string, never>
  /**
   * Do not include default policy for this token
   */
  no_default_policy?: boolean
  /**
   * Create the token with no parent
   */
  no_parent?: boolean
  /**
   * Max number of uses for this token
   */
  num_uses?: number
  /**
   * Renew period
   */
  period?: string
  /**
   * List of policies for the token
   */
  policies?: string[]
  /**
   * Allow token to be renewed past its initial TTL up to system/mount maximum TTL
   */
  renewable?: boolean
  /**
   * Time to live for this token
   */
  ttl?: string
  /**
   * Token type
   */
  type?: string
}

/* @anchor:file:end */
