// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TransitGenerateHmacRequest {
  /**
   * Algorithm to use (POST body parameter). Valid values are: * sha2-224 * sha2-256 * sha2-384 * sha2-512 * sha3-224 * sha3-256 * sha3-384 * sha3-512 Defaults to "sha2-256".
   */
  algorithm?: string
  /**
   * Specifies a list of items to be processed in a single batch. When this parameter is set, if the parameter 'input' is also set, it will be ignored. Any batch output will preserve the order of the batch input.
   */
  batch_input?: Record<string, never>[]
  /**
   * The base64-encoded input data
   */
  input?: string
  /**
   * The version of the key to use for generating the HMAC. Must be 0 (for latest) or a value greater than or equal to the min_encryption_version configured on the key.
   */
  key_version?: number
  /**
   * Algorithm to use (POST URL parameter)
   */
  urlalgorithm?: string
}

/* @anchor:file:end */
