// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TransitDeriveKeyRequest {
  /**
   * Name of the base key to use for derivation (own private key for ECDH)
   */
  base_key_name?: string
  /**
   * The version of the base key to use for derivation. Must be 0 (for latest) or a value greater than or equal to the min_derivation_version configured on the key.
   */
  base_key_version?: number
  /**
   * The type of the output derived key. Currently, "aes128-gcm96" , "aes256-gcm96", "chacha20-poly1305", "xchacha20-poly1305" are supported. Defaults to "aes256-gcm96".
   */
  derived_key_type?: string
  /**
   * Key derivation algorithm to use. Valid values are: * ecdh Defaults to "ecdh".
   */
  key_derivation_algorithm?: string
  /**
   * The pem-encoded other party's ECC public key
   */
  peer_public_key?: string
}

/* @anchor:file:end */
