// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TransitGenerateRandomWithBytesRequest {
  /**
   * The number of bytes to generate (POST body parameter). Defaults to 32 (256 bits).
   */
  bytes?: number
  /**
   * Encoding format to use. Can be "hex" or "base64". Defaults to "base64".
   */
  format?: string
  /**
   * Which system to source random data from, ether "platform", "seal", or "all".
   */
  source?: string
}

/* @anchor:file:end */
