// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TransitConfigureCacheRequest {
  /**
   * Size of cache, use 0 for an unlimited cache size, defaults to 0
   */
  size?: number
}

/* @anchor:file:end */
