// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface TransitConfigureKeyRequest {
  /**
   * Enables taking a backup of the named key in plaintext format. Once set, this cannot be disabled.
   */
  allow_plaintext_backup?: boolean
  /**
   * Amount of time the key should live before being automatically rotated. A value of 0 disables automatic rotation for the key.
   * @format seconds
   */
  auto_rotate_period?: number
  /**
   * Whether to allow deletion of the key
   */
  deletion_allowed?: boolean
  /**
   * Enables export of the key. Once set, this cannot be disabled.
   */
  exportable?: boolean
  /**
   * If set, the minimum version of the key allowed to be decrypted. For signing keys, the minimum version allowed to be used for verification.
   */
  min_decryption_version?: number
  /**
   * If set, the minimum version of the key allowed to be used for encryption; or for signing keys, to be used for signing. If set to zero, only the latest version of the key is allowed.
   */
  min_encryption_version?: number
}

/* @anchor:file:end */
