// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface UiHeadersReadConfigurationResponse {
  /**
   * returns the first header value when `multivalue` request parameter is false
   */
  value?: string
  /**
   * returns all header values when `multivalue` request parameter is true
   */
  values?: string[]
}

/* @anchor:file:end */
