// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface UiHeadersConfigureRequest {
  /**
   * Returns multiple values if true
   */
  multivalue?: boolean
  /**
   * The values to set the header.
   */
  values?: string[]
}

/* @anchor:file:end */
