// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface UnsealResponse {
  build_date?: string
  cluster_id?: string
  cluster_name?: string
  initialized?: boolean
  migration?: boolean
  n?: number
  nonce?: string
  progress?: number
  recovery_seal?: boolean
  sealed?: boolean
  storage_type?: string
  t?: number
  type?: string
  version?: string
}

/* @anchor:file:end */
