// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface UnsealRequest {
  /**
   * Specifies a single unseal key share. This is required unless reset is true.
   */
  key?: string
  /**
   * Specifies if previously-provided unseal keys are discarded and the unseal process is reset.
   */
  reset?: boolean
}

/* @anchor:file:end */
