// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface UserpassResetPasswordRequest {
  /**
   * Password for this user.
   */
  password?: string
}

/* @anchor:file:end */
