// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface UserpassWriteUserRequest {
  /**
   * Use "token_bound_cidrs" instead. If this and "token_bound_cidrs" are both specified, only "token_bound_cidrs" will be used.
   * @deprecated
   */
  bound_cidrs?: string[]
  /**
   * Use "token_max_ttl" instead. If this and "token_max_ttl" are both specified, only "token_max_ttl" will be used.
   * @deprecated
   * @format seconds
   */
  max_ttl?: number
  /**
   * Password for this user.
   */
  password?: string
  /**
   * Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
   * @deprecated
   */
  policies?: string[]
  /**
   * Comma separated string or JSON list of CIDR blocks. If set, specifies the blocks of IP addresses which are allowed to use the generated token.
   */
  token_bound_cidrs?: string[]
  /**
   * If set, tokens created via this role carry an explicit maximum TTL. During renewal, the current maximum TTL values of the role and the mount are not checked for changes, and any updates to these values will have no effect on the token being renewed.
   * @format seconds
   */
  token_explicit_max_ttl?: number
  /**
   * The maximum lifetime of the generated token
   * @format seconds
   */
  token_max_ttl?: number
  /**
   * If true, the 'default' policy will not automatically be added to generated tokens
   */
  token_no_default_policy?: boolean
  /**
   * The maximum number of times a token may be used, a value of zero means unlimited
   */
  token_num_uses?: number
  /**
   * If set, tokens created via this role will have no max lifetime; instead, their renewal period will be fixed to this value. This takes an integer number of seconds, or a string duration (e.g. "24h").
   * @format seconds
   */
  token_period?: number
  /**
   * Comma-separated list of policies
   */
  token_policies?: string[]
  /**
   * If true, CIDRs for the token will be strictly bound to the source IP address of the login request
   */
  token_strictly_bind_ip?: boolean
  /**
   * The initial ttl of the token to generate
   * @format seconds
   */
  token_ttl?: number
  /**
   * The type of token to generate, service or batch
   */
  token_type?: string
  /**
   * Use "token_ttl" instead. If this and "token_ttl" are both specified, only "token_ttl" will be used.
   * @deprecated
   * @format seconds
   */
  ttl?: number
}

/* @anchor:file:end */
