// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface UserpassUpdatePoliciesRequest {
  /**
   * Use "token_policies" instead. If this and "token_policies" are both specified, only "token_policies" will be used.
   * @deprecated
   */
  policies?: string[]
  /**
   * Comma-separated list of policies
   */
  token_policies?: string[]
}

/* @anchor:file:end */
