// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */


export interface VersionHistoryResponse {
  /**
   * @format kvpairs
   */
  key_info?: Record<string, never>
  keys?: string[]
}

/* @anchor:file:end */
