// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface AliasReadByIdResponseBodies {
  200: void
}

export interface AliasReadByIdRequestBodies {}

export type AliasReadByIdRequestQuery = {}

export type AliasReadByIdRouteParameters = {}

export type AliasReadByIdRequestHeaders = {}

export type AliasReadByIdRequestParameters = AliasReadByIdRequestQuery & AliasReadByIdRouteParameters & AliasReadByIdRequestHeaders

export interface AliasReadByIdOperation<STATUS extends keyof AliasReadByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AliasReadByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AliasReadByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AliasReadByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AliasReadByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
