// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AliasUpdateByIdRequest as AliasUpdateByIdRequestSchema } from '../components/schemas/alias-update-by-id-request.schema'

export interface AliasUpdateByIdResponseBodies {
  200: void
}

export interface AliasUpdateByIdRequestBodies {
  'application/json': AliasUpdateByIdRequestSchema
}

export type AliasUpdateByIdRequestQuery = {}

export type AliasUpdateByIdRouteParameters = {}

export type AliasUpdateByIdRequestHeaders = {}

interface AliasUpdateByIdParameterBodies {
  'application/json': AliasUpdateByIdRequestSchema & { [key: string]: any }
}

export type AliasUpdateByIdRequestParameters = AliasUpdateByIdRequestQuery & AliasUpdateByIdRouteParameters & AliasUpdateByIdRequestHeaders & AliasUpdateByIdRequestBodies['application/json']

export interface AliasUpdateByIdOperation<STATUS extends keyof AliasUpdateByIdResponseBodies, CONTENT_TYPE extends keyof AliasUpdateByIdParameterBodies> extends KeqOperation {
  requestParams: AliasUpdateByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AliasUpdateByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AliasUpdateByIdRequestHeaders & { [key: string]: string | number }
  requestBody: AliasUpdateByIdParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: AliasUpdateByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
