// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AuditingCalculateHashRequest as AuditingCalculateHashRequestSchema } from '../components/schemas/auditing-calculate-hash-request.schema'
import type { AuditingCalculateHashResponse as AuditingCalculateHashResponseSchema } from '../components/schemas/auditing-calculate-hash-response.schema'

export interface AuditingCalculateHashResponseBodies {
  200: AuditingCalculateHashResponseSchema
}

export interface AuditingCalculateHashRequestBodies {
  'application/json': AuditingCalculateHashRequestSchema
}

export type AuditingCalculateHashRequestQuery = {}

export type AuditingCalculateHashRouteParameters = {}

export type AuditingCalculateHashRequestHeaders = {}

interface AuditingCalculateHashParameterBodies {
  'application/json': AuditingCalculateHashRequestSchema & { [key: string]: any }
}

export type AuditingCalculateHashRequestParameters = AuditingCalculateHashRequestQuery & AuditingCalculateHashRouteParameters & AuditingCalculateHashRequestHeaders & AuditingCalculateHashRequestBodies['application/json']

export interface AuditingCalculateHashOperation<STATUS extends keyof AuditingCalculateHashResponseBodies, CONTENT_TYPE extends keyof AuditingCalculateHashParameterBodies> extends KeqOperation {
  requestParams: AuditingCalculateHashRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuditingCalculateHashRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuditingCalculateHashRequestHeaders & { [key: string]: string | number }
  requestBody: AuditingCalculateHashParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: AuditingCalculateHashResponseBodies[STATUS]
}

/* @anchor:file:end */
