// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface AuditingDisableDeviceResponseBodies {
  204: void
}

export interface AuditingDisableDeviceRequestBodies {}

export type AuditingDisableDeviceRequestQuery = {}

export type AuditingDisableDeviceRouteParameters = {}

export type AuditingDisableDeviceRequestHeaders = {}

export type AuditingDisableDeviceRequestParameters = AuditingDisableDeviceRequestQuery & AuditingDisableDeviceRouteParameters & AuditingDisableDeviceRequestHeaders

export interface AuditingDisableDeviceOperation<STATUS extends keyof AuditingDisableDeviceResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AuditingDisableDeviceRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuditingDisableDeviceRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuditingDisableDeviceRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AuditingDisableDeviceResponseBodies[STATUS]
}

/* @anchor:file:end */
