// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface AuditingListEnabledDevicesResponseBodies {
  200: void
}

export interface AuditingListEnabledDevicesRequestBodies {}

export type AuditingListEnabledDevicesRequestQuery = {}

export type AuditingListEnabledDevicesRouteParameters = {}

export type AuditingListEnabledDevicesRequestHeaders = {}

export type AuditingListEnabledDevicesRequestParameters = AuditingListEnabledDevicesRequestQuery & AuditingListEnabledDevicesRouteParameters & AuditingListEnabledDevicesRequestHeaders

export interface AuditingListEnabledDevicesOperation<STATUS extends keyof AuditingListEnabledDevicesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AuditingListEnabledDevicesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuditingListEnabledDevicesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuditingListEnabledDevicesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AuditingListEnabledDevicesResponseBodies[STATUS]
}

/* @anchor:file:end */
