// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface AuditingReadRequestHeaderInformationResponseBodies {
  200: void
}

export interface AuditingReadRequestHeaderInformationRequestBodies {}

export type AuditingReadRequestHeaderInformationRequestQuery = {}

export type AuditingReadRequestHeaderInformationRouteParameters = {}

export type AuditingReadRequestHeaderInformationRequestHeaders = {}

export type AuditingReadRequestHeaderInformationRequestParameters = AuditingReadRequestHeaderInformationRequestQuery & AuditingReadRequestHeaderInformationRouteParameters & AuditingReadRequestHeaderInformationRequestHeaders

export interface AuditingReadRequestHeaderInformationOperation<STATUS extends keyof AuditingReadRequestHeaderInformationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AuditingReadRequestHeaderInformationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuditingReadRequestHeaderInformationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuditingReadRequestHeaderInformationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AuditingReadRequestHeaderInformationResponseBodies[STATUS]
}

/* @anchor:file:end */
