// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AuditingListRequestHeadersResponse as AuditingListRequestHeadersResponseSchema } from '../components/schemas/auditing-list-request-headers-response.schema'

export interface AuditingListRequestHeadersResponseBodies {
  200: AuditingListRequestHeadersResponseSchema
}

export interface AuditingListRequestHeadersRequestBodies {}

export type AuditingListRequestHeadersRequestQuery = {}

export type AuditingListRequestHeadersRouteParameters = {}

export type AuditingListRequestHeadersRequestHeaders = {}

export type AuditingListRequestHeadersRequestParameters = AuditingListRequestHeadersRequestQuery & AuditingListRequestHeadersRouteParameters & AuditingListRequestHeadersRequestHeaders

export interface AuditingListRequestHeadersOperation<STATUS extends keyof AuditingListRequestHeadersResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AuditingListRequestHeadersRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuditingListRequestHeadersRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuditingListRequestHeadersRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AuditingListRequestHeadersResponseBodies[STATUS]
}

/* @anchor:file:end */
