// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AuditingEnableRequestHeaderRequest as AuditingEnableRequestHeaderRequestSchema } from '../components/schemas/auditing-enable-request-header-request.schema'

export interface AuditingEnableRequestHeaderResponseBodies {
  204: void
}

export interface AuditingEnableRequestHeaderRequestBodies {
  'application/json': AuditingEnableRequestHeaderRequestSchema
}

export type AuditingEnableRequestHeaderRequestQuery = {}

export type AuditingEnableRequestHeaderRouteParameters = {}

export type AuditingEnableRequestHeaderRequestHeaders = {}

interface AuditingEnableRequestHeaderParameterBodies {
  'application/json': AuditingEnableRequestHeaderRequestSchema & { [key: string]: any }
}

export type AuditingEnableRequestHeaderRequestParameters = AuditingEnableRequestHeaderRequestQuery & AuditingEnableRequestHeaderRouteParameters & AuditingEnableRequestHeaderRequestHeaders & AuditingEnableRequestHeaderRequestBodies['application/json']

export interface AuditingEnableRequestHeaderOperation<STATUS extends keyof AuditingEnableRequestHeaderResponseBodies, CONTENT_TYPE extends keyof AuditingEnableRequestHeaderParameterBodies> extends KeqOperation {
  requestParams: AuditingEnableRequestHeaderRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuditingEnableRequestHeaderRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuditingEnableRequestHeaderRequestHeaders & { [key: string]: string | number }
  requestBody: AuditingEnableRequestHeaderParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: AuditingEnableRequestHeaderResponseBodies[STATUS]
}

/* @anchor:file:end */
