// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AuditingEnableDeviceRequest as AuditingEnableDeviceRequestSchema } from '../components/schemas/auditing-enable-device-request.schema'

export interface AuditingEnableDeviceResponseBodies {
  204: void
}

export interface AuditingEnableDeviceRequestBodies {
  'application/json': AuditingEnableDeviceRequestSchema
}

export type AuditingEnableDeviceRequestQuery = {}

export type AuditingEnableDeviceRouteParameters = {}

export type AuditingEnableDeviceRequestHeaders = {}

interface AuditingEnableDeviceParameterBodies {
  'application/json': AuditingEnableDeviceRequestSchema & { [key: string]: any }
}

export type AuditingEnableDeviceRequestParameters = AuditingEnableDeviceRequestQuery & AuditingEnableDeviceRouteParameters & AuditingEnableDeviceRequestHeaders & AuditingEnableDeviceRequestBodies['application/json']

export interface AuditingEnableDeviceOperation<STATUS extends keyof AuditingEnableDeviceResponseBodies, CONTENT_TYPE extends keyof AuditingEnableDeviceParameterBodies> extends KeqOperation {
  requestParams: AuditingEnableDeviceRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuditingEnableDeviceRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuditingEnableDeviceRequestHeaders & { [key: string]: string | number }
  requestBody: AuditingEnableDeviceParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: AuditingEnableDeviceResponseBodies[STATUS]
}

/* @anchor:file:end */
