// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AuthTuneConfigurationParametersRequest as AuthTuneConfigurationParametersRequestSchema } from '../components/schemas/auth-tune-configuration-parameters-request.schema'

export interface AuthTuneConfigurationParametersResponseBodies {
  204: void
}

export interface AuthTuneConfigurationParametersRequestBodies {
  'application/json': AuthTuneConfigurationParametersRequestSchema
}

export type AuthTuneConfigurationParametersRequestQuery = {}

export type AuthTuneConfigurationParametersRouteParameters = {}

export type AuthTuneConfigurationParametersRequestHeaders = {}

interface AuthTuneConfigurationParametersParameterBodies {
  'application/json': AuthTuneConfigurationParametersRequestSchema & { [key: string]: any }
}

export type AuthTuneConfigurationParametersRequestParameters = AuthTuneConfigurationParametersRequestQuery & AuthTuneConfigurationParametersRouteParameters & AuthTuneConfigurationParametersRequestHeaders & AuthTuneConfigurationParametersRequestBodies['application/json']

export interface AuthTuneConfigurationParametersOperation<STATUS extends keyof AuthTuneConfigurationParametersResponseBodies, CONTENT_TYPE extends keyof AuthTuneConfigurationParametersParameterBodies> extends KeqOperation {
  requestParams: AuthTuneConfigurationParametersRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuthTuneConfigurationParametersRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuthTuneConfigurationParametersRequestHeaders & { [key: string]: string | number }
  requestBody: AuthTuneConfigurationParametersParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: AuthTuneConfigurationParametersResponseBodies[STATUS]
}

/* @anchor:file:end */
