// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface AuthDisableMethodResponseBodies {
  204: void
}

export interface AuthDisableMethodRequestBodies {}

export type AuthDisableMethodRequestQuery = {}

export type AuthDisableMethodRouteParameters = {}

export type AuthDisableMethodRequestHeaders = {}

export type AuthDisableMethodRequestParameters = AuthDisableMethodRequestQuery & AuthDisableMethodRouteParameters & AuthDisableMethodRequestHeaders

export interface AuthDisableMethodOperation<STATUS extends keyof AuthDisableMethodResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AuthDisableMethodRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuthDisableMethodRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuthDisableMethodRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AuthDisableMethodResponseBodies[STATUS]
}

/* @anchor:file:end */
