// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface AuthListEnabledMethodsResponseBodies {
  200: void
}

export interface AuthListEnabledMethodsRequestBodies {}

export type AuthListEnabledMethodsRequestQuery = {}

export type AuthListEnabledMethodsRouteParameters = {}

export type AuthListEnabledMethodsRequestHeaders = {}

export type AuthListEnabledMethodsRequestParameters = AuthListEnabledMethodsRequestQuery & AuthListEnabledMethodsRouteParameters & AuthListEnabledMethodsRequestHeaders

export interface AuthListEnabledMethodsOperation<STATUS extends keyof AuthListEnabledMethodsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AuthListEnabledMethodsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuthListEnabledMethodsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuthListEnabledMethodsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AuthListEnabledMethodsResponseBodies[STATUS]
}

/* @anchor:file:end */
