// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AuthReadConfigurationResponse as AuthReadConfigurationResponseSchema } from '../components/schemas/auth-read-configuration-response.schema'

export interface AuthReadConfigurationResponseBodies {
  200: AuthReadConfigurationResponseSchema
}

export interface AuthReadConfigurationRequestBodies {}

export type AuthReadConfigurationRequestQuery = {}

export type AuthReadConfigurationRouteParameters = {}

export type AuthReadConfigurationRequestHeaders = {}

export type AuthReadConfigurationRequestParameters = AuthReadConfigurationRequestQuery & AuthReadConfigurationRouteParameters & AuthReadConfigurationRequestHeaders

export interface AuthReadConfigurationOperation<STATUS extends keyof AuthReadConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AuthReadConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuthReadConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuthReadConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AuthReadConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
