// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AuthReadTuningInformationResponse as AuthReadTuningInformationResponseSchema } from '../components/schemas/auth-read-tuning-information-response.schema'

export interface AuthReadTuningInformationResponseBodies {
  200: AuthReadTuningInformationResponseSchema
}

export interface AuthReadTuningInformationRequestBodies {}

export type AuthReadTuningInformationRequestQuery = {}

export type AuthReadTuningInformationRouteParameters = {}

export type AuthReadTuningInformationRequestHeaders = {}

export type AuthReadTuningInformationRequestParameters = AuthReadTuningInformationRequestQuery & AuthReadTuningInformationRouteParameters & AuthReadTuningInformationRequestHeaders

export interface AuthReadTuningInformationOperation<STATUS extends keyof AuthReadTuningInformationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: AuthReadTuningInformationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuthReadTuningInformationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuthReadTuningInformationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: AuthReadTuningInformationResponseBodies[STATUS]
}

/* @anchor:file:end */
