// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { AuthEnableMethodRequest as AuthEnableMethodRequestSchema } from '../components/schemas/auth-enable-method-request.schema'

export interface AuthEnableMethodResponseBodies {
  204: void
}

export interface AuthEnableMethodRequestBodies {
  'application/json': AuthEnableMethodRequestSchema
}

export type AuthEnableMethodRequestQuery = {}

export type AuthEnableMethodRouteParameters = {}

export type AuthEnableMethodRequestHeaders = {}

interface AuthEnableMethodParameterBodies {
  'application/json': AuthEnableMethodRequestSchema & { [key: string]: any }
}

export type AuthEnableMethodRequestParameters = AuthEnableMethodRequestQuery & AuthEnableMethodRouteParameters & AuthEnableMethodRequestHeaders & AuthEnableMethodRequestBodies['application/json']

export interface AuthEnableMethodOperation<STATUS extends keyof AuthEnableMethodResponseBodies, CONTENT_TYPE extends keyof AuthEnableMethodParameterBodies> extends KeqOperation {
  requestParams: AuthEnableMethodRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: AuthEnableMethodRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: AuthEnableMethodRequestHeaders & { [key: string]: string | number }
  requestBody: AuthEnableMethodParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: AuthEnableMethodResponseBodies[STATUS]
}

/* @anchor:file:end */
