// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { CorsConfigureRequest as CorsConfigureRequestSchema } from '../components/schemas/cors-configure-request.schema'

export interface CorsConfigureResponseBodies {
  204: void
}

export interface CorsConfigureRequestBodies {
  'application/json': CorsConfigureRequestSchema
}

export type CorsConfigureRequestQuery = {}

export type CorsConfigureRouteParameters = {}

export type CorsConfigureRequestHeaders = {}

interface CorsConfigureParameterBodies {
  'application/json': CorsConfigureRequestSchema & { [key: string]: any }
}

export type CorsConfigureRequestParameters = CorsConfigureRequestQuery & CorsConfigureRouteParameters & CorsConfigureRequestHeaders & CorsConfigureRequestBodies['application/json']

export interface CorsConfigureOperation<STATUS extends keyof CorsConfigureResponseBodies, CONTENT_TYPE extends keyof CorsConfigureParameterBodies> extends KeqOperation {
  requestParams: CorsConfigureRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: CorsConfigureRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: CorsConfigureRequestHeaders & { [key: string]: string | number }
  requestBody: CorsConfigureParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: CorsConfigureResponseBodies[STATUS]
}

/* @anchor:file:end */
