// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface CorsDeleteConfigurationResponseBodies {
  204: void
}

export interface CorsDeleteConfigurationRequestBodies {}

export type CorsDeleteConfigurationRequestQuery = {}

export type CorsDeleteConfigurationRouteParameters = {}

export type CorsDeleteConfigurationRequestHeaders = {}

export type CorsDeleteConfigurationRequestParameters = CorsDeleteConfigurationRequestQuery & CorsDeleteConfigurationRouteParameters & CorsDeleteConfigurationRequestHeaders

export interface CorsDeleteConfigurationOperation<STATUS extends keyof CorsDeleteConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: CorsDeleteConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: CorsDeleteConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: CorsDeleteConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: CorsDeleteConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
