// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface CubbyholeWriteResponseBodies {
  200: void
}

export interface CubbyholeWriteRequestBodies {}

export type CubbyholeWriteRequestQuery = {}

export type CubbyholeWriteRouteParameters = {}

export type CubbyholeWriteRequestHeaders = {}

export type CubbyholeWriteRequestParameters = CubbyholeWriteRequestQuery & CubbyholeWriteRouteParameters & CubbyholeWriteRequestHeaders

export interface CubbyholeWriteOperation<STATUS extends keyof CubbyholeWriteResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: CubbyholeWriteRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: CubbyholeWriteRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: CubbyholeWriteRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: CubbyholeWriteResponseBodies[STATUS]
}

/* @anchor:file:end */
