// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface CubbyholeReadResponseBodies {
  200: void
}

export interface CubbyholeReadRequestBodies {}

export type CubbyholeReadRequestQuery = {
  list?: string
}

export type CubbyholeReadRouteParameters = {}

export type CubbyholeReadRequestHeaders = {}

export type CubbyholeReadRequestParameters = CubbyholeReadRequestQuery & CubbyholeReadRouteParameters & CubbyholeReadRequestHeaders

export interface CubbyholeReadOperation<STATUS extends keyof CubbyholeReadResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: CubbyholeReadRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: CubbyholeReadRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: CubbyholeReadRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: CubbyholeReadResponseBodies[STATUS]
}

/* @anchor:file:end */
