// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { DecodeRequest as DecodeRequestSchema } from '../components/schemas/decode-request.schema'

export interface DecodeResponseBodies {
  200: void
}

export interface DecodeRequestBodies {
  'application/json': DecodeRequestSchema
}

export type DecodeRequestQuery = {}

export type DecodeRouteParameters = {}

export type DecodeRequestHeaders = {}

interface DecodeParameterBodies {
  'application/json': DecodeRequestSchema & { [key: string]: any }
}

export type DecodeRequestParameters = DecodeRequestQuery & DecodeRouteParameters & DecodeRequestHeaders & DecodeRequestBodies['application/json']

export interface DecodeOperation<STATUS extends keyof DecodeResponseBodies, CONTENT_TYPE extends keyof DecodeParameterBodies> extends KeqOperation {
  requestParams: DecodeRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: DecodeRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: DecodeRequestHeaders & { [key: string]: string | number }
  requestBody: DecodeParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: DecodeResponseBodies[STATUS]
}

/* @anchor:file:end */
