// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { EncryptionKeyReadRotationConfigurationResponse as EncryptionKeyReadRotationConfigurationResponseSchema } from '../components/schemas/encryption-key-read-rotation-configuration-response.schema'

export interface EncryptionKeyReadRotationConfigurationResponseBodies {
  200: EncryptionKeyReadRotationConfigurationResponseSchema
}

export interface EncryptionKeyReadRotationConfigurationRequestBodies {}

export type EncryptionKeyReadRotationConfigurationRequestQuery = {}

export type EncryptionKeyReadRotationConfigurationRouteParameters = {}

export type EncryptionKeyReadRotationConfigurationRequestHeaders = {}

export type EncryptionKeyReadRotationConfigurationRequestParameters = EncryptionKeyReadRotationConfigurationRequestQuery & EncryptionKeyReadRotationConfigurationRouteParameters & EncryptionKeyReadRotationConfigurationRequestHeaders

export interface EncryptionKeyReadRotationConfigurationOperation<STATUS extends keyof EncryptionKeyReadRotationConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EncryptionKeyReadRotationConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EncryptionKeyReadRotationConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EncryptionKeyReadRotationConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EncryptionKeyReadRotationConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
