// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface EncryptionKeyRotateRotateKeyringResponseBodies {
  204: void
}

export interface EncryptionKeyRotateRotateKeyringRequestBodies {}

export type EncryptionKeyRotateRotateKeyringRequestQuery = {}

export type EncryptionKeyRotateRotateKeyringRouteParameters = {}

export type EncryptionKeyRotateRotateKeyringRequestHeaders = {}

export type EncryptionKeyRotateRotateKeyringRequestParameters = EncryptionKeyRotateRotateKeyringRequestQuery & EncryptionKeyRotateRotateKeyringRouteParameters & EncryptionKeyRotateRotateKeyringRequestHeaders

export interface EncryptionKeyRotateRotateKeyringOperation<STATUS extends keyof EncryptionKeyRotateRotateKeyringResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EncryptionKeyRotateRotateKeyringRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EncryptionKeyRotateRotateKeyringRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EncryptionKeyRotateRotateKeyringRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EncryptionKeyRotateRotateKeyringResponseBodies[STATUS]
}

/* @anchor:file:end */
