// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface EncryptionKeyRotateResponseBodies {
  204: void
}

export interface EncryptionKeyRotateRequestBodies {}

export type EncryptionKeyRotateRequestQuery = {}

export type EncryptionKeyRotateRouteParameters = {}

export type EncryptionKeyRotateRequestHeaders = {}

export type EncryptionKeyRotateRequestParameters = EncryptionKeyRotateRequestQuery & EncryptionKeyRotateRouteParameters & EncryptionKeyRotateRequestHeaders

export interface EncryptionKeyRotateOperation<STATUS extends keyof EncryptionKeyRotateResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EncryptionKeyRotateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EncryptionKeyRotateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EncryptionKeyRotateRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EncryptionKeyRotateResponseBodies[STATUS]
}

/* @anchor:file:end */
