// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { EncryptionKeyConfigureRotationConfigurationRequest as EncryptionKeyConfigureRotationConfigurationRequestSchema } from '../components/schemas/encryption-key-configure-rotation-configuration-request.schema'

export interface EncryptionKeyConfigureRotationConfigurationResponseBodies {
  204: void
}

export interface EncryptionKeyConfigureRotationConfigurationRequestBodies {
  'application/json': EncryptionKeyConfigureRotationConfigurationRequestSchema
}

export type EncryptionKeyConfigureRotationConfigurationRequestQuery = {}

export type EncryptionKeyConfigureRotationConfigurationRouteParameters = {}

export type EncryptionKeyConfigureRotationConfigurationRequestHeaders = {}

interface EncryptionKeyConfigureRotationConfigurationParameterBodies {
  'application/json': EncryptionKeyConfigureRotationConfigurationRequestSchema & { [key: string]: any }
}

export type EncryptionKeyConfigureRotationConfigurationRequestParameters = EncryptionKeyConfigureRotationConfigurationRequestQuery & EncryptionKeyConfigureRotationConfigurationRouteParameters & EncryptionKeyConfigureRotationConfigurationRequestHeaders & EncryptionKeyConfigureRotationConfigurationRequestBodies['application/json']

export interface EncryptionKeyConfigureRotationConfigurationOperation<STATUS extends keyof EncryptionKeyConfigureRotationConfigurationResponseBodies, CONTENT_TYPE extends keyof EncryptionKeyConfigureRotationConfigurationParameterBodies> extends KeqOperation {
  requestParams: EncryptionKeyConfigureRotationConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EncryptionKeyConfigureRotationConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EncryptionKeyConfigureRotationConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: EncryptionKeyConfigureRotationConfigurationParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: EncryptionKeyConfigureRotationConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
