// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { EntityUpdateByIdRequest as EntityUpdateByIdRequestSchema } from '../components/schemas/entity-update-by-id-request.schema'

export interface EntityUpdateByIdResponseBodies {
  200: void
}

export interface EntityUpdateByIdRequestBodies {
  'application/json': EntityUpdateByIdRequestSchema
}

export type EntityUpdateByIdRequestQuery = {}

export type EntityUpdateByIdRouteParameters = {}

export type EntityUpdateByIdRequestHeaders = {}

interface EntityUpdateByIdParameterBodies {
  'application/json': EntityUpdateByIdRequestSchema & { [key: string]: any }
}

export type EntityUpdateByIdRequestParameters = EntityUpdateByIdRequestQuery & EntityUpdateByIdRouteParameters & EntityUpdateByIdRequestHeaders & EntityUpdateByIdRequestBodies['application/json']

export interface EntityUpdateByIdOperation<STATUS extends keyof EntityUpdateByIdResponseBodies, CONTENT_TYPE extends keyof EntityUpdateByIdParameterBodies> extends KeqOperation {
  requestParams: EntityUpdateByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityUpdateByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityUpdateByIdRequestHeaders & { [key: string]: string | number }
  requestBody: EntityUpdateByIdParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: EntityUpdateByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
