// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface EntityDeleteAliasByIdResponseBodies {
  204: void
}

export interface EntityDeleteAliasByIdRequestBodies {}

export type EntityDeleteAliasByIdRequestQuery = {}

export type EntityDeleteAliasByIdRouteParameters = {}

export type EntityDeleteAliasByIdRequestHeaders = {}

export type EntityDeleteAliasByIdRequestParameters = EntityDeleteAliasByIdRequestQuery & EntityDeleteAliasByIdRouteParameters & EntityDeleteAliasByIdRequestHeaders

export interface EntityDeleteAliasByIdOperation<STATUS extends keyof EntityDeleteAliasByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EntityDeleteAliasByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityDeleteAliasByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityDeleteAliasByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EntityDeleteAliasByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
