// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { EntityCreateRequest as EntityCreateRequestSchema } from '../components/schemas/entity-create-request.schema'

export interface EntityCreateResponseBodies {
  200: void
}

export interface EntityCreateRequestBodies {
  'application/json': EntityCreateRequestSchema
}

export type EntityCreateRequestQuery = {}

export type EntityCreateRouteParameters = {}

export type EntityCreateRequestHeaders = {}

interface EntityCreateParameterBodies {
  'application/json': EntityCreateRequestSchema & { [key: string]: any }
}

export type EntityCreateRequestParameters = EntityCreateRequestQuery & EntityCreateRouteParameters & EntityCreateRequestHeaders & EntityCreateRequestBodies['application/json']

export interface EntityCreateOperation<STATUS extends keyof EntityCreateResponseBodies, CONTENT_TYPE extends keyof EntityCreateParameterBodies> extends KeqOperation {
  requestParams: EntityCreateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityCreateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityCreateRequestHeaders & { [key: string]: string | number }
  requestBody: EntityCreateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: EntityCreateResponseBodies[STATUS]
}

/* @anchor:file:end */
