// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface EntityReadAliasByIdResponseBodies {
  200: void
}

export interface EntityReadAliasByIdRequestBodies {}

export type EntityReadAliasByIdRequestQuery = {}

export type EntityReadAliasByIdRouteParameters = {}

export type EntityReadAliasByIdRequestHeaders = {}

export type EntityReadAliasByIdRequestParameters = EntityReadAliasByIdRequestQuery & EntityReadAliasByIdRouteParameters & EntityReadAliasByIdRequestHeaders

export interface EntityReadAliasByIdOperation<STATUS extends keyof EntityReadAliasByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EntityReadAliasByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityReadAliasByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityReadAliasByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EntityReadAliasByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
