// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { EntityLookUpRequest as EntityLookUpRequestSchema } from '../components/schemas/entity-look-up-request.schema'

export interface EntityLookUpResponseBodies {
  200: void
}

export interface EntityLookUpRequestBodies {
  'application/json': EntityLookUpRequestSchema
}

export type EntityLookUpRequestQuery = {}

export type EntityLookUpRouteParameters = {}

export type EntityLookUpRequestHeaders = {}

interface EntityLookUpParameterBodies {
  'application/json': EntityLookUpRequestSchema & { [key: string]: any }
}

export type EntityLookUpRequestParameters = EntityLookUpRequestQuery & EntityLookUpRouteParameters & EntityLookUpRequestHeaders & EntityLookUpRequestBodies['application/json']

export interface EntityLookUpOperation<STATUS extends keyof EntityLookUpResponseBodies, CONTENT_TYPE extends keyof EntityLookUpParameterBodies> extends KeqOperation {
  requestParams: EntityLookUpRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityLookUpRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityLookUpRequestHeaders & { [key: string]: string | number }
  requestBody: EntityLookUpParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: EntityLookUpResponseBodies[STATUS]
}

/* @anchor:file:end */
