// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface EntityDeleteByNameResponseBodies {
  204: void
}

export interface EntityDeleteByNameRequestBodies {}

export type EntityDeleteByNameRequestQuery = {}

export type EntityDeleteByNameRouteParameters = {}

export type EntityDeleteByNameRequestHeaders = {}

export type EntityDeleteByNameRequestParameters = EntityDeleteByNameRequestQuery & EntityDeleteByNameRouteParameters & EntityDeleteByNameRequestHeaders

export interface EntityDeleteByNameOperation<STATUS extends keyof EntityDeleteByNameResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EntityDeleteByNameRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityDeleteByNameRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityDeleteByNameRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EntityDeleteByNameResponseBodies[STATUS]
}

/* @anchor:file:end */
