// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { EntityBatchDeleteRequest as EntityBatchDeleteRequestSchema } from '../components/schemas/entity-batch-delete-request.schema'

export interface EntityBatchDeleteResponseBodies {
  200: void
}

export interface EntityBatchDeleteRequestBodies {
  'application/json': EntityBatchDeleteRequestSchema
}

export type EntityBatchDeleteRequestQuery = {}

export type EntityBatchDeleteRouteParameters = {}

export type EntityBatchDeleteRequestHeaders = {}

interface EntityBatchDeleteParameterBodies {
  'application/json': EntityBatchDeleteRequestSchema & { [key: string]: any }
}

export type EntityBatchDeleteRequestParameters = EntityBatchDeleteRequestQuery & EntityBatchDeleteRouteParameters & EntityBatchDeleteRequestHeaders & EntityBatchDeleteRequestBodies['application/json']

export interface EntityBatchDeleteOperation<STATUS extends keyof EntityBatchDeleteResponseBodies, CONTENT_TYPE extends keyof EntityBatchDeleteParameterBodies> extends KeqOperation {
  requestParams: EntityBatchDeleteRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityBatchDeleteRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityBatchDeleteRequestHeaders & { [key: string]: string | number }
  requestBody: EntityBatchDeleteParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: EntityBatchDeleteResponseBodies[STATUS]
}

/* @anchor:file:end */
