// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface EntityDeleteByIdResponseBodies {
  204: void
}

export interface EntityDeleteByIdRequestBodies {}

export type EntityDeleteByIdRequestQuery = {}

export type EntityDeleteByIdRouteParameters = {}

export type EntityDeleteByIdRequestHeaders = {}

export type EntityDeleteByIdRequestParameters = EntityDeleteByIdRequestQuery & EntityDeleteByIdRouteParameters & EntityDeleteByIdRequestHeaders

export interface EntityDeleteByIdOperation<STATUS extends keyof EntityDeleteByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EntityDeleteByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityDeleteByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityDeleteByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EntityDeleteByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
