// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface EntityListAliasesByIdResponseBodies {
  200: void
}

export interface EntityListAliasesByIdRequestBodies {}

export type EntityListAliasesByIdRequestQuery = {
  list: ('true')
}

export type EntityListAliasesByIdRouteParameters = {}

export type EntityListAliasesByIdRequestHeaders = {}

export type EntityListAliasesByIdRequestParameters = EntityListAliasesByIdRequestQuery & EntityListAliasesByIdRouteParameters & EntityListAliasesByIdRequestHeaders

export interface EntityListAliasesByIdOperation<STATUS extends keyof EntityListAliasesByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EntityListAliasesByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityListAliasesByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityListAliasesByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EntityListAliasesByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
