// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { EntityUpdateAliasByIdRequest as EntityUpdateAliasByIdRequestSchema } from '../components/schemas/entity-update-alias-by-id-request.schema'

export interface EntityUpdateAliasByIdResponseBodies {
  200: void
}

export interface EntityUpdateAliasByIdRequestBodies {
  'application/json': EntityUpdateAliasByIdRequestSchema
}

export type EntityUpdateAliasByIdRequestQuery = {}

export type EntityUpdateAliasByIdRouteParameters = {}

export type EntityUpdateAliasByIdRequestHeaders = {}

interface EntityUpdateAliasByIdParameterBodies {
  'application/json': EntityUpdateAliasByIdRequestSchema & { [key: string]: any }
}

export type EntityUpdateAliasByIdRequestParameters = EntityUpdateAliasByIdRequestQuery & EntityUpdateAliasByIdRouteParameters & EntityUpdateAliasByIdRequestHeaders & EntityUpdateAliasByIdRequestBodies['application/json']

export interface EntityUpdateAliasByIdOperation<STATUS extends keyof EntityUpdateAliasByIdResponseBodies, CONTENT_TYPE extends keyof EntityUpdateAliasByIdParameterBodies> extends KeqOperation {
  requestParams: EntityUpdateAliasByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityUpdateAliasByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityUpdateAliasByIdRequestHeaders & { [key: string]: string | number }
  requestBody: EntityUpdateAliasByIdParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: EntityUpdateAliasByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
