// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { EntityUpdateByNameRequest as EntityUpdateByNameRequestSchema } from '../components/schemas/entity-update-by-name-request.schema'

export interface EntityUpdateByNameResponseBodies {
  200: void
}

export interface EntityUpdateByNameRequestBodies {
  'application/json': EntityUpdateByNameRequestSchema
}

export type EntityUpdateByNameRequestQuery = {}

export type EntityUpdateByNameRouteParameters = {}

export type EntityUpdateByNameRequestHeaders = {}

interface EntityUpdateByNameParameterBodies {
  'application/json': EntityUpdateByNameRequestSchema & { [key: string]: any }
}

export type EntityUpdateByNameRequestParameters = EntityUpdateByNameRequestQuery & EntityUpdateByNameRouteParameters & EntityUpdateByNameRequestHeaders & EntityUpdateByNameRequestBodies['application/json']

export interface EntityUpdateByNameOperation<STATUS extends keyof EntityUpdateByNameResponseBodies, CONTENT_TYPE extends keyof EntityUpdateByNameParameterBodies> extends KeqOperation {
  requestParams: EntityUpdateByNameRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityUpdateByNameRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityUpdateByNameRequestHeaders & { [key: string]: string | number }
  requestBody: EntityUpdateByNameParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: EntityUpdateByNameResponseBodies[STATUS]
}

/* @anchor:file:end */
