// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface EntityReadByIdResponseBodies {
  200: void
}

export interface EntityReadByIdRequestBodies {}

export type EntityReadByIdRequestQuery = {}

export type EntityReadByIdRouteParameters = {}

export type EntityReadByIdRequestHeaders = {}

export type EntityReadByIdRequestParameters = EntityReadByIdRequestQuery & EntityReadByIdRouteParameters & EntityReadByIdRequestHeaders

export interface EntityReadByIdOperation<STATUS extends keyof EntityReadByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: EntityReadByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: EntityReadByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: EntityReadByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: EntityReadByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
