// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GenerateRandomRequest as GenerateRandomRequestSchema } from '../components/schemas/generate-random-request.schema'
import type { GenerateRandomResponse as GenerateRandomResponseSchema } from '../components/schemas/generate-random-response.schema'

export interface GenerateRandomResponseBodies {
  200: GenerateRandomResponseSchema
}

export interface GenerateRandomRequestBodies {
  'application/json': GenerateRandomRequestSchema
}

export type GenerateRandomRequestQuery = {}

export type GenerateRandomRouteParameters = {}

export type GenerateRandomRequestHeaders = {}

interface GenerateRandomParameterBodies {
  'application/json': GenerateRandomRequestSchema & { [key: string]: any }
}

export type GenerateRandomRequestParameters = GenerateRandomRequestQuery & GenerateRandomRouteParameters & GenerateRandomRequestHeaders & GenerateRandomRequestBodies['application/json']

export interface GenerateRandomOperation<STATUS extends keyof GenerateRandomResponseBodies, CONTENT_TYPE extends keyof GenerateRandomParameterBodies> extends KeqOperation {
  requestParams: GenerateRandomRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GenerateRandomRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GenerateRandomRequestHeaders & { [key: string]: string | number }
  requestBody: GenerateRandomParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GenerateRandomResponseBodies[STATUS]
}

/* @anchor:file:end */
