// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GenerateRandomWithSourceAndBytesRequest as GenerateRandomWithSourceAndBytesRequestSchema } from '../components/schemas/generate-random-with-source-and-bytes-request.schema'
import type { GenerateRandomWithSourceAndBytesResponse as GenerateRandomWithSourceAndBytesResponseSchema } from '../components/schemas/generate-random-with-source-and-bytes-response.schema'

export interface GenerateRandomWithSourceAndBytesResponseBodies {
  200: GenerateRandomWithSourceAndBytesResponseSchema
}

export interface GenerateRandomWithSourceAndBytesRequestBodies {
  'application/json': GenerateRandomWithSourceAndBytesRequestSchema
}

export type GenerateRandomWithSourceAndBytesRequestQuery = {}

export type GenerateRandomWithSourceAndBytesRouteParameters = {}

export type GenerateRandomWithSourceAndBytesRequestHeaders = {}

interface GenerateRandomWithSourceAndBytesParameterBodies {
  'application/json': GenerateRandomWithSourceAndBytesRequestSchema & { [key: string]: any }
}

export type GenerateRandomWithSourceAndBytesRequestParameters = GenerateRandomWithSourceAndBytesRequestQuery & GenerateRandomWithSourceAndBytesRouteParameters & GenerateRandomWithSourceAndBytesRequestHeaders & GenerateRandomWithSourceAndBytesRequestBodies['application/json']

export interface GenerateRandomWithSourceAndBytesOperation<STATUS extends keyof GenerateRandomWithSourceAndBytesResponseBodies, CONTENT_TYPE extends keyof GenerateRandomWithSourceAndBytesParameterBodies> extends KeqOperation {
  requestParams: GenerateRandomWithSourceAndBytesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GenerateRandomWithSourceAndBytesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GenerateRandomWithSourceAndBytesRequestHeaders & { [key: string]: string | number }
  requestBody: GenerateRandomWithSourceAndBytesParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GenerateRandomWithSourceAndBytesResponseBodies[STATUS]
}

/* @anchor:file:end */
