// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GenerateHashRequest as GenerateHashRequestSchema } from '../components/schemas/generate-hash-request.schema'
import type { GenerateHashResponse as GenerateHashResponseSchema } from '../components/schemas/generate-hash-response.schema'

export interface GenerateHashResponseBodies {
  200: GenerateHashResponseSchema
}

export interface GenerateHashRequestBodies {
  'application/json': GenerateHashRequestSchema
}

export type GenerateHashRequestQuery = {}

export type GenerateHashRouteParameters = {}

export type GenerateHashRequestHeaders = {}

interface GenerateHashParameterBodies {
  'application/json': GenerateHashRequestSchema & { [key: string]: any }
}

export type GenerateHashRequestParameters = GenerateHashRequestQuery & GenerateHashRouteParameters & GenerateHashRequestHeaders & GenerateHashRequestBodies['application/json']

export interface GenerateHashOperation<STATUS extends keyof GenerateHashResponseBodies, CONTENT_TYPE extends keyof GenerateHashParameterBodies> extends KeqOperation {
  requestParams: GenerateHashRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GenerateHashRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GenerateHashRequestHeaders & { [key: string]: string | number }
  requestBody: GenerateHashParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GenerateHashResponseBodies[STATUS]
}

/* @anchor:file:end */
