// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GenerateHashWithAlgorithmRequest as GenerateHashWithAlgorithmRequestSchema } from '../components/schemas/generate-hash-with-algorithm-request.schema'
import type { GenerateHashWithAlgorithmResponse as GenerateHashWithAlgorithmResponseSchema } from '../components/schemas/generate-hash-with-algorithm-response.schema'

export interface GenerateHashWithAlgorithmResponseBodies {
  200: GenerateHashWithAlgorithmResponseSchema
}

export interface GenerateHashWithAlgorithmRequestBodies {
  'application/json': GenerateHashWithAlgorithmRequestSchema
}

export type GenerateHashWithAlgorithmRequestQuery = {}

export type GenerateHashWithAlgorithmRouteParameters = {}

export type GenerateHashWithAlgorithmRequestHeaders = {}

interface GenerateHashWithAlgorithmParameterBodies {
  'application/json': GenerateHashWithAlgorithmRequestSchema & { [key: string]: any }
}

export type GenerateHashWithAlgorithmRequestParameters = GenerateHashWithAlgorithmRequestQuery & GenerateHashWithAlgorithmRouteParameters & GenerateHashWithAlgorithmRequestHeaders & GenerateHashWithAlgorithmRequestBodies['application/json']

export interface GenerateHashWithAlgorithmOperation<STATUS extends keyof GenerateHashWithAlgorithmResponseBodies, CONTENT_TYPE extends keyof GenerateHashWithAlgorithmParameterBodies> extends KeqOperation {
  requestParams: GenerateHashWithAlgorithmRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GenerateHashWithAlgorithmRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GenerateHashWithAlgorithmRequestHeaders & { [key: string]: string | number }
  requestBody: GenerateHashWithAlgorithmParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GenerateHashWithAlgorithmResponseBodies[STATUS]
}

/* @anchor:file:end */
