// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface GroupReadByNameResponseBodies {
  200: void
}

export interface GroupReadByNameRequestBodies {}

export type GroupReadByNameRequestQuery = {}

export type GroupReadByNameRouteParameters = {}

export type GroupReadByNameRequestHeaders = {}

export type GroupReadByNameRequestParameters = GroupReadByNameRequestQuery & GroupReadByNameRouteParameters & GroupReadByNameRequestHeaders

export interface GroupReadByNameOperation<STATUS extends keyof GroupReadByNameResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: GroupReadByNameRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupReadByNameRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupReadByNameRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: GroupReadByNameResponseBodies[STATUS]
}

/* @anchor:file:end */
