// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GroupLookUpRequest as GroupLookUpRequestSchema } from '../components/schemas/group-look-up-request.schema'

export interface GroupLookUpResponseBodies {
  200: void
}

export interface GroupLookUpRequestBodies {
  'application/json': GroupLookUpRequestSchema
}

export type GroupLookUpRequestQuery = {}

export type GroupLookUpRouteParameters = {}

export type GroupLookUpRequestHeaders = {}

interface GroupLookUpParameterBodies {
  'application/json': GroupLookUpRequestSchema & { [key: string]: any }
}

export type GroupLookUpRequestParameters = GroupLookUpRequestQuery & GroupLookUpRouteParameters & GroupLookUpRequestHeaders & GroupLookUpRequestBodies['application/json']

export interface GroupLookUpOperation<STATUS extends keyof GroupLookUpResponseBodies, CONTENT_TYPE extends keyof GroupLookUpParameterBodies> extends KeqOperation {
  requestParams: GroupLookUpRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupLookUpRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupLookUpRequestHeaders & { [key: string]: string | number }
  requestBody: GroupLookUpParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GroupLookUpResponseBodies[STATUS]
}

/* @anchor:file:end */
