// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface GroupListAliasesByIdResponseBodies {
  200: void
}

export interface GroupListAliasesByIdRequestBodies {}

export type GroupListAliasesByIdRequestQuery = {
  list: 'true'
}

export type GroupListAliasesByIdRouteParameters = {}

export type GroupListAliasesByIdRequestHeaders = {}

export type GroupListAliasesByIdRequestParameters = GroupListAliasesByIdRequestQuery & GroupListAliasesByIdRouteParameters & GroupListAliasesByIdRequestHeaders

export interface GroupListAliasesByIdOperation<STATUS extends keyof GroupListAliasesByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: GroupListAliasesByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupListAliasesByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupListAliasesByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: GroupListAliasesByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
