// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GroupCreateRequest as GroupCreateRequestSchema } from '../components/schemas/group-create-request.schema'

export interface GroupCreateResponseBodies {
  200: void
}

export interface GroupCreateRequestBodies {
  'application/json': GroupCreateRequestSchema
}

export type GroupCreateRequestQuery = {}

export type GroupCreateRouteParameters = {}

export type GroupCreateRequestHeaders = {}

interface GroupCreateParameterBodies {
  'application/json': GroupCreateRequestSchema & { [key: string]: any }
}

export type GroupCreateRequestParameters = GroupCreateRequestQuery & GroupCreateRouteParameters & GroupCreateRequestHeaders & GroupCreateRequestBodies['application/json']

export interface GroupCreateOperation<STATUS extends keyof GroupCreateResponseBodies, CONTENT_TYPE extends keyof GroupCreateParameterBodies> extends KeqOperation {
  requestParams: GroupCreateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupCreateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupCreateRequestHeaders & { [key: string]: string | number }
  requestBody: GroupCreateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GroupCreateResponseBodies[STATUS]
}

/* @anchor:file:end */
