// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GroupUpdateAliasByIdRequest as GroupUpdateAliasByIdRequestSchema } from '../components/schemas/group-update-alias-by-id-request.schema'

export interface GroupUpdateAliasByIdResponseBodies {
  200: void
}

export interface GroupUpdateAliasByIdRequestBodies {
  'application/json': GroupUpdateAliasByIdRequestSchema
}

export type GroupUpdateAliasByIdRequestQuery = {}

export type GroupUpdateAliasByIdRouteParameters = {}

export type GroupUpdateAliasByIdRequestHeaders = {}

interface GroupUpdateAliasByIdParameterBodies {
  'application/json': GroupUpdateAliasByIdRequestSchema & { [key: string]: any }
}

export type GroupUpdateAliasByIdRequestParameters = GroupUpdateAliasByIdRequestQuery & GroupUpdateAliasByIdRouteParameters & GroupUpdateAliasByIdRequestHeaders & GroupUpdateAliasByIdRequestBodies['application/json']

export interface GroupUpdateAliasByIdOperation<STATUS extends keyof GroupUpdateAliasByIdResponseBodies, CONTENT_TYPE extends keyof GroupUpdateAliasByIdParameterBodies> extends KeqOperation {
  requestParams: GroupUpdateAliasByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupUpdateAliasByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupUpdateAliasByIdRequestHeaders & { [key: string]: string | number }
  requestBody: GroupUpdateAliasByIdParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GroupUpdateAliasByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
