// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GroupUpdateByIdRequest as GroupUpdateByIdRequestSchema } from '../components/schemas/group-update-by-id-request.schema'

export interface GroupUpdateByIdResponseBodies {
  200: void
}

export interface GroupUpdateByIdRequestBodies {
  'application/json': GroupUpdateByIdRequestSchema
}

export type GroupUpdateByIdRequestQuery = {}

export type GroupUpdateByIdRouteParameters = {}

export type GroupUpdateByIdRequestHeaders = {}

interface GroupUpdateByIdParameterBodies {
  'application/json': GroupUpdateByIdRequestSchema & { [key: string]: any }
}

export type GroupUpdateByIdRequestParameters = GroupUpdateByIdRequestQuery & GroupUpdateByIdRouteParameters & GroupUpdateByIdRequestHeaders & GroupUpdateByIdRequestBodies['application/json']

export interface GroupUpdateByIdOperation<STATUS extends keyof GroupUpdateByIdResponseBodies, CONTENT_TYPE extends keyof GroupUpdateByIdParameterBodies> extends KeqOperation {
  requestParams: GroupUpdateByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupUpdateByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupUpdateByIdRequestHeaders & { [key: string]: string | number }
  requestBody: GroupUpdateByIdParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GroupUpdateByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
