// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface GroupDeleteByIdResponseBodies {
  204: void
}

export interface GroupDeleteByIdRequestBodies {}

export type GroupDeleteByIdRequestQuery = {}

export type GroupDeleteByIdRouteParameters = {}

export type GroupDeleteByIdRequestHeaders = {}

export type GroupDeleteByIdRequestParameters = GroupDeleteByIdRequestQuery & GroupDeleteByIdRouteParameters & GroupDeleteByIdRequestHeaders

export interface GroupDeleteByIdOperation<STATUS extends keyof GroupDeleteByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: GroupDeleteByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupDeleteByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupDeleteByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: GroupDeleteByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
