// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { GroupCreateAliasRequest as GroupCreateAliasRequestSchema } from '../components/schemas/group-create-alias-request.schema'

export interface GroupCreateAliasResponseBodies {
  200: void
}

export interface GroupCreateAliasRequestBodies {
  'application/json': GroupCreateAliasRequestSchema
}

export type GroupCreateAliasRequestQuery = {}

export type GroupCreateAliasRouteParameters = {}

export type GroupCreateAliasRequestHeaders = {}

interface GroupCreateAliasParameterBodies {
  'application/json': GroupCreateAliasRequestSchema & { [key: string]: any }
}

export type GroupCreateAliasRequestParameters = GroupCreateAliasRequestQuery & GroupCreateAliasRouteParameters & GroupCreateAliasRequestHeaders & GroupCreateAliasRequestBodies['application/json']

export interface GroupCreateAliasOperation<STATUS extends keyof GroupCreateAliasResponseBodies, CONTENT_TYPE extends keyof GroupCreateAliasParameterBodies> extends KeqOperation {
  requestParams: GroupCreateAliasRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupCreateAliasRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupCreateAliasRequestHeaders & { [key: string]: string | number }
  requestBody: GroupCreateAliasParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: GroupCreateAliasResponseBodies[STATUS]
}

/* @anchor:file:end */
