// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface GroupReadByIdResponseBodies {
  200: void
}

export interface GroupReadByIdRequestBodies {}

export type GroupReadByIdRequestQuery = {}

export type GroupReadByIdRouteParameters = {}

export type GroupReadByIdRequestHeaders = {}

export type GroupReadByIdRequestParameters = GroupReadByIdRequestQuery & GroupReadByIdRouteParameters & GroupReadByIdRequestHeaders

export interface GroupReadByIdOperation<STATUS extends keyof GroupReadByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: GroupReadByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupReadByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupReadByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: GroupReadByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
