// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface GroupReadAliasByIdResponseBodies {
  200: void
}

export interface GroupReadAliasByIdRequestBodies {}

export type GroupReadAliasByIdRequestQuery = {}

export type GroupReadAliasByIdRouteParameters = {}

export type GroupReadAliasByIdRequestHeaders = {}

export type GroupReadAliasByIdRequestParameters = GroupReadAliasByIdRequestQuery & GroupReadAliasByIdRouteParameters & GroupReadAliasByIdRequestHeaders

export interface GroupReadAliasByIdOperation<STATUS extends keyof GroupReadAliasByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: GroupReadAliasByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupReadAliasByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupReadAliasByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: GroupReadAliasByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
