// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface GroupDeleteAliasByIdResponseBodies {
  204: void
}

export interface GroupDeleteAliasByIdRequestBodies {}

export type GroupDeleteAliasByIdRequestQuery = {}

export type GroupDeleteAliasByIdRouteParameters = {}

export type GroupDeleteAliasByIdRequestHeaders = {}

export type GroupDeleteAliasByIdRequestParameters = GroupDeleteAliasByIdRequestQuery & GroupDeleteAliasByIdRouteParameters & GroupDeleteAliasByIdRequestHeaders

export interface GroupDeleteAliasByIdOperation<STATUS extends keyof GroupDeleteAliasByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: GroupDeleteAliasByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: GroupDeleteAliasByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: GroupDeleteAliasByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: GroupDeleteAliasByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
