// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { HaStatusResponse as HaStatusResponseSchema } from '../components/schemas/ha-status-response.schema'

export interface HaStatusResponseBodies {
  200: HaStatusResponseSchema
}

export interface HaStatusRequestBodies {}

export type HaStatusRequestQuery = {}

export type HaStatusRouteParameters = {}

export type HaStatusRequestHeaders = {}

export type HaStatusRequestParameters = HaStatusRequestQuery & HaStatusRouteParameters & HaStatusRequestHeaders

export interface HaStatusOperation<STATUS extends keyof HaStatusResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: HaStatusRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: HaStatusRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: HaStatusRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: HaStatusResponseBodies[STATUS]
}

/* @anchor:file:end */
