// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { InitializeSystemRequest as InitializeSystemRequestSchema } from '../components/schemas/initialize-system-request.schema'

export interface InitializeSystemResponseBodies {
  200: void
}

export interface InitializeSystemRequestBodies {
  'application/json': InitializeSystemRequestSchema
}

export type InitializeSystemRequestQuery = {}

export type InitializeSystemRouteParameters = {}

export type InitializeSystemRequestHeaders = {}

interface InitializeSystemParameterBodies {
  'application/json': InitializeSystemRequestSchema & { [key: string]: any }
}

export type InitializeSystemRequestParameters = InitializeSystemRequestQuery & InitializeSystemRouteParameters & InitializeSystemRequestHeaders & InitializeSystemRequestBodies['application/json']

export interface InitializeSystemOperation<STATUS extends keyof InitializeSystemResponseBodies, CONTENT_TYPE extends keyof InitializeSystemParameterBodies> extends KeqOperation {
  requestParams: InitializeSystemRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: InitializeSystemRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: InitializeSystemRequestHeaders & { [key: string]: string | number }
  requestBody: InitializeSystemParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: InitializeSystemResponseBodies[STATUS]
}

/* @anchor:file:end */
