// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { InternalCountTokensResponse as InternalCountTokensResponseSchema } from '../components/schemas/internal-count-tokens-response.schema'

export interface InternalCountTokensResponseBodies {
  200: InternalCountTokensResponseSchema
}

export interface InternalCountTokensRequestBodies {}

export type InternalCountTokensRequestQuery = {}

export type InternalCountTokensRouteParameters = {}

export type InternalCountTokensRequestHeaders = {}

export type InternalCountTokensRequestParameters = InternalCountTokensRequestQuery & InternalCountTokensRouteParameters & InternalCountTokensRequestHeaders

export interface InternalCountTokensOperation<STATUS extends keyof InternalCountTokensResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: InternalCountTokensRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: InternalCountTokensRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: InternalCountTokensRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: InternalCountTokensResponseBodies[STATUS]
}

/* @anchor:file:end */
