// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface InternalGenerateOpenApiDocumentResponseBodies {
  200: void
}

export interface InternalGenerateOpenApiDocumentRequestBodies {}

export type InternalGenerateOpenApiDocumentRequestQuery = {}

export type InternalGenerateOpenApiDocumentRouteParameters = {}

export type InternalGenerateOpenApiDocumentRequestHeaders = {}

export type InternalGenerateOpenApiDocumentRequestParameters = InternalGenerateOpenApiDocumentRequestQuery & InternalGenerateOpenApiDocumentRouteParameters & InternalGenerateOpenApiDocumentRequestHeaders

export interface InternalGenerateOpenApiDocumentOperation<STATUS extends keyof InternalGenerateOpenApiDocumentResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: InternalGenerateOpenApiDocumentRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: InternalGenerateOpenApiDocumentRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: InternalGenerateOpenApiDocumentRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: InternalGenerateOpenApiDocumentResponseBodies[STATUS]
}

/* @anchor:file:end */
