// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { InternalCountEntitiesResponse as InternalCountEntitiesResponseSchema } from '../components/schemas/internal-count-entities-response.schema'

export interface InternalCountEntitiesResponseBodies {
  200: InternalCountEntitiesResponseSchema
}

export interface InternalCountEntitiesRequestBodies {}

export type InternalCountEntitiesRequestQuery = {}

export type InternalCountEntitiesRouteParameters = {}

export type InternalCountEntitiesRequestHeaders = {}

export type InternalCountEntitiesRequestParameters = InternalCountEntitiesRequestQuery & InternalCountEntitiesRouteParameters & InternalCountEntitiesRequestHeaders

export interface InternalCountEntitiesOperation<STATUS extends keyof InternalCountEntitiesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: InternalCountEntitiesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: InternalCountEntitiesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: InternalCountEntitiesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: InternalCountEntitiesResponseBodies[STATUS]
}

/* @anchor:file:end */
