// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { InternalUiReadResultantAclResponse as InternalUiReadResultantAclResponseSchema } from '../components/schemas/internal-ui-read-resultant-acl-response.schema'

export interface InternalUiReadResultantAclResponseBodies {
  200: InternalUiReadResultantAclResponseSchema
  204: void
}

export interface InternalUiReadResultantAclRequestBodies {}

export type InternalUiReadResultantAclRequestQuery = {}

export type InternalUiReadResultantAclRouteParameters = {}

export type InternalUiReadResultantAclRequestHeaders = {}

export type InternalUiReadResultantAclRequestParameters = InternalUiReadResultantAclRequestQuery & InternalUiReadResultantAclRouteParameters & InternalUiReadResultantAclRequestHeaders

export interface InternalUiReadResultantAclOperation<STATUS extends keyof InternalUiReadResultantAclResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: InternalUiReadResultantAclRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: InternalUiReadResultantAclRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: InternalUiReadResultantAclRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: InternalUiReadResultantAclResponseBodies[STATUS]
}

/* @anchor:file:end */
