// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface InternalInspectRequestResponseBodies {
  200: void
}

export interface InternalInspectRequestRequestBodies {}

export type InternalInspectRequestRequestQuery = {}

export type InternalInspectRequestRouteParameters = {}

export type InternalInspectRequestRequestHeaders = {}

export type InternalInspectRequestRequestParameters = InternalInspectRequestRequestQuery & InternalInspectRequestRouteParameters & InternalInspectRequestRequestHeaders

export interface InternalInspectRequestOperation<STATUS extends keyof InternalInspectRequestResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: InternalInspectRequestRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: InternalInspectRequestRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: InternalInspectRequestRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: InternalInspectRequestResponseBodies[STATUS]
}

/* @anchor:file:end */
