// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface InternalInspectRouterResponseBodies {
  200: void
}

export interface InternalInspectRouterRequestBodies {}

export type InternalInspectRouterRequestQuery = {}

export type InternalInspectRouterRouteParameters = {}

export type InternalInspectRouterRequestHeaders = {}

export type InternalInspectRouterRequestParameters = InternalInspectRouterRequestQuery & InternalInspectRouterRouteParameters & InternalInspectRouterRequestHeaders

export interface InternalInspectRouterOperation<STATUS extends keyof InternalInspectRouterResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: InternalInspectRouterRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: InternalInspectRouterRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: InternalInspectRouterRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: InternalInspectRouterResponseBodies[STATUS]
}

/* @anchor:file:end */
