// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface KubernetesReadAuthConfigurationResponseBodies {
  200: void
}

export interface KubernetesReadAuthConfigurationRequestBodies {}

export type KubernetesReadAuthConfigurationRequestQuery = {}

export type KubernetesReadAuthConfigurationRouteParameters = {}

export type KubernetesReadAuthConfigurationRequestHeaders = {}

export type KubernetesReadAuthConfigurationRequestParameters = KubernetesReadAuthConfigurationRequestQuery & KubernetesReadAuthConfigurationRouteParameters & KubernetesReadAuthConfigurationRequestHeaders

export interface KubernetesReadAuthConfigurationOperation<STATUS extends keyof KubernetesReadAuthConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: KubernetesReadAuthConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KubernetesReadAuthConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KubernetesReadAuthConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: KubernetesReadAuthConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
