// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { KubernetesWriteAuthRoleRequest as KubernetesWriteAuthRoleRequestSchema } from '../components/schemas/kubernetes-write-auth-role-request.schema'

export interface KubernetesWriteAuthRoleResponseBodies {
  200: void
}

export interface KubernetesWriteAuthRoleRequestBodies {
  'application/json': KubernetesWriteAuthRoleRequestSchema
}

export type KubernetesWriteAuthRoleRequestQuery = {}

export type KubernetesWriteAuthRoleRouteParameters = {}

export type KubernetesWriteAuthRoleRequestHeaders = {}

interface KubernetesWriteAuthRoleParameterBodies {
  'application/json': KubernetesWriteAuthRoleRequestSchema & { [key: string]: any }
}

export type KubernetesWriteAuthRoleRequestParameters = KubernetesWriteAuthRoleRequestQuery & KubernetesWriteAuthRoleRouteParameters & KubernetesWriteAuthRoleRequestHeaders & KubernetesWriteAuthRoleRequestBodies['application/json']

export interface KubernetesWriteAuthRoleOperation<STATUS extends keyof KubernetesWriteAuthRoleResponseBodies, CONTENT_TYPE extends keyof KubernetesWriteAuthRoleParameterBodies> extends KeqOperation {
  requestParams: KubernetesWriteAuthRoleRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KubernetesWriteAuthRoleRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KubernetesWriteAuthRoleRequestHeaders & { [key: string]: string | number }
  requestBody: KubernetesWriteAuthRoleParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: KubernetesWriteAuthRoleResponseBodies[STATUS]
}

/* @anchor:file:end */
