// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface KubernetesListAuthRolesResponseBodies {
  200: void
}

export interface KubernetesListAuthRolesRequestBodies {}

export type KubernetesListAuthRolesRequestQuery = {
  list: ('true')
}

export type KubernetesListAuthRolesRouteParameters = {}

export type KubernetesListAuthRolesRequestHeaders = {}

export type KubernetesListAuthRolesRequestParameters = KubernetesListAuthRolesRequestQuery & KubernetesListAuthRolesRouteParameters & KubernetesListAuthRolesRequestHeaders

export interface KubernetesListAuthRolesOperation<STATUS extends keyof KubernetesListAuthRolesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: KubernetesListAuthRolesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KubernetesListAuthRolesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KubernetesListAuthRolesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: KubernetesListAuthRolesResponseBodies[STATUS]
}

/* @anchor:file:end */
