// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface KubernetesDeleteAuthRoleResponseBodies {
  204: void
}

export interface KubernetesDeleteAuthRoleRequestBodies {}

export type KubernetesDeleteAuthRoleRequestQuery = {}

export type KubernetesDeleteAuthRoleRouteParameters = {}

export type KubernetesDeleteAuthRoleRequestHeaders = {}

export type KubernetesDeleteAuthRoleRequestParameters = KubernetesDeleteAuthRoleRequestQuery & KubernetesDeleteAuthRoleRouteParameters & KubernetesDeleteAuthRoleRequestHeaders

export interface KubernetesDeleteAuthRoleOperation<STATUS extends keyof KubernetesDeleteAuthRoleResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: KubernetesDeleteAuthRoleRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KubernetesDeleteAuthRoleRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KubernetesDeleteAuthRoleRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: KubernetesDeleteAuthRoleResponseBodies[STATUS]
}

/* @anchor:file:end */
