// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { KubernetesConfigureAuthRequest as KubernetesConfigureAuthRequestSchema } from '../components/schemas/kubernetes-configure-auth-request.schema'

export interface KubernetesConfigureAuthResponseBodies {
  200: void
}

export interface KubernetesConfigureAuthRequestBodies {
  'application/json': KubernetesConfigureAuthRequestSchema
}

export type KubernetesConfigureAuthRequestQuery = {}

export type KubernetesConfigureAuthRouteParameters = {}

export type KubernetesConfigureAuthRequestHeaders = {}

interface KubernetesConfigureAuthParameterBodies {
  'application/json': KubernetesConfigureAuthRequestSchema & { [key: string]: any }
}

export type KubernetesConfigureAuthRequestParameters = KubernetesConfigureAuthRequestQuery & KubernetesConfigureAuthRouteParameters & KubernetesConfigureAuthRequestHeaders & KubernetesConfigureAuthRequestBodies['application/json']

export interface KubernetesConfigureAuthOperation<STATUS extends keyof KubernetesConfigureAuthResponseBodies, CONTENT_TYPE extends keyof KubernetesConfigureAuthParameterBodies> extends KeqOperation {
  requestParams: KubernetesConfigureAuthRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KubernetesConfigureAuthRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KubernetesConfigureAuthRequestHeaders & { [key: string]: string | number }
  requestBody: KubernetesConfigureAuthParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: KubernetesConfigureAuthResponseBodies[STATUS]
}

/* @anchor:file:end */
