// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface KvListDetailedMetadataPathResponseBodies {
  200: void
}

export interface KvListDetailedMetadataPathRequestBodies {}

export type KvListDetailedMetadataPathRequestQuery = {
  list: ('true')
}

export type KvListDetailedMetadataPathRouteParameters = {}

export type KvListDetailedMetadataPathRequestHeaders = {}

export type KvListDetailedMetadataPathRequestParameters = KvListDetailedMetadataPathRequestQuery & KvListDetailedMetadataPathRouteParameters & KvListDetailedMetadataPathRequestHeaders

export interface KvListDetailedMetadataPathOperation<STATUS extends keyof KvListDetailedMetadataPathResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: KvListDetailedMetadataPathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KvListDetailedMetadataPathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KvListDetailedMetadataPathRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: KvListDetailedMetadataPathResponseBodies[STATUS]
}

/* @anchor:file:end */
