// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface KvReadMetadataPathResponseBodies {
  200: void
}

export interface KvReadMetadataPathRequestBodies {}

export type KvReadMetadataPathRequestQuery = {
  list?: string
}

export type KvReadMetadataPathRouteParameters = {}

export type KvReadMetadataPathRequestHeaders = {}

export type KvReadMetadataPathRequestParameters = KvReadMetadataPathRequestQuery & KvReadMetadataPathRouteParameters & KvReadMetadataPathRequestHeaders

export interface KvReadMetadataPathOperation<STATUS extends keyof KvReadMetadataPathResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: KvReadMetadataPathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KvReadMetadataPathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KvReadMetadataPathRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: KvReadMetadataPathResponseBodies[STATUS]
}

/* @anchor:file:end */
