// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface KvReadConfigResponseBodies {
  200: void
}

export interface KvReadConfigRequestBodies {}

export type KvReadConfigRequestQuery = {}

export type KvReadConfigRouteParameters = {}

export type KvReadConfigRequestHeaders = {}

export type KvReadConfigRequestParameters = KvReadConfigRequestQuery & KvReadConfigRouteParameters & KvReadConfigRequestHeaders

export interface KvReadConfigOperation<STATUS extends keyof KvReadConfigResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: KvReadConfigRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KvReadConfigRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KvReadConfigRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: KvReadConfigResponseBodies[STATUS]
}

/* @anchor:file:end */
