// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface KvReadDataPathResponseBodies {
  200: void
}

export interface KvReadDataPathRequestBodies {}

export type KvReadDataPathRequestQuery = {}

export type KvReadDataPathRouteParameters = {}

export type KvReadDataPathRequestHeaders = {}

export type KvReadDataPathRequestParameters = KvReadDataPathRequestQuery & KvReadDataPathRouteParameters & KvReadDataPathRequestHeaders

export interface KvReadDataPathOperation<STATUS extends keyof KvReadDataPathResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: KvReadDataPathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KvReadDataPathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KvReadDataPathRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: KvReadDataPathResponseBodies[STATUS]
}

/* @anchor:file:end */
