// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { KvWriteMetadataPathRequest as KvWriteMetadataPathRequestSchema } from '../components/schemas/kv-write-metadata-path-request.schema'

export interface KvWriteMetadataPathResponseBodies {
  200: void
}

export interface KvWriteMetadataPathRequestBodies {
  'application/json': KvWriteMetadataPathRequestSchema
}

export type KvWriteMetadataPathRequestQuery = {}

export type KvWriteMetadataPathRouteParameters = {}

export type KvWriteMetadataPathRequestHeaders = {}

interface KvWriteMetadataPathParameterBodies {
  'application/json': KvWriteMetadataPathRequestSchema & { [key: string]: any }
}

export type KvWriteMetadataPathRequestParameters = KvWriteMetadataPathRequestQuery & KvWriteMetadataPathRouteParameters & KvWriteMetadataPathRequestHeaders & KvWriteMetadataPathRequestBodies['application/json']

export interface KvWriteMetadataPathOperation<STATUS extends keyof KvWriteMetadataPathResponseBodies, CONTENT_TYPE extends keyof KvWriteMetadataPathParameterBodies> extends KeqOperation {
  requestParams: KvWriteMetadataPathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KvWriteMetadataPathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KvWriteMetadataPathRequestHeaders & { [key: string]: string | number }
  requestBody: KvWriteMetadataPathParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: KvWriteMetadataPathResponseBodies[STATUS]
}

/* @anchor:file:end */
