// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { KvWriteDataPathRequest as KvWriteDataPathRequestSchema } from '../components/schemas/kv-write-data-path-request.schema'

export interface KvWriteDataPathResponseBodies {
  200: void
}

export interface KvWriteDataPathRequestBodies {
  'application/json': KvWriteDataPathRequestSchema
}

export type KvWriteDataPathRequestQuery = {}

export type KvWriteDataPathRouteParameters = {}

export type KvWriteDataPathRequestHeaders = {}

interface KvWriteDataPathParameterBodies {
  'application/json': KvWriteDataPathRequestSchema & { [key: string]: any }
}

export type KvWriteDataPathRequestParameters = KvWriteDataPathRequestQuery & KvWriteDataPathRouteParameters & KvWriteDataPathRequestHeaders & KvWriteDataPathRequestBodies['application/json']

export interface KvWriteDataPathOperation<STATUS extends keyof KvWriteDataPathResponseBodies, CONTENT_TYPE extends keyof KvWriteDataPathParameterBodies> extends KeqOperation {
  requestParams: KvWriteDataPathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KvWriteDataPathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KvWriteDataPathRequestHeaders & { [key: string]: string | number }
  requestBody: KvWriteDataPathParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: KvWriteDataPathResponseBodies[STATUS]
}

/* @anchor:file:end */
