// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { KvWriteUndeletePathRequest as KvWriteUndeletePathRequestSchema } from '../components/schemas/kv-write-undelete-path-request.schema'

export interface KvWriteUndeletePathResponseBodies {
  200: void
}

export interface KvWriteUndeletePathRequestBodies {
  'application/json': KvWriteUndeletePathRequestSchema
}

export type KvWriteUndeletePathRequestQuery = {}

export type KvWriteUndeletePathRouteParameters = {}

export type KvWriteUndeletePathRequestHeaders = {}

interface KvWriteUndeletePathParameterBodies {
  'application/json': KvWriteUndeletePathRequestSchema & { [key: string]: any }
}

export type KvWriteUndeletePathRequestParameters = KvWriteUndeletePathRequestQuery & KvWriteUndeletePathRouteParameters & KvWriteUndeletePathRequestHeaders & KvWriteUndeletePathRequestBodies['application/json']

export interface KvWriteUndeletePathOperation<STATUS extends keyof KvWriteUndeletePathResponseBodies, CONTENT_TYPE extends keyof KvWriteUndeletePathParameterBodies> extends KeqOperation {
  requestParams: KvWriteUndeletePathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: KvWriteUndeletePathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: KvWriteUndeletePathRequestHeaders & { [key: string]: string | number }
  requestBody: KvWriteUndeletePathParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: KvWriteUndeletePathResponseBodies[STATUS]
}

/* @anchor:file:end */
