// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeaderStatusResponse as LeaderStatusResponseSchema } from '../components/schemas/leader-status-response.schema'

export interface LeaderStatusResponseBodies {
  200: LeaderStatusResponseSchema
}

export interface LeaderStatusRequestBodies {}

export type LeaderStatusRequestQuery = {}

export type LeaderStatusRouteParameters = {}

export type LeaderStatusRequestHeaders = {}

export type LeaderStatusRequestParameters = LeaderStatusRequestQuery & LeaderStatusRouteParameters & LeaderStatusRequestHeaders

export interface LeaderStatusOperation<STATUS extends keyof LeaderStatusResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LeaderStatusRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeaderStatusRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeaderStatusRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LeaderStatusResponseBodies[STATUS]
}

/* @anchor:file:end */
