// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface LeasesTidyResponseBodies {
  204: void
}

export interface LeasesTidyRequestBodies {}

export type LeasesTidyRequestQuery = {}

export type LeasesTidyRouteParameters = {}

export type LeasesTidyRequestHeaders = {}

export type LeasesTidyRequestParameters = LeasesTidyRequestQuery & LeasesTidyRouteParameters & LeasesTidyRequestHeaders

export interface LeasesTidyOperation<STATUS extends keyof LeasesTidyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LeasesTidyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesTidyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesTidyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LeasesTidyResponseBodies[STATUS]
}

/* @anchor:file:end */
