// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesRevokeLease2Request as LeasesRevokeLease2RequestSchema } from '../components/schemas/leases-revoke-lease2-request.schema'

export interface LeasesRevokeLease2ResponseBodies {
  204: void
}

export interface LeasesRevokeLease2RequestBodies {
  'application/json': LeasesRevokeLease2RequestSchema
}

export type LeasesRevokeLease2RequestQuery = {}

export type LeasesRevokeLease2RouteParameters = {}

export type LeasesRevokeLease2RequestHeaders = {}

interface LeasesRevokeLease2ParameterBodies {
  'application/json': LeasesRevokeLease2RequestSchema & { [key: string]: any }
}

export type LeasesRevokeLease2RequestParameters = LeasesRevokeLease2RequestQuery & LeasesRevokeLease2RouteParameters & LeasesRevokeLease2RequestHeaders & LeasesRevokeLease2RequestBodies['application/json']

export interface LeasesRevokeLease2Operation<STATUS extends keyof LeasesRevokeLease2ResponseBodies, CONTENT_TYPE extends keyof LeasesRevokeLease2ParameterBodies> extends KeqOperation {
  requestParams: LeasesRevokeLease2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesRevokeLease2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesRevokeLease2RequestHeaders & { [key: string]: string | number }
  requestBody: LeasesRevokeLease2ParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: LeasesRevokeLease2ResponseBodies[STATUS]
}

/* @anchor:file:end */
