// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesLookUpResponse as LeasesLookUpResponseSchema } from '../components/schemas/leases-look-up-response.schema'

export interface LeasesLookUpResponseBodies {
  200: LeasesLookUpResponseSchema
}

export interface LeasesLookUpRequestBodies {}

export type LeasesLookUpRequestQuery = {
  list: ('true')
}

export type LeasesLookUpRouteParameters = {}

export type LeasesLookUpRequestHeaders = {}

export type LeasesLookUpRequestParameters = LeasesLookUpRequestQuery & LeasesLookUpRouteParameters & LeasesLookUpRequestHeaders

export interface LeasesLookUpOperation<STATUS extends keyof LeasesLookUpResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LeasesLookUpRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesLookUpRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesLookUpRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LeasesLookUpResponseBodies[STATUS]
}

/* @anchor:file:end */
