// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface LeasesForceRevokeLeaseWithPrefix2ResponseBodies {
  204: void
}

export interface LeasesForceRevokeLeaseWithPrefix2RequestBodies {}

export type LeasesForceRevokeLeaseWithPrefix2RequestQuery = {}

export type LeasesForceRevokeLeaseWithPrefix2RouteParameters = {}

export type LeasesForceRevokeLeaseWithPrefix2RequestHeaders = {}

export type LeasesForceRevokeLeaseWithPrefix2RequestParameters = LeasesForceRevokeLeaseWithPrefix2RequestQuery & LeasesForceRevokeLeaseWithPrefix2RouteParameters & LeasesForceRevokeLeaseWithPrefix2RequestHeaders

export interface LeasesForceRevokeLeaseWithPrefix2Operation<STATUS extends keyof LeasesForceRevokeLeaseWithPrefix2ResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LeasesForceRevokeLeaseWithPrefix2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesForceRevokeLeaseWithPrefix2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesForceRevokeLeaseWithPrefix2RequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LeasesForceRevokeLeaseWithPrefix2ResponseBodies[STATUS]
}

/* @anchor:file:end */
