// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesRevokeLeaseWithPrefix2Request as LeasesRevokeLeaseWithPrefix2RequestSchema } from '../components/schemas/leases-revoke-lease-with-prefix2-request.schema'

export interface LeasesRevokeLeaseWithPrefix2ResponseBodies {
  204: void
}

export interface LeasesRevokeLeaseWithPrefix2RequestBodies {
  'application/json': LeasesRevokeLeaseWithPrefix2RequestSchema
}

export type LeasesRevokeLeaseWithPrefix2RequestQuery = {}

export type LeasesRevokeLeaseWithPrefix2RouteParameters = {}

export type LeasesRevokeLeaseWithPrefix2RequestHeaders = {}

interface LeasesRevokeLeaseWithPrefix2ParameterBodies {
  'application/json': LeasesRevokeLeaseWithPrefix2RequestSchema & { [key: string]: any }
}

export type LeasesRevokeLeaseWithPrefix2RequestParameters = LeasesRevokeLeaseWithPrefix2RequestQuery & LeasesRevokeLeaseWithPrefix2RouteParameters & LeasesRevokeLeaseWithPrefix2RequestHeaders & LeasesRevokeLeaseWithPrefix2RequestBodies['application/json']

export interface LeasesRevokeLeaseWithPrefix2Operation<STATUS extends keyof LeasesRevokeLeaseWithPrefix2ResponseBodies, CONTENT_TYPE extends keyof LeasesRevokeLeaseWithPrefix2ParameterBodies> extends KeqOperation {
  requestParams: LeasesRevokeLeaseWithPrefix2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesRevokeLeaseWithPrefix2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesRevokeLeaseWithPrefix2RequestHeaders & { [key: string]: string | number }
  requestBody: LeasesRevokeLeaseWithPrefix2ParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: LeasesRevokeLeaseWithPrefix2ResponseBodies[STATUS]
}

/* @anchor:file:end */
