// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesRevokeLeaseRequest as LeasesRevokeLeaseRequestSchema } from '../components/schemas/leases-revoke-lease-request.schema'

export interface LeasesRevokeLeaseResponseBodies {
  204: void
}

export interface LeasesRevokeLeaseRequestBodies {
  'application/json': LeasesRevokeLeaseRequestSchema
}

export type LeasesRevokeLeaseRequestQuery = {}

export type LeasesRevokeLeaseRouteParameters = {}

export type LeasesRevokeLeaseRequestHeaders = {}

interface LeasesRevokeLeaseParameterBodies {
  'application/json': LeasesRevokeLeaseRequestSchema & { [key: string]: any }
}

export type LeasesRevokeLeaseRequestParameters = LeasesRevokeLeaseRequestQuery & LeasesRevokeLeaseRouteParameters & LeasesRevokeLeaseRequestHeaders & LeasesRevokeLeaseRequestBodies['application/json']

export interface LeasesRevokeLeaseOperation<STATUS extends keyof LeasesRevokeLeaseResponseBodies, CONTENT_TYPE extends keyof LeasesRevokeLeaseParameterBodies> extends KeqOperation {
  requestParams: LeasesRevokeLeaseRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesRevokeLeaseRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesRevokeLeaseRequestHeaders & { [key: string]: string | number }
  requestBody: LeasesRevokeLeaseParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: LeasesRevokeLeaseResponseBodies[STATUS]
}

/* @anchor:file:end */
