// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesCountResponse as LeasesCountResponseSchema } from '../components/schemas/leases-count-response.schema'

export interface LeasesCountResponseBodies {
  200: LeasesCountResponseSchema
}

export interface LeasesCountRequestBodies {}

export type LeasesCountRequestQuery = {}

export type LeasesCountRouteParameters = {}

export type LeasesCountRequestHeaders = {}

export type LeasesCountRequestParameters = LeasesCountRequestQuery & LeasesCountRouteParameters & LeasesCountRequestHeaders

export interface LeasesCountOperation<STATUS extends keyof LeasesCountResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LeasesCountRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesCountRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesCountRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LeasesCountResponseBodies[STATUS]
}

/* @anchor:file:end */
