// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesRevokeLeaseWithId2Request as LeasesRevokeLeaseWithId2RequestSchema } from '../components/schemas/leases-revoke-lease-with-id2-request.schema'

export interface LeasesRevokeLeaseWithId2ResponseBodies {
  204: void
}

export interface LeasesRevokeLeaseWithId2RequestBodies {
  'application/json': LeasesRevokeLeaseWithId2RequestSchema
}

export type LeasesRevokeLeaseWithId2RequestQuery = {}

export type LeasesRevokeLeaseWithId2RouteParameters = {}

export type LeasesRevokeLeaseWithId2RequestHeaders = {}

interface LeasesRevokeLeaseWithId2ParameterBodies {
  'application/json': LeasesRevokeLeaseWithId2RequestSchema & { [key: string]: any }
}

export type LeasesRevokeLeaseWithId2RequestParameters = LeasesRevokeLeaseWithId2RequestQuery & LeasesRevokeLeaseWithId2RouteParameters & LeasesRevokeLeaseWithId2RequestHeaders & LeasesRevokeLeaseWithId2RequestBodies['application/json']

export interface LeasesRevokeLeaseWithId2Operation<STATUS extends keyof LeasesRevokeLeaseWithId2ResponseBodies, CONTENT_TYPE extends keyof LeasesRevokeLeaseWithId2ParameterBodies> extends KeqOperation {
  requestParams: LeasesRevokeLeaseWithId2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesRevokeLeaseWithId2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesRevokeLeaseWithId2RequestHeaders & { [key: string]: string | number }
  requestBody: LeasesRevokeLeaseWithId2ParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: LeasesRevokeLeaseWithId2ResponseBodies[STATUS]
}

/* @anchor:file:end */
