// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesRevokeLeaseWithPrefixRequest as LeasesRevokeLeaseWithPrefixRequestSchema } from '../components/schemas/leases-revoke-lease-with-prefix-request.schema'

export interface LeasesRevokeLeaseWithPrefixResponseBodies {
  204: void
}

export interface LeasesRevokeLeaseWithPrefixRequestBodies {
  'application/json': LeasesRevokeLeaseWithPrefixRequestSchema
}

export type LeasesRevokeLeaseWithPrefixRequestQuery = {}

export type LeasesRevokeLeaseWithPrefixRouteParameters = {}

export type LeasesRevokeLeaseWithPrefixRequestHeaders = {}

interface LeasesRevokeLeaseWithPrefixParameterBodies {
  'application/json': LeasesRevokeLeaseWithPrefixRequestSchema & { [key: string]: any }
}

export type LeasesRevokeLeaseWithPrefixRequestParameters = LeasesRevokeLeaseWithPrefixRequestQuery & LeasesRevokeLeaseWithPrefixRouteParameters & LeasesRevokeLeaseWithPrefixRequestHeaders & LeasesRevokeLeaseWithPrefixRequestBodies['application/json']

export interface LeasesRevokeLeaseWithPrefixOperation<STATUS extends keyof LeasesRevokeLeaseWithPrefixResponseBodies, CONTENT_TYPE extends keyof LeasesRevokeLeaseWithPrefixParameterBodies> extends KeqOperation {
  requestParams: LeasesRevokeLeaseWithPrefixRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesRevokeLeaseWithPrefixRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesRevokeLeaseWithPrefixRequestHeaders & { [key: string]: string | number }
  requestBody: LeasesRevokeLeaseWithPrefixParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: LeasesRevokeLeaseWithPrefixResponseBodies[STATUS]
}

/* @anchor:file:end */
