// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesRenewLeaseWithIdRequest as LeasesRenewLeaseWithIdRequestSchema } from '../components/schemas/leases-renew-lease-with-id-request.schema'

export interface LeasesRenewLeaseWithIdResponseBodies {
  204: void
}

export interface LeasesRenewLeaseWithIdRequestBodies {
  'application/json': LeasesRenewLeaseWithIdRequestSchema
}

export type LeasesRenewLeaseWithIdRequestQuery = {}

export type LeasesRenewLeaseWithIdRouteParameters = {}

export type LeasesRenewLeaseWithIdRequestHeaders = {}

interface LeasesRenewLeaseWithIdParameterBodies {
  'application/json': LeasesRenewLeaseWithIdRequestSchema & { [key: string]: any }
}

export type LeasesRenewLeaseWithIdRequestParameters = LeasesRenewLeaseWithIdRequestQuery & LeasesRenewLeaseWithIdRouteParameters & LeasesRenewLeaseWithIdRequestHeaders & LeasesRenewLeaseWithIdRequestBodies['application/json']

export interface LeasesRenewLeaseWithIdOperation<STATUS extends keyof LeasesRenewLeaseWithIdResponseBodies, CONTENT_TYPE extends keyof LeasesRenewLeaseWithIdParameterBodies> extends KeqOperation {
  requestParams: LeasesRenewLeaseWithIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesRenewLeaseWithIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesRenewLeaseWithIdRequestHeaders & { [key: string]: string | number }
  requestBody: LeasesRenewLeaseWithIdParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: LeasesRenewLeaseWithIdResponseBodies[STATUS]
}

/* @anchor:file:end */
