// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesLookUpWithPrefixResponse as LeasesLookUpWithPrefixResponseSchema } from '../components/schemas/leases-look-up-with-prefix-response.schema'

export interface LeasesLookUpWithPrefixResponseBodies {
  200: LeasesLookUpWithPrefixResponseSchema
}

export interface LeasesLookUpWithPrefixRequestBodies {}

export type LeasesLookUpWithPrefixRequestQuery = {
  list: ('true')
}

export type LeasesLookUpWithPrefixRouteParameters = {}

export type LeasesLookUpWithPrefixRequestHeaders = {}

export type LeasesLookUpWithPrefixRequestParameters = LeasesLookUpWithPrefixRequestQuery & LeasesLookUpWithPrefixRouteParameters & LeasesLookUpWithPrefixRequestHeaders

export interface LeasesLookUpWithPrefixOperation<STATUS extends keyof LeasesLookUpWithPrefixResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LeasesLookUpWithPrefixRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesLookUpWithPrefixRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesLookUpWithPrefixRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LeasesLookUpWithPrefixResponseBodies[STATUS]
}

/* @anchor:file:end */
