// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LeasesReadLeaseRequest as LeasesReadLeaseRequestSchema } from '../components/schemas/leases-read-lease-request.schema'
import type { LeasesReadLeaseResponse as LeasesReadLeaseResponseSchema } from '../components/schemas/leases-read-lease-response.schema'

export interface LeasesReadLeaseResponseBodies {
  200: LeasesReadLeaseResponseSchema
}

export interface LeasesReadLeaseRequestBodies {
  'application/json': LeasesReadLeaseRequestSchema
}

export type LeasesReadLeaseRequestQuery = {}

export type LeasesReadLeaseRouteParameters = {}

export type LeasesReadLeaseRequestHeaders = {}

interface LeasesReadLeaseParameterBodies {
  'application/json': LeasesReadLeaseRequestSchema & { [key: string]: any }
}

export type LeasesReadLeaseRequestParameters = LeasesReadLeaseRequestQuery & LeasesReadLeaseRouteParameters & LeasesReadLeaseRequestHeaders & LeasesReadLeaseRequestBodies['application/json']

export interface LeasesReadLeaseOperation<STATUS extends keyof LeasesReadLeaseResponseBodies, CONTENT_TYPE extends keyof LeasesReadLeaseParameterBodies> extends KeqOperation {
  requestParams: LeasesReadLeaseRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesReadLeaseRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesReadLeaseRequestHeaders & { [key: string]: string | number }
  requestBody: LeasesReadLeaseParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: LeasesReadLeaseResponseBodies[STATUS]
}

/* @anchor:file:end */
