// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface LeasesForceRevokeLeaseWithPrefixResponseBodies {
  204: void
}

export interface LeasesForceRevokeLeaseWithPrefixRequestBodies {}

export type LeasesForceRevokeLeaseWithPrefixRequestQuery = {}

export type LeasesForceRevokeLeaseWithPrefixRouteParameters = {}

export type LeasesForceRevokeLeaseWithPrefixRequestHeaders = {}

export type LeasesForceRevokeLeaseWithPrefixRequestParameters = LeasesForceRevokeLeaseWithPrefixRequestQuery & LeasesForceRevokeLeaseWithPrefixRouteParameters & LeasesForceRevokeLeaseWithPrefixRequestHeaders

export interface LeasesForceRevokeLeaseWithPrefixOperation<STATUS extends keyof LeasesForceRevokeLeaseWithPrefixResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LeasesForceRevokeLeaseWithPrefixRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LeasesForceRevokeLeaseWithPrefixRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LeasesForceRevokeLeaseWithPrefixRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LeasesForceRevokeLeaseWithPrefixResponseBodies[STATUS]
}

/* @anchor:file:end */
