// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface LockedUsersUnlockResponseBodies {
  200: void
}

export interface LockedUsersUnlockRequestBodies {}

export type LockedUsersUnlockRequestQuery = {}

export type LockedUsersUnlockRouteParameters = {}

export type LockedUsersUnlockRequestHeaders = {}

export type LockedUsersUnlockRequestParameters = LockedUsersUnlockRequestQuery & LockedUsersUnlockRouteParameters & LockedUsersUnlockRequestHeaders

export interface LockedUsersUnlockOperation<STATUS extends keyof LockedUsersUnlockResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LockedUsersUnlockRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LockedUsersUnlockRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LockedUsersUnlockRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LockedUsersUnlockResponseBodies[STATUS]
}

/* @anchor:file:end */
