// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface LoggersReadVerbosityLevelResponseBodies {
  200: void
}

export interface LoggersReadVerbosityLevelRequestBodies {}

export type LoggersReadVerbosityLevelRequestQuery = {}

export type LoggersReadVerbosityLevelRouteParameters = {}

export type LoggersReadVerbosityLevelRequestHeaders = {}

export type LoggersReadVerbosityLevelRequestParameters = LoggersReadVerbosityLevelRequestQuery & LoggersReadVerbosityLevelRouteParameters & LoggersReadVerbosityLevelRequestHeaders

export interface LoggersReadVerbosityLevelOperation<STATUS extends keyof LoggersReadVerbosityLevelResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: LoggersReadVerbosityLevelRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LoggersReadVerbosityLevelRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LoggersReadVerbosityLevelRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: LoggersReadVerbosityLevelResponseBodies[STATUS]
}

/* @anchor:file:end */
