// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { LoggersUpdateVerbosityLevelForRequest as LoggersUpdateVerbosityLevelForRequestSchema } from '../components/schemas/loggers-update-verbosity-level-for-request.schema'

export interface LoggersUpdateVerbosityLevelForResponseBodies {
  204: void
}

export interface LoggersUpdateVerbosityLevelForRequestBodies {
  'application/json': LoggersUpdateVerbosityLevelForRequestSchema
}

export type LoggersUpdateVerbosityLevelForRequestQuery = {}

export type LoggersUpdateVerbosityLevelForRouteParameters = {}

export type LoggersUpdateVerbosityLevelForRequestHeaders = {}

interface LoggersUpdateVerbosityLevelForParameterBodies {
  'application/json': LoggersUpdateVerbosityLevelForRequestSchema & { [key: string]: any }
}

export type LoggersUpdateVerbosityLevelForRequestParameters = LoggersUpdateVerbosityLevelForRequestQuery & LoggersUpdateVerbosityLevelForRouteParameters & LoggersUpdateVerbosityLevelForRequestHeaders & LoggersUpdateVerbosityLevelForRequestBodies['application/json']

export interface LoggersUpdateVerbosityLevelForOperation<STATUS extends keyof LoggersUpdateVerbosityLevelForResponseBodies, CONTENT_TYPE extends keyof LoggersUpdateVerbosityLevelForParameterBodies> extends KeqOperation {
  requestParams: LoggersUpdateVerbosityLevelForRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: LoggersUpdateVerbosityLevelForRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: LoggersUpdateVerbosityLevelForRequestHeaders & { [key: string]: string | number }
  requestBody: LoggersUpdateVerbosityLevelForParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: LoggersUpdateVerbosityLevelForResponseBodies[STATUS]
}

/* @anchor:file:end */
