// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MetricsResponseBodies {
  200: void
}

export interface MetricsRequestBodies {}

export type MetricsRequestQuery = {}

export type MetricsRouteParameters = {}

export type MetricsRequestHeaders = {}

export type MetricsRequestParameters = MetricsRequestQuery & MetricsRouteParameters & MetricsRequestHeaders

export interface MetricsOperation<STATUS extends keyof MetricsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MetricsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MetricsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MetricsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MetricsResponseBodies[STATUS]
}

/* @anchor:file:end */
