// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaDeleteTotpMethodResponseBodies {
  204: void
}

export interface MfaDeleteTotpMethodRequestBodies {}

export type MfaDeleteTotpMethodRequestQuery = {}

export type MfaDeleteTotpMethodRouteParameters = {}

export type MfaDeleteTotpMethodRequestHeaders = {}

export type MfaDeleteTotpMethodRequestParameters = MfaDeleteTotpMethodRequestQuery & MfaDeleteTotpMethodRouteParameters & MfaDeleteTotpMethodRequestHeaders

export interface MfaDeleteTotpMethodOperation<STATUS extends keyof MfaDeleteTotpMethodResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaDeleteTotpMethodRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaDeleteTotpMethodRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaDeleteTotpMethodRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaDeleteTotpMethodResponseBodies[STATUS]
}

/* @anchor:file:end */
