// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaDeleteDuoMethodResponseBodies {
  204: void
}

export interface MfaDeleteDuoMethodRequestBodies {}

export type MfaDeleteDuoMethodRequestQuery = {}

export type MfaDeleteDuoMethodRouteParameters = {}

export type MfaDeleteDuoMethodRequestHeaders = {}

export type MfaDeleteDuoMethodRequestParameters = MfaDeleteDuoMethodRequestQuery & MfaDeleteDuoMethodRouteParameters & MfaDeleteDuoMethodRequestHeaders

export interface MfaDeleteDuoMethodOperation<STATUS extends keyof MfaDeleteDuoMethodResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaDeleteDuoMethodRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaDeleteDuoMethodRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaDeleteDuoMethodRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaDeleteDuoMethodResponseBodies[STATUS]
}

/* @anchor:file:end */
