// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { MfaConfigureTotpMethodRequest as MfaConfigureTotpMethodRequestSchema } from '../components/schemas/mfa-configure-totp-method-request.schema'

export interface MfaConfigureTotpMethodResponseBodies {
  200: void
}

export interface MfaConfigureTotpMethodRequestBodies {
  'application/json': MfaConfigureTotpMethodRequestSchema
}

export type MfaConfigureTotpMethodRequestQuery = {}

export type MfaConfigureTotpMethodRouteParameters = {}

export type MfaConfigureTotpMethodRequestHeaders = {}

interface MfaConfigureTotpMethodParameterBodies {
  'application/json': MfaConfigureTotpMethodRequestSchema & { [key: string]: any }
}

export type MfaConfigureTotpMethodRequestParameters = MfaConfigureTotpMethodRequestQuery & MfaConfigureTotpMethodRouteParameters & MfaConfigureTotpMethodRequestHeaders & MfaConfigureTotpMethodRequestBodies['application/json']

export interface MfaConfigureTotpMethodOperation<STATUS extends keyof MfaConfigureTotpMethodResponseBodies, CONTENT_TYPE extends keyof MfaConfigureTotpMethodParameterBodies> extends KeqOperation {
  requestParams: MfaConfigureTotpMethodRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaConfigureTotpMethodRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaConfigureTotpMethodRequestHeaders & { [key: string]: string | number }
  requestBody: MfaConfigureTotpMethodParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: MfaConfigureTotpMethodResponseBodies[STATUS]
}

/* @anchor:file:end */
