// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { MfaConfigureOktaMethodRequest as MfaConfigureOktaMethodRequestSchema } from '../components/schemas/mfa-configure-okta-method-request.schema'

export interface MfaConfigureOktaMethodResponseBodies {
  200: void
}

export interface MfaConfigureOktaMethodRequestBodies {
  'application/json': MfaConfigureOktaMethodRequestSchema
}

export type MfaConfigureOktaMethodRequestQuery = {}

export type MfaConfigureOktaMethodRouteParameters = {}

export type MfaConfigureOktaMethodRequestHeaders = {}

interface MfaConfigureOktaMethodParameterBodies {
  'application/json': MfaConfigureOktaMethodRequestSchema & { [key: string]: any }
}

export type MfaConfigureOktaMethodRequestParameters = MfaConfigureOktaMethodRequestQuery & MfaConfigureOktaMethodRouteParameters & MfaConfigureOktaMethodRequestHeaders & MfaConfigureOktaMethodRequestBodies['application/json']

export interface MfaConfigureOktaMethodOperation<STATUS extends keyof MfaConfigureOktaMethodResponseBodies, CONTENT_TYPE extends keyof MfaConfigureOktaMethodParameterBodies> extends KeqOperation {
  requestParams: MfaConfigureOktaMethodRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaConfigureOktaMethodRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaConfigureOktaMethodRequestHeaders & { [key: string]: string | number }
  requestBody: MfaConfigureOktaMethodParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: MfaConfigureOktaMethodResponseBodies[STATUS]
}

/* @anchor:file:end */
