// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { MfaAdminGenerateTotpSecretRequest as MfaAdminGenerateTotpSecretRequestSchema } from '../components/schemas/mfa-admin-generate-totp-secret-request.schema'

export interface MfaAdminGenerateTotpSecretResponseBodies {
  200: void
}

export interface MfaAdminGenerateTotpSecretRequestBodies {
  'application/json': MfaAdminGenerateTotpSecretRequestSchema
}

export type MfaAdminGenerateTotpSecretRequestQuery = {}

export type MfaAdminGenerateTotpSecretRouteParameters = {}

export type MfaAdminGenerateTotpSecretRequestHeaders = {}

interface MfaAdminGenerateTotpSecretParameterBodies {
  'application/json': MfaAdminGenerateTotpSecretRequestSchema & { [key: string]: any }
}

export type MfaAdminGenerateTotpSecretRequestParameters = MfaAdminGenerateTotpSecretRequestQuery & MfaAdminGenerateTotpSecretRouteParameters & MfaAdminGenerateTotpSecretRequestHeaders & MfaAdminGenerateTotpSecretRequestBodies['application/json']

export interface MfaAdminGenerateTotpSecretOperation<STATUS extends keyof MfaAdminGenerateTotpSecretResponseBodies, CONTENT_TYPE extends keyof MfaAdminGenerateTotpSecretParameterBodies> extends KeqOperation {
  requestParams: MfaAdminGenerateTotpSecretRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaAdminGenerateTotpSecretRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaAdminGenerateTotpSecretRequestHeaders & { [key: string]: string | number }
  requestBody: MfaAdminGenerateTotpSecretParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: MfaAdminGenerateTotpSecretResponseBodies[STATUS]
}

/* @anchor:file:end */
