// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaListLoginEnforcementsResponseBodies {
  200: void
}

export interface MfaListLoginEnforcementsRequestBodies {}

export type MfaListLoginEnforcementsRequestQuery = {
  list: 'true'
}

export type MfaListLoginEnforcementsRouteParameters = {}

export type MfaListLoginEnforcementsRequestHeaders = {}

export type MfaListLoginEnforcementsRequestParameters = MfaListLoginEnforcementsRequestQuery & MfaListLoginEnforcementsRouteParameters & MfaListLoginEnforcementsRequestHeaders

export interface MfaListLoginEnforcementsOperation<STATUS extends keyof MfaListLoginEnforcementsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaListLoginEnforcementsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaListLoginEnforcementsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaListLoginEnforcementsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaListLoginEnforcementsResponseBodies[STATUS]
}

/* @anchor:file:end */
