// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaReadTotpMethodConfigurationResponseBodies {
  200: void
}

export interface MfaReadTotpMethodConfigurationRequestBodies {}

export type MfaReadTotpMethodConfigurationRequestQuery = {}

export type MfaReadTotpMethodConfigurationRouteParameters = {}

export type MfaReadTotpMethodConfigurationRequestHeaders = {}

export type MfaReadTotpMethodConfigurationRequestParameters = MfaReadTotpMethodConfigurationRequestQuery & MfaReadTotpMethodConfigurationRouteParameters & MfaReadTotpMethodConfigurationRequestHeaders

export interface MfaReadTotpMethodConfigurationOperation<STATUS extends keyof MfaReadTotpMethodConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaReadTotpMethodConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaReadTotpMethodConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaReadTotpMethodConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaReadTotpMethodConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
