// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaListDuoMethodsResponseBodies {
  200: void
}

export interface MfaListDuoMethodsRequestBodies {}

export type MfaListDuoMethodsRequestQuery = {
  list: 'true'
}

export type MfaListDuoMethodsRouteParameters = {}

export type MfaListDuoMethodsRequestHeaders = {}

export type MfaListDuoMethodsRequestParameters = MfaListDuoMethodsRequestQuery & MfaListDuoMethodsRouteParameters & MfaListDuoMethodsRequestHeaders

export interface MfaListDuoMethodsOperation<STATUS extends keyof MfaListDuoMethodsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaListDuoMethodsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaListDuoMethodsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaListDuoMethodsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaListDuoMethodsResponseBodies[STATUS]
}

/* @anchor:file:end */
