// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaDeleteLoginEnforcementResponseBodies {
  204: void
}

export interface MfaDeleteLoginEnforcementRequestBodies {}

export type MfaDeleteLoginEnforcementRequestQuery = {}

export type MfaDeleteLoginEnforcementRouteParameters = {}

export type MfaDeleteLoginEnforcementRequestHeaders = {}

export type MfaDeleteLoginEnforcementRequestParameters = MfaDeleteLoginEnforcementRequestQuery & MfaDeleteLoginEnforcementRouteParameters & MfaDeleteLoginEnforcementRequestHeaders

export interface MfaDeleteLoginEnforcementOperation<STATUS extends keyof MfaDeleteLoginEnforcementResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaDeleteLoginEnforcementRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaDeleteLoginEnforcementRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaDeleteLoginEnforcementRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaDeleteLoginEnforcementResponseBodies[STATUS]
}

/* @anchor:file:end */
