// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaReadPingIdMethodConfigurationResponseBodies {
  200: void
}

export interface MfaReadPingIdMethodConfigurationRequestBodies {}

export type MfaReadPingIdMethodConfigurationRequestQuery = {}

export type MfaReadPingIdMethodConfigurationRouteParameters = {}

export type MfaReadPingIdMethodConfigurationRequestHeaders = {}

export type MfaReadPingIdMethodConfigurationRequestParameters = MfaReadPingIdMethodConfigurationRequestQuery & MfaReadPingIdMethodConfigurationRouteParameters & MfaReadPingIdMethodConfigurationRequestHeaders

export interface MfaReadPingIdMethodConfigurationOperation<STATUS extends keyof MfaReadPingIdMethodConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaReadPingIdMethodConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaReadPingIdMethodConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaReadPingIdMethodConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaReadPingIdMethodConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
