// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaReadMethodConfigurationResponseBodies {
  200: void
}

export interface MfaReadMethodConfigurationRequestBodies {}

export type MfaReadMethodConfigurationRequestQuery = {}

export type MfaReadMethodConfigurationRouteParameters = {}

export type MfaReadMethodConfigurationRequestHeaders = {}

export type MfaReadMethodConfigurationRequestParameters = MfaReadMethodConfigurationRequestQuery & MfaReadMethodConfigurationRouteParameters & MfaReadMethodConfigurationRequestHeaders

export interface MfaReadMethodConfigurationOperation<STATUS extends keyof MfaReadMethodConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaReadMethodConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaReadMethodConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaReadMethodConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaReadMethodConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
