// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { MfaConfigureDuoMethodRequest as MfaConfigureDuoMethodRequestSchema } from '../components/schemas/mfa-configure-duo-method-request.schema'

export interface MfaConfigureDuoMethodResponseBodies {
  200: void
}

export interface MfaConfigureDuoMethodRequestBodies {
  'application/json': MfaConfigureDuoMethodRequestSchema
}

export type MfaConfigureDuoMethodRequestQuery = {}

export type MfaConfigureDuoMethodRouteParameters = {}

export type MfaConfigureDuoMethodRequestHeaders = {}

interface MfaConfigureDuoMethodParameterBodies {
  'application/json': MfaConfigureDuoMethodRequestSchema & { [key: string]: any }
}

export type MfaConfigureDuoMethodRequestParameters = MfaConfigureDuoMethodRequestQuery & MfaConfigureDuoMethodRouteParameters & MfaConfigureDuoMethodRequestHeaders & MfaConfigureDuoMethodRequestBodies['application/json']

export interface MfaConfigureDuoMethodOperation<STATUS extends keyof MfaConfigureDuoMethodResponseBodies, CONTENT_TYPE extends keyof MfaConfigureDuoMethodParameterBodies> extends KeqOperation {
  requestParams: MfaConfigureDuoMethodRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaConfigureDuoMethodRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaConfigureDuoMethodRequestHeaders & { [key: string]: string | number }
  requestBody: MfaConfigureDuoMethodParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: MfaConfigureDuoMethodResponseBodies[STATUS]
}

/* @anchor:file:end */
