// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaReadOktaMethodConfigurationResponseBodies {
  200: void
}

export interface MfaReadOktaMethodConfigurationRequestBodies {}

export type MfaReadOktaMethodConfigurationRequestQuery = {}

export type MfaReadOktaMethodConfigurationRouteParameters = {}

export type MfaReadOktaMethodConfigurationRequestHeaders = {}

export type MfaReadOktaMethodConfigurationRequestParameters = MfaReadOktaMethodConfigurationRequestQuery & MfaReadOktaMethodConfigurationRouteParameters & MfaReadOktaMethodConfigurationRequestHeaders

export interface MfaReadOktaMethodConfigurationOperation<STATUS extends keyof MfaReadOktaMethodConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaReadOktaMethodConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaReadOktaMethodConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaReadOktaMethodConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaReadOktaMethodConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
