// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MfaListTotpMethodsResponseBodies {
  200: void
}

export interface MfaListTotpMethodsRequestBodies {}

export type MfaListTotpMethodsRequestQuery = {
  list: ('true')
}

export type MfaListTotpMethodsRouteParameters = {}

export type MfaListTotpMethodsRequestHeaders = {}

export type MfaListTotpMethodsRequestParameters = MfaListTotpMethodsRequestQuery & MfaListTotpMethodsRouteParameters & MfaListTotpMethodsRequestHeaders

export interface MfaListTotpMethodsOperation<STATUS extends keyof MfaListTotpMethodsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MfaListTotpMethodsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MfaListTotpMethodsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MfaListTotpMethodsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MfaListTotpMethodsResponseBodies[STATUS]
}

/* @anchor:file:end */
