// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { MountsReadTuningInformationResponse as MountsReadTuningInformationResponseSchema } from '../components/schemas/mounts-read-tuning-information-response.schema'

export interface MountsReadTuningInformationResponseBodies {
  200: MountsReadTuningInformationResponseSchema
}

export interface MountsReadTuningInformationRequestBodies {}

export type MountsReadTuningInformationRequestQuery = {}

export type MountsReadTuningInformationRouteParameters = {}

export type MountsReadTuningInformationRequestHeaders = {}

export type MountsReadTuningInformationRequestParameters = MountsReadTuningInformationRequestQuery & MountsReadTuningInformationRouteParameters & MountsReadTuningInformationRequestHeaders

export interface MountsReadTuningInformationOperation<STATUS extends keyof MountsReadTuningInformationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MountsReadTuningInformationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MountsReadTuningInformationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MountsReadTuningInformationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MountsReadTuningInformationResponseBodies[STATUS]
}

/* @anchor:file:end */
