// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MountsListSecretsEnginesResponseBodies {
  200: void
}

export interface MountsListSecretsEnginesRequestBodies {}

export type MountsListSecretsEnginesRequestQuery = {}

export type MountsListSecretsEnginesRouteParameters = {}

export type MountsListSecretsEnginesRequestHeaders = {}

export type MountsListSecretsEnginesRequestParameters = MountsListSecretsEnginesRequestQuery & MountsListSecretsEnginesRouteParameters & MountsListSecretsEnginesRequestHeaders

export interface MountsListSecretsEnginesOperation<STATUS extends keyof MountsListSecretsEnginesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MountsListSecretsEnginesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MountsListSecretsEnginesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MountsListSecretsEnginesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MountsListSecretsEnginesResponseBodies[STATUS]
}

/* @anchor:file:end */
