// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface MountsDisableSecretsEngineResponseBodies {
  200: void
}

export interface MountsDisableSecretsEngineRequestBodies {}

export type MountsDisableSecretsEngineRequestQuery = {}

export type MountsDisableSecretsEngineRouteParameters = {}

export type MountsDisableSecretsEngineRequestHeaders = {}

export type MountsDisableSecretsEngineRequestParameters = MountsDisableSecretsEngineRequestQuery & MountsDisableSecretsEngineRouteParameters & MountsDisableSecretsEngineRequestHeaders

export interface MountsDisableSecretsEngineOperation<STATUS extends keyof MountsDisableSecretsEngineResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MountsDisableSecretsEngineRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MountsDisableSecretsEngineRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MountsDisableSecretsEngineRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MountsDisableSecretsEngineResponseBodies[STATUS]
}

/* @anchor:file:end */
