// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { MountsEnableSecretsEngineRequest as MountsEnableSecretsEngineRequestSchema } from '../components/schemas/mounts-enable-secrets-engine-request.schema'

export interface MountsEnableSecretsEngineResponseBodies {
  204: void
}

export interface MountsEnableSecretsEngineRequestBodies {
  'application/json': MountsEnableSecretsEngineRequestSchema
}

export type MountsEnableSecretsEngineRequestQuery = {}

export type MountsEnableSecretsEngineRouteParameters = {}

export type MountsEnableSecretsEngineRequestHeaders = {}

interface MountsEnableSecretsEngineParameterBodies {
  'application/json': MountsEnableSecretsEngineRequestSchema & { [key: string]: any }
}

export type MountsEnableSecretsEngineRequestParameters = MountsEnableSecretsEngineRequestQuery & MountsEnableSecretsEngineRouteParameters & MountsEnableSecretsEngineRequestHeaders & MountsEnableSecretsEngineRequestBodies['application/json']

export interface MountsEnableSecretsEngineOperation<STATUS extends keyof MountsEnableSecretsEngineResponseBodies, CONTENT_TYPE extends keyof MountsEnableSecretsEngineParameterBodies> extends KeqOperation {
  requestParams: MountsEnableSecretsEngineRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MountsEnableSecretsEngineRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MountsEnableSecretsEngineRequestHeaders & { [key: string]: string | number }
  requestBody: MountsEnableSecretsEngineParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: MountsEnableSecretsEngineResponseBodies[STATUS]
}

/* @anchor:file:end */
