// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { MountsTuneConfigurationParametersRequest as MountsTuneConfigurationParametersRequestSchema } from '../components/schemas/mounts-tune-configuration-parameters-request.schema'

export interface MountsTuneConfigurationParametersResponseBodies {
  200: void
}

export interface MountsTuneConfigurationParametersRequestBodies {
  'application/json': MountsTuneConfigurationParametersRequestSchema
}

export type MountsTuneConfigurationParametersRequestQuery = {}

export type MountsTuneConfigurationParametersRouteParameters = {}

export type MountsTuneConfigurationParametersRequestHeaders = {}

interface MountsTuneConfigurationParametersParameterBodies {
  'application/json': MountsTuneConfigurationParametersRequestSchema & { [key: string]: any }
}

export type MountsTuneConfigurationParametersRequestParameters = MountsTuneConfigurationParametersRequestQuery & MountsTuneConfigurationParametersRouteParameters & MountsTuneConfigurationParametersRequestHeaders & MountsTuneConfigurationParametersRequestBodies['application/json']

export interface MountsTuneConfigurationParametersOperation<STATUS extends keyof MountsTuneConfigurationParametersResponseBodies, CONTENT_TYPE extends keyof MountsTuneConfigurationParametersParameterBodies> extends KeqOperation {
  requestParams: MountsTuneConfigurationParametersRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MountsTuneConfigurationParametersRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MountsTuneConfigurationParametersRequestHeaders & { [key: string]: string | number }
  requestBody: MountsTuneConfigurationParametersParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: MountsTuneConfigurationParametersResponseBodies[STATUS]
}

/* @anchor:file:end */
