// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { MountsReadConfigurationResponse as MountsReadConfigurationResponseSchema } from '../components/schemas/mounts-read-configuration-response.schema'

export interface MountsReadConfigurationResponseBodies {
  200: MountsReadConfigurationResponseSchema
}

export interface MountsReadConfigurationRequestBodies {}

export type MountsReadConfigurationRequestQuery = {}

export type MountsReadConfigurationRouteParameters = {}

export type MountsReadConfigurationRequestHeaders = {}

export type MountsReadConfigurationRequestParameters = MountsReadConfigurationRequestQuery & MountsReadConfigurationRouteParameters & MountsReadConfigurationRequestHeaders

export interface MountsReadConfigurationOperation<STATUS extends keyof MountsReadConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: MountsReadConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: MountsReadConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: MountsReadConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: MountsReadConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
