// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { NamespacesWriteNamespacesApiLockUnlockRequest as NamespacesWriteNamespacesApiLockUnlockRequestSchema } from '../components/schemas/namespaces-write-namespaces-api-lock-unlock-request.schema'

export interface NamespacesWriteNamespacesApiLockUnlockResponseBodies {
  204: void
}

export interface NamespacesWriteNamespacesApiLockUnlockRequestBodies {
  'application/json': NamespacesWriteNamespacesApiLockUnlockRequestSchema
}

export type NamespacesWriteNamespacesApiLockUnlockRequestQuery = {}

export type NamespacesWriteNamespacesApiLockUnlockRouteParameters = {}

export type NamespacesWriteNamespacesApiLockUnlockRequestHeaders = {}

interface NamespacesWriteNamespacesApiLockUnlockParameterBodies {
  'application/json': NamespacesWriteNamespacesApiLockUnlockRequestSchema & { [key: string]: any }
}

export type NamespacesWriteNamespacesApiLockUnlockRequestParameters = NamespacesWriteNamespacesApiLockUnlockRequestQuery & NamespacesWriteNamespacesApiLockUnlockRouteParameters & NamespacesWriteNamespacesApiLockUnlockRequestHeaders & NamespacesWriteNamespacesApiLockUnlockRequestBodies['application/json']

export interface NamespacesWriteNamespacesApiLockUnlockOperation<STATUS extends keyof NamespacesWriteNamespacesApiLockUnlockResponseBodies, CONTENT_TYPE extends keyof NamespacesWriteNamespacesApiLockUnlockParameterBodies> extends KeqOperation {
  requestParams: NamespacesWriteNamespacesApiLockUnlockRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: NamespacesWriteNamespacesApiLockUnlockRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: NamespacesWriteNamespacesApiLockUnlockRequestHeaders & { [key: string]: string | number }
  requestBody: NamespacesWriteNamespacesApiLockUnlockParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: NamespacesWriteNamespacesApiLockUnlockResponseBodies[STATUS]
}

/* @anchor:file:end */
