// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { NamespacesListNamespacesResponse as NamespacesListNamespacesResponseSchema } from '../components/schemas/namespaces-list-namespaces-response.schema'

export interface NamespacesListNamespacesResponseBodies {
  200: NamespacesListNamespacesResponseSchema
}

export interface NamespacesListNamespacesRequestBodies {}

export type NamespacesListNamespacesRequestQuery = {
  list: ('true')
}

export type NamespacesListNamespacesRouteParameters = {}

export type NamespacesListNamespacesRequestHeaders = {}

export type NamespacesListNamespacesRequestParameters = NamespacesListNamespacesRequestQuery & NamespacesListNamespacesRouteParameters & NamespacesListNamespacesRequestHeaders

export interface NamespacesListNamespacesOperation<STATUS extends keyof NamespacesListNamespacesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: NamespacesListNamespacesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: NamespacesListNamespacesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: NamespacesListNamespacesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: NamespacesListNamespacesResponseBodies[STATUS]
}

/* @anchor:file:end */
