// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { NamespacesWriteNamespacesPathRequest as NamespacesWriteNamespacesPathRequestSchema } from '../components/schemas/namespaces-write-namespaces-path-request.schema'
import type { NamespacesWriteNamespacesPathResponse as NamespacesWriteNamespacesPathResponseSchema } from '../components/schemas/namespaces-write-namespaces-path-response.schema'

export interface NamespacesWriteNamespacesPathResponseBodies {
  200: NamespacesWriteNamespacesPathResponseSchema
}

export interface NamespacesWriteNamespacesPathRequestBodies {
  'application/json': NamespacesWriteNamespacesPathRequestSchema
}

export type NamespacesWriteNamespacesPathRequestQuery = {}

export type NamespacesWriteNamespacesPathRouteParameters = {}

export type NamespacesWriteNamespacesPathRequestHeaders = {}

interface NamespacesWriteNamespacesPathParameterBodies {
  'application/json': NamespacesWriteNamespacesPathRequestSchema & { [key: string]: any }
}

export type NamespacesWriteNamespacesPathRequestParameters = NamespacesWriteNamespacesPathRequestQuery & NamespacesWriteNamespacesPathRouteParameters & NamespacesWriteNamespacesPathRequestHeaders & NamespacesWriteNamespacesPathRequestBodies['application/json']

export interface NamespacesWriteNamespacesPathOperation<STATUS extends keyof NamespacesWriteNamespacesPathResponseBodies, CONTENT_TYPE extends keyof NamespacesWriteNamespacesPathParameterBodies> extends KeqOperation {
  requestParams: NamespacesWriteNamespacesPathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: NamespacesWriteNamespacesPathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: NamespacesWriteNamespacesPathRequestHeaders & { [key: string]: string | number }
  requestBody: NamespacesWriteNamespacesPathParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: NamespacesWriteNamespacesPathResponseBodies[STATUS]
}

/* @anchor:file:end */
