// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { NamespacesWriteNamespacesApiLockLockRequest as NamespacesWriteNamespacesApiLockLockRequestSchema } from '../components/schemas/namespaces-write-namespaces-api-lock-lock-request.schema'
import type { NamespacesWriteNamespacesApiLockLockResponse as NamespacesWriteNamespacesApiLockLockResponseSchema } from '../components/schemas/namespaces-write-namespaces-api-lock-lock-response.schema'

export interface NamespacesWriteNamespacesApiLockLockResponseBodies {
  200: NamespacesWriteNamespacesApiLockLockResponseSchema
}

export interface NamespacesWriteNamespacesApiLockLockRequestBodies {
  'application/json': NamespacesWriteNamespacesApiLockLockRequestSchema
}

export type NamespacesWriteNamespacesApiLockLockRequestQuery = {}

export type NamespacesWriteNamespacesApiLockLockRouteParameters = {}

export type NamespacesWriteNamespacesApiLockLockRequestHeaders = {}

interface NamespacesWriteNamespacesApiLockLockParameterBodies {
  'application/json': NamespacesWriteNamespacesApiLockLockRequestSchema & { [key: string]: any }
}

export type NamespacesWriteNamespacesApiLockLockRequestParameters = NamespacesWriteNamespacesApiLockLockRequestQuery & NamespacesWriteNamespacesApiLockLockRouteParameters & NamespacesWriteNamespacesApiLockLockRequestHeaders & NamespacesWriteNamespacesApiLockLockRequestBodies['application/json']

export interface NamespacesWriteNamespacesApiLockLockOperation<STATUS extends keyof NamespacesWriteNamespacesApiLockLockResponseBodies, CONTENT_TYPE extends keyof NamespacesWriteNamespacesApiLockLockParameterBodies> extends KeqOperation {
  requestParams: NamespacesWriteNamespacesApiLockLockRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: NamespacesWriteNamespacesApiLockLockRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: NamespacesWriteNamespacesApiLockLockRequestHeaders & { [key: string]: string | number }
  requestBody: NamespacesWriteNamespacesApiLockLockParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: NamespacesWriteNamespacesApiLockLockResponseBodies[STATUS]
}

/* @anchor:file:end */
