// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { NamespacesWriteNamespacesApiLockUnlockPathRequest as NamespacesWriteNamespacesApiLockUnlockPathRequestSchema } from '../components/schemas/namespaces-write-namespaces-api-lock-unlock-path-request.schema'

export interface NamespacesWriteNamespacesApiLockUnlockPathResponseBodies {
  204: void
}

export interface NamespacesWriteNamespacesApiLockUnlockPathRequestBodies {
  'application/json': NamespacesWriteNamespacesApiLockUnlockPathRequestSchema
}

export type NamespacesWriteNamespacesApiLockUnlockPathRequestQuery = {}

export type NamespacesWriteNamespacesApiLockUnlockPathRouteParameters = {}

export type NamespacesWriteNamespacesApiLockUnlockPathRequestHeaders = {}

interface NamespacesWriteNamespacesApiLockUnlockPathParameterBodies {
  'application/json': NamespacesWriteNamespacesApiLockUnlockPathRequestSchema & { [key: string]: any }
}

export type NamespacesWriteNamespacesApiLockUnlockPathRequestParameters = NamespacesWriteNamespacesApiLockUnlockPathRequestQuery & NamespacesWriteNamespacesApiLockUnlockPathRouteParameters & NamespacesWriteNamespacesApiLockUnlockPathRequestHeaders & NamespacesWriteNamespacesApiLockUnlockPathRequestBodies['application/json']

export interface NamespacesWriteNamespacesApiLockUnlockPathOperation<STATUS extends keyof NamespacesWriteNamespacesApiLockUnlockPathResponseBodies, CONTENT_TYPE extends keyof NamespacesWriteNamespacesApiLockUnlockPathParameterBodies> extends KeqOperation {
  requestParams: NamespacesWriteNamespacesApiLockUnlockPathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: NamespacesWriteNamespacesApiLockUnlockPathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: NamespacesWriteNamespacesApiLockUnlockPathRequestHeaders & { [key: string]: string | number }
  requestBody: NamespacesWriteNamespacesApiLockUnlockPathParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: NamespacesWriteNamespacesApiLockUnlockPathResponseBodies[STATUS]
}

/* @anchor:file:end */
