// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { NamespacesReadNamespacesPathResponse as NamespacesReadNamespacesPathResponseSchema } from '../components/schemas/namespaces-read-namespaces-path-response.schema'

export interface NamespacesReadNamespacesPathResponseBodies {
  200: NamespacesReadNamespacesPathResponseSchema
}

export interface NamespacesReadNamespacesPathRequestBodies {}

export type NamespacesReadNamespacesPathRequestQuery = {}

export type NamespacesReadNamespacesPathRouteParameters = {}

export type NamespacesReadNamespacesPathRequestHeaders = {}

export type NamespacesReadNamespacesPathRequestParameters = NamespacesReadNamespacesPathRequestQuery & NamespacesReadNamespacesPathRouteParameters & NamespacesReadNamespacesPathRequestHeaders

export interface NamespacesReadNamespacesPathOperation<STATUS extends keyof NamespacesReadNamespacesPathResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: NamespacesReadNamespacesPathRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: NamespacesReadNamespacesPathRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: NamespacesReadNamespacesPathRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: NamespacesReadNamespacesPathResponseBodies[STATUS]
}

/* @anchor:file:end */
