// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcListProvidersResponseBodies {
  200: void
}

export interface OidcListProvidersRequestBodies {}

export type OidcListProvidersRequestQuery = {
  list: 'true'
}

export type OidcListProvidersRouteParameters = {}

export type OidcListProvidersRequestHeaders = {}

export type OidcListProvidersRequestParameters = OidcListProvidersRequestQuery & OidcListProvidersRouteParameters & OidcListProvidersRequestHeaders

export interface OidcListProvidersOperation<STATUS extends keyof OidcListProvidersResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcListProvidersRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcListProvidersRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcListProvidersRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcListProvidersResponseBodies[STATUS]
}

/* @anchor:file:end */
