// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcDeleteAssignmentResponseBodies {
  204: void
}

export interface OidcDeleteAssignmentRequestBodies {}

export type OidcDeleteAssignmentRequestQuery = {}

export type OidcDeleteAssignmentRouteParameters = {}

export type OidcDeleteAssignmentRequestHeaders = {}

export type OidcDeleteAssignmentRequestParameters = OidcDeleteAssignmentRequestQuery & OidcDeleteAssignmentRouteParameters & OidcDeleteAssignmentRequestHeaders

export interface OidcDeleteAssignmentOperation<STATUS extends keyof OidcDeleteAssignmentResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcDeleteAssignmentRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcDeleteAssignmentRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcDeleteAssignmentRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcDeleteAssignmentResponseBodies[STATUS]
}

/* @anchor:file:end */
