// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { OidcWriteAssignmentRequest as OidcWriteAssignmentRequestSchema } from '../components/schemas/oidc-write-assignment-request.schema'

export interface OidcWriteAssignmentResponseBodies {
  200: void
}

export interface OidcWriteAssignmentRequestBodies {
  'application/json': OidcWriteAssignmentRequestSchema
}

export type OidcWriteAssignmentRequestQuery = {}

export type OidcWriteAssignmentRouteParameters = {}

export type OidcWriteAssignmentRequestHeaders = {}

interface OidcWriteAssignmentParameterBodies {
  'application/json': OidcWriteAssignmentRequestSchema & { [key: string]: any }
}

export type OidcWriteAssignmentRequestParameters = OidcWriteAssignmentRequestQuery & OidcWriteAssignmentRouteParameters & OidcWriteAssignmentRequestHeaders & OidcWriteAssignmentRequestBodies['application/json']

export interface OidcWriteAssignmentOperation<STATUS extends keyof OidcWriteAssignmentResponseBodies, CONTENT_TYPE extends keyof OidcWriteAssignmentParameterBodies> extends KeqOperation {
  requestParams: OidcWriteAssignmentRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcWriteAssignmentRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcWriteAssignmentRequestHeaders & { [key: string]: string | number }
  requestBody: OidcWriteAssignmentParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: OidcWriteAssignmentResponseBodies[STATUS]
}

/* @anchor:file:end */
