// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { OidcWriteRoleRequest as OidcWriteRoleRequestSchema } from '../components/schemas/oidc-write-role-request.schema'

export interface OidcWriteRoleResponseBodies {
  200: void
}

export interface OidcWriteRoleRequestBodies {
  'application/json': OidcWriteRoleRequestSchema
}

export type OidcWriteRoleRequestQuery = {}

export type OidcWriteRoleRouteParameters = {}

export type OidcWriteRoleRequestHeaders = {}

interface OidcWriteRoleParameterBodies {
  'application/json': OidcWriteRoleRequestSchema & { [key: string]: any }
}

export type OidcWriteRoleRequestParameters = OidcWriteRoleRequestQuery & OidcWriteRoleRouteParameters & OidcWriteRoleRequestHeaders & OidcWriteRoleRequestBodies['application/json']

export interface OidcWriteRoleOperation<STATUS extends keyof OidcWriteRoleResponseBodies, CONTENT_TYPE extends keyof OidcWriteRoleParameterBodies> extends KeqOperation {
  requestParams: OidcWriteRoleRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcWriteRoleRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcWriteRoleRequestHeaders & { [key: string]: string | number }
  requestBody: OidcWriteRoleParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: OidcWriteRoleResponseBodies[STATUS]
}

/* @anchor:file:end */
