// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcDeleteProviderResponseBodies {
  204: void
}

export interface OidcDeleteProviderRequestBodies {}

export type OidcDeleteProviderRequestQuery = {}

export type OidcDeleteProviderRouteParameters = {}

export type OidcDeleteProviderRequestHeaders = {}

export type OidcDeleteProviderRequestParameters = OidcDeleteProviderRequestQuery & OidcDeleteProviderRouteParameters & OidcDeleteProviderRequestHeaders

export interface OidcDeleteProviderOperation<STATUS extends keyof OidcDeleteProviderResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcDeleteProviderRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcDeleteProviderRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcDeleteProviderRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcDeleteProviderResponseBodies[STATUS]
}

/* @anchor:file:end */
