// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcDeleteKeyResponseBodies {
  204: void
}

export interface OidcDeleteKeyRequestBodies {}

export type OidcDeleteKeyRequestQuery = {}

export type OidcDeleteKeyRouteParameters = {}

export type OidcDeleteKeyRequestHeaders = {}

export type OidcDeleteKeyRequestParameters = OidcDeleteKeyRequestQuery & OidcDeleteKeyRouteParameters & OidcDeleteKeyRequestHeaders

export interface OidcDeleteKeyOperation<STATUS extends keyof OidcDeleteKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcDeleteKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcDeleteKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcDeleteKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcDeleteKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
