// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { OidcProviderTokenRequest as OidcProviderTokenRequestSchema } from '../components/schemas/oidc-provider-token-request.schema'

export interface OidcProviderTokenResponseBodies {
  200: void
}

export interface OidcProviderTokenRequestBodies {
  'application/json': OidcProviderTokenRequestSchema
}

export type OidcProviderTokenRequestQuery = {}

export type OidcProviderTokenRouteParameters = {}

export type OidcProviderTokenRequestHeaders = {}

interface OidcProviderTokenParameterBodies {
  'application/json': OidcProviderTokenRequestSchema & { [key: string]: any }
}

export type OidcProviderTokenRequestParameters = OidcProviderTokenRequestQuery & OidcProviderTokenRouteParameters & OidcProviderTokenRequestHeaders & OidcProviderTokenRequestBodies['application/json']

export interface OidcProviderTokenOperation<STATUS extends keyof OidcProviderTokenResponseBodies, CONTENT_TYPE extends keyof OidcProviderTokenParameterBodies> extends KeqOperation {
  requestParams: OidcProviderTokenRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcProviderTokenRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcProviderTokenRequestHeaders & { [key: string]: string | number }
  requestBody: OidcProviderTokenParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: OidcProviderTokenResponseBodies[STATUS]
}

/* @anchor:file:end */
