// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcListAssignmentsResponseBodies {
  200: void
}

export interface OidcListAssignmentsRequestBodies {}

export type OidcListAssignmentsRequestQuery = {
  list: ('true')
}

export type OidcListAssignmentsRouteParameters = {}

export type OidcListAssignmentsRequestHeaders = {}

export type OidcListAssignmentsRequestParameters = OidcListAssignmentsRequestQuery & OidcListAssignmentsRouteParameters & OidcListAssignmentsRequestHeaders

export interface OidcListAssignmentsOperation<STATUS extends keyof OidcListAssignmentsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcListAssignmentsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcListAssignmentsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcListAssignmentsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcListAssignmentsResponseBodies[STATUS]
}

/* @anchor:file:end */
