// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcDeleteClientResponseBodies {
  204: void
}

export interface OidcDeleteClientRequestBodies {}

export type OidcDeleteClientRequestQuery = {}

export type OidcDeleteClientRouteParameters = {}

export type OidcDeleteClientRequestHeaders = {}

export type OidcDeleteClientRequestParameters = OidcDeleteClientRequestQuery & OidcDeleteClientRouteParameters & OidcDeleteClientRequestHeaders

export interface OidcDeleteClientOperation<STATUS extends keyof OidcDeleteClientResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcDeleteClientRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcDeleteClientRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcDeleteClientRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcDeleteClientResponseBodies[STATUS]
}

/* @anchor:file:end */
