// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcProviderAuthorizeResponseBodies {
  200: void
}

export interface OidcProviderAuthorizeRequestBodies {}

export type OidcProviderAuthorizeRequestQuery = {}

export type OidcProviderAuthorizeRouteParameters = {}

export type OidcProviderAuthorizeRequestHeaders = {}

export type OidcProviderAuthorizeRequestParameters = OidcProviderAuthorizeRequestQuery & OidcProviderAuthorizeRouteParameters & OidcProviderAuthorizeRequestHeaders

export interface OidcProviderAuthorizeOperation<STATUS extends keyof OidcProviderAuthorizeResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcProviderAuthorizeRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcProviderAuthorizeRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcProviderAuthorizeRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcProviderAuthorizeResponseBodies[STATUS]
}

/* @anchor:file:end */
