// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcListRolesResponseBodies {
  200: void
}

export interface OidcListRolesRequestBodies {}

export type OidcListRolesRequestQuery = {
  list: ('true')
}

export type OidcListRolesRouteParameters = {}

export type OidcListRolesRequestHeaders = {}

export type OidcListRolesRequestParameters = OidcListRolesRequestQuery & OidcListRolesRouteParameters & OidcListRolesRequestHeaders

export interface OidcListRolesOperation<STATUS extends keyof OidcListRolesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcListRolesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcListRolesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcListRolesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcListRolesResponseBodies[STATUS]
}

/* @anchor:file:end */
