// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcReadProviderResponseBodies {
  200: void
}

export interface OidcReadProviderRequestBodies {}

export type OidcReadProviderRequestQuery = {}

export type OidcReadProviderRouteParameters = {}

export type OidcReadProviderRequestHeaders = {}

export type OidcReadProviderRequestParameters = OidcReadProviderRequestQuery & OidcReadProviderRouteParameters & OidcReadProviderRequestHeaders

export interface OidcReadProviderOperation<STATUS extends keyof OidcReadProviderResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcReadProviderRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcReadProviderRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcReadProviderRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcReadProviderResponseBodies[STATUS]
}

/* @anchor:file:end */
