// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcReadRoleResponseBodies {
  200: void
}

export interface OidcReadRoleRequestBodies {}

export type OidcReadRoleRequestQuery = {}

export type OidcReadRoleRouteParameters = {}

export type OidcReadRoleRequestHeaders = {}

export type OidcReadRoleRequestParameters = OidcReadRoleRequestQuery & OidcReadRoleRouteParameters & OidcReadRoleRequestHeaders

export interface OidcReadRoleOperation<STATUS extends keyof OidcReadRoleResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcReadRoleRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcReadRoleRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcReadRoleRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcReadRoleResponseBodies[STATUS]
}

/* @anchor:file:end */
