// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { OidcIntrospectRequest as OidcIntrospectRequestSchema } from '../components/schemas/oidc-introspect-request.schema'

export interface OidcIntrospectResponseBodies {
  200: void
}

export interface OidcIntrospectRequestBodies {
  'application/json': OidcIntrospectRequestSchema
}

export type OidcIntrospectRequestQuery = {}

export type OidcIntrospectRouteParameters = {}

export type OidcIntrospectRequestHeaders = {}

interface OidcIntrospectParameterBodies {
  'application/json': OidcIntrospectRequestSchema & { [key: string]: any }
}

export type OidcIntrospectRequestParameters = OidcIntrospectRequestQuery & OidcIntrospectRouteParameters & OidcIntrospectRequestHeaders & OidcIntrospectRequestBodies['application/json']

export interface OidcIntrospectOperation<STATUS extends keyof OidcIntrospectResponseBodies, CONTENT_TYPE extends keyof OidcIntrospectParameterBodies> extends KeqOperation {
  requestParams: OidcIntrospectRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcIntrospectRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcIntrospectRequestHeaders & { [key: string]: string | number }
  requestBody: OidcIntrospectParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: OidcIntrospectResponseBodies[STATUS]
}

/* @anchor:file:end */
