// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcListScopesResponseBodies {
  200: void
}

export interface OidcListScopesRequestBodies {}

export type OidcListScopesRequestQuery = {
  list: ('true')
}

export type OidcListScopesRouteParameters = {}

export type OidcListScopesRequestHeaders = {}

export type OidcListScopesRequestParameters = OidcListScopesRequestQuery & OidcListScopesRouteParameters & OidcListScopesRequestHeaders

export interface OidcListScopesOperation<STATUS extends keyof OidcListScopesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcListScopesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcListScopesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcListScopesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcListScopesResponseBodies[STATUS]
}

/* @anchor:file:end */
