// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcGenerateTokenResponseBodies {
  200: void
}

export interface OidcGenerateTokenRequestBodies {}

export type OidcGenerateTokenRequestQuery = {}

export type OidcGenerateTokenRouteParameters = {}

export type OidcGenerateTokenRequestHeaders = {}

export type OidcGenerateTokenRequestParameters = OidcGenerateTokenRequestQuery & OidcGenerateTokenRouteParameters & OidcGenerateTokenRequestHeaders

export interface OidcGenerateTokenOperation<STATUS extends keyof OidcGenerateTokenResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcGenerateTokenRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcGenerateTokenRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcGenerateTokenRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcGenerateTokenResponseBodies[STATUS]
}

/* @anchor:file:end */
