// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcReadProviderPublicKeysResponseBodies {
  200: void
}

export interface OidcReadProviderPublicKeysRequestBodies {}

export type OidcReadProviderPublicKeysRequestQuery = {}

export type OidcReadProviderPublicKeysRouteParameters = {}

export type OidcReadProviderPublicKeysRequestHeaders = {}

export type OidcReadProviderPublicKeysRequestParameters = OidcReadProviderPublicKeysRequestQuery & OidcReadProviderPublicKeysRouteParameters & OidcReadProviderPublicKeysRequestHeaders

export interface OidcReadProviderPublicKeysOperation<STATUS extends keyof OidcReadProviderPublicKeysResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcReadProviderPublicKeysRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcReadProviderPublicKeysRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcReadProviderPublicKeysRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcReadProviderPublicKeysResponseBodies[STATUS]
}

/* @anchor:file:end */
