// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { OidcWriteClientRequest as OidcWriteClientRequestSchema } from '../components/schemas/oidc-write-client-request.schema'

export interface OidcWriteClientResponseBodies {
  200: void
}

export interface OidcWriteClientRequestBodies {
  'application/json': OidcWriteClientRequestSchema
}

export type OidcWriteClientRequestQuery = {}

export type OidcWriteClientRouteParameters = {}

export type OidcWriteClientRequestHeaders = {}

interface OidcWriteClientParameterBodies {
  'application/json': OidcWriteClientRequestSchema & { [key: string]: any }
}

export type OidcWriteClientRequestParameters = OidcWriteClientRequestQuery & OidcWriteClientRouteParameters & OidcWriteClientRequestHeaders & OidcWriteClientRequestBodies['application/json']

export interface OidcWriteClientOperation<STATUS extends keyof OidcWriteClientResponseBodies, CONTENT_TYPE extends keyof OidcWriteClientParameterBodies> extends KeqOperation {
  requestParams: OidcWriteClientRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcWriteClientRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcWriteClientRequestHeaders & { [key: string]: string | number }
  requestBody: OidcWriteClientParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: OidcWriteClientResponseBodies[STATUS]
}

/* @anchor:file:end */
