// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcReadOpenIdConfigurationResponseBodies {
  200: void
}

export interface OidcReadOpenIdConfigurationRequestBodies {}

export type OidcReadOpenIdConfigurationRequestQuery = {}

export type OidcReadOpenIdConfigurationRouteParameters = {}

export type OidcReadOpenIdConfigurationRequestHeaders = {}

export type OidcReadOpenIdConfigurationRequestParameters = OidcReadOpenIdConfigurationRequestQuery & OidcReadOpenIdConfigurationRouteParameters & OidcReadOpenIdConfigurationRequestHeaders

export interface OidcReadOpenIdConfigurationOperation<STATUS extends keyof OidcReadOpenIdConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcReadOpenIdConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcReadOpenIdConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcReadOpenIdConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcReadOpenIdConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
