// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcReadScopeResponseBodies {
  200: void
}

export interface OidcReadScopeRequestBodies {}

export type OidcReadScopeRequestQuery = {}

export type OidcReadScopeRouteParameters = {}

export type OidcReadScopeRequestHeaders = {}

export type OidcReadScopeRequestParameters = OidcReadScopeRequestQuery & OidcReadScopeRouteParameters & OidcReadScopeRequestHeaders

export interface OidcReadScopeOperation<STATUS extends keyof OidcReadScopeResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcReadScopeRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcReadScopeRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcReadScopeRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcReadScopeResponseBodies[STATUS]
}

/* @anchor:file:end */
