// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { OidcConfigureRequest as OidcConfigureRequestSchema } from '../components/schemas/oidc-configure-request.schema'

export interface OidcConfigureResponseBodies {
  200: void
}

export interface OidcConfigureRequestBodies {
  'application/json': OidcConfigureRequestSchema
}

export type OidcConfigureRequestQuery = {}

export type OidcConfigureRouteParameters = {}

export type OidcConfigureRequestHeaders = {}

interface OidcConfigureParameterBodies {
  'application/json': OidcConfigureRequestSchema & { [key: string]: any }
}

export type OidcConfigureRequestParameters = OidcConfigureRequestQuery & OidcConfigureRouteParameters & OidcConfigureRequestHeaders & OidcConfigureRequestBodies['application/json']

export interface OidcConfigureOperation<STATUS extends keyof OidcConfigureResponseBodies, CONTENT_TYPE extends keyof OidcConfigureParameterBodies> extends KeqOperation {
  requestParams: OidcConfigureRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcConfigureRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcConfigureRequestHeaders & { [key: string]: string | number }
  requestBody: OidcConfigureParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: OidcConfigureResponseBodies[STATUS]
}

/* @anchor:file:end */
