// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcDeleteScopeResponseBodies {
  204: void
}

export interface OidcDeleteScopeRequestBodies {}

export type OidcDeleteScopeRequestQuery = {}

export type OidcDeleteScopeRouteParameters = {}

export type OidcDeleteScopeRequestHeaders = {}

export type OidcDeleteScopeRequestParameters = OidcDeleteScopeRequestQuery & OidcDeleteScopeRouteParameters & OidcDeleteScopeRequestHeaders

export interface OidcDeleteScopeOperation<STATUS extends keyof OidcDeleteScopeResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcDeleteScopeRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcDeleteScopeRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcDeleteScopeRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcDeleteScopeResponseBodies[STATUS]
}

/* @anchor:file:end */
