// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface OidcListKeysResponseBodies {
  200: void
}

export interface OidcListKeysRequestBodies {}

export type OidcListKeysRequestQuery = {
  list: ('true')
}

export type OidcListKeysRouteParameters = {}

export type OidcListKeysRequestHeaders = {}

export type OidcListKeysRequestParameters = OidcListKeysRequestQuery & OidcListKeysRouteParameters & OidcListKeysRequestHeaders

export interface OidcListKeysOperation<STATUS extends keyof OidcListKeysResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: OidcListKeysRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: OidcListKeysRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: OidcListKeysRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: OidcListKeysResponseBodies[STATUS]
}

/* @anchor:file:end */
