// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PersonaReadByIdResponseBodies {
  200: void
}

export interface PersonaReadByIdRequestBodies {}

export type PersonaReadByIdRequestQuery = {}

export type PersonaReadByIdRouteParameters = {}

export type PersonaReadByIdRequestHeaders = {}

export type PersonaReadByIdRequestParameters = PersonaReadByIdRequestQuery & PersonaReadByIdRouteParameters & PersonaReadByIdRequestHeaders

export interface PersonaReadByIdOperation<STATUS extends keyof PersonaReadByIdResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PersonaReadByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PersonaReadByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PersonaReadByIdRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PersonaReadByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
