// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PersonaCreateRequest as PersonaCreateRequestSchema } from '../components/schemas/persona-create-request.schema'

export interface PersonaCreateResponseBodies {
  200: void
}

export interface PersonaCreateRequestBodies {
  'application/json': PersonaCreateRequestSchema
}

export type PersonaCreateRequestQuery = {}

export type PersonaCreateRouteParameters = {}

export type PersonaCreateRequestHeaders = {}

interface PersonaCreateParameterBodies {
  'application/json': PersonaCreateRequestSchema & { [key: string]: any }
}

export type PersonaCreateRequestParameters = PersonaCreateRequestQuery & PersonaCreateRouteParameters & PersonaCreateRequestHeaders & PersonaCreateRequestBodies['application/json']

export interface PersonaCreateOperation<STATUS extends keyof PersonaCreateResponseBodies, CONTENT_TYPE extends keyof PersonaCreateParameterBodies> extends KeqOperation {
  requestParams: PersonaCreateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PersonaCreateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PersonaCreateRequestHeaders & { [key: string]: string | number }
  requestBody: PersonaCreateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: PersonaCreateResponseBodies[STATUS]
}

/* @anchor:file:end */
