// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PersonaUpdateByIdRequest as PersonaUpdateByIdRequestSchema } from '../components/schemas/persona-update-by-id-request.schema'

export interface PersonaUpdateByIdResponseBodies {
  200: void
}

export interface PersonaUpdateByIdRequestBodies {
  'application/json': PersonaUpdateByIdRequestSchema
}

export type PersonaUpdateByIdRequestQuery = {}

export type PersonaUpdateByIdRouteParameters = {}

export type PersonaUpdateByIdRequestHeaders = {}

interface PersonaUpdateByIdParameterBodies {
  'application/json': PersonaUpdateByIdRequestSchema & { [key: string]: any }
}

export type PersonaUpdateByIdRequestParameters = PersonaUpdateByIdRequestQuery & PersonaUpdateByIdRouteParameters & PersonaUpdateByIdRequestHeaders & PersonaUpdateByIdRequestBodies['application/json']

export interface PersonaUpdateByIdOperation<STATUS extends keyof PersonaUpdateByIdResponseBodies, CONTENT_TYPE extends keyof PersonaUpdateByIdParameterBodies> extends KeqOperation {
  requestParams: PersonaUpdateByIdRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PersonaUpdateByIdRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PersonaUpdateByIdRequestHeaders & { [key: string]: string | number }
  requestBody: PersonaUpdateByIdParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: PersonaUpdateByIdResponseBodies[STATUS]
}

/* @anchor:file:end */
