// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PluginsCatalogListPluginsWithTypeResponse as PluginsCatalogListPluginsWithTypeResponseSchema } from '../components/schemas/plugins-catalog-list-plugins-with-type-response.schema'

export interface PluginsCatalogListPluginsWithTypeResponseBodies {
  200: PluginsCatalogListPluginsWithTypeResponseSchema
}

export interface PluginsCatalogListPluginsWithTypeRequestBodies {}

export type PluginsCatalogListPluginsWithTypeRequestQuery = {
  list: ('true')
}

export type PluginsCatalogListPluginsWithTypeRouteParameters = {}

export type PluginsCatalogListPluginsWithTypeRequestHeaders = {}

export type PluginsCatalogListPluginsWithTypeRequestParameters = PluginsCatalogListPluginsWithTypeRequestQuery & PluginsCatalogListPluginsWithTypeRouteParameters & PluginsCatalogListPluginsWithTypeRequestHeaders

export interface PluginsCatalogListPluginsWithTypeOperation<STATUS extends keyof PluginsCatalogListPluginsWithTypeResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PluginsCatalogListPluginsWithTypeRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PluginsCatalogListPluginsWithTypeRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PluginsCatalogListPluginsWithTypeRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PluginsCatalogListPluginsWithTypeResponseBodies[STATUS]
}

/* @anchor:file:end */
