// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PluginsCatalogListPluginsResponse as PluginsCatalogListPluginsResponseSchema } from '../components/schemas/plugins-catalog-list-plugins-response.schema'

export interface PluginsCatalogListPluginsResponseBodies {
  200: PluginsCatalogListPluginsResponseSchema
}

export interface PluginsCatalogListPluginsRequestBodies {}

export type PluginsCatalogListPluginsRequestQuery = {}

export type PluginsCatalogListPluginsRouteParameters = {}

export type PluginsCatalogListPluginsRequestHeaders = {}

export type PluginsCatalogListPluginsRequestParameters = PluginsCatalogListPluginsRequestQuery & PluginsCatalogListPluginsRouteParameters & PluginsCatalogListPluginsRequestHeaders

export interface PluginsCatalogListPluginsOperation<STATUS extends keyof PluginsCatalogListPluginsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PluginsCatalogListPluginsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PluginsCatalogListPluginsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PluginsCatalogListPluginsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PluginsCatalogListPluginsResponseBodies[STATUS]
}

/* @anchor:file:end */
