// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PluginsCatalogReadPluginConfigurationWithTypeResponse as PluginsCatalogReadPluginConfigurationWithTypeResponseSchema } from '../components/schemas/plugins-catalog-read-plugin-configuration-with-type-response.schema'

export interface PluginsCatalogReadPluginConfigurationWithTypeResponseBodies {
  200: PluginsCatalogReadPluginConfigurationWithTypeResponseSchema
}

export interface PluginsCatalogReadPluginConfigurationWithTypeRequestBodies {}

export type PluginsCatalogReadPluginConfigurationWithTypeRequestQuery = {}

export type PluginsCatalogReadPluginConfigurationWithTypeRouteParameters = {}

export type PluginsCatalogReadPluginConfigurationWithTypeRequestHeaders = {}

export type PluginsCatalogReadPluginConfigurationWithTypeRequestParameters = PluginsCatalogReadPluginConfigurationWithTypeRequestQuery & PluginsCatalogReadPluginConfigurationWithTypeRouteParameters & PluginsCatalogReadPluginConfigurationWithTypeRequestHeaders

export interface PluginsCatalogReadPluginConfigurationWithTypeOperation<STATUS extends keyof PluginsCatalogReadPluginConfigurationWithTypeResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PluginsCatalogReadPluginConfigurationWithTypeRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PluginsCatalogReadPluginConfigurationWithTypeRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PluginsCatalogReadPluginConfigurationWithTypeRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PluginsCatalogReadPluginConfigurationWithTypeResponseBodies[STATUS]
}

/* @anchor:file:end */
