// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PluginsCatalogRemovePluginResponseBodies {
  200: void
}

export interface PluginsCatalogRemovePluginRequestBodies {}

export type PluginsCatalogRemovePluginRequestQuery = {}

export type PluginsCatalogRemovePluginRouteParameters = {}

export type PluginsCatalogRemovePluginRequestHeaders = {}

export type PluginsCatalogRemovePluginRequestParameters = PluginsCatalogRemovePluginRequestQuery & PluginsCatalogRemovePluginRouteParameters & PluginsCatalogRemovePluginRequestHeaders

export interface PluginsCatalogRemovePluginOperation<STATUS extends keyof PluginsCatalogRemovePluginResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PluginsCatalogRemovePluginRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PluginsCatalogRemovePluginRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PluginsCatalogRemovePluginRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PluginsCatalogRemovePluginResponseBodies[STATUS]
}

/* @anchor:file:end */
