// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PluginsCatalogReadPluginConfigurationResponse as PluginsCatalogReadPluginConfigurationResponseSchema } from '../components/schemas/plugins-catalog-read-plugin-configuration-response.schema'

export interface PluginsCatalogReadPluginConfigurationResponseBodies {
  200: PluginsCatalogReadPluginConfigurationResponseSchema
}

export interface PluginsCatalogReadPluginConfigurationRequestBodies {}

export type PluginsCatalogReadPluginConfigurationRequestQuery = {}

export type PluginsCatalogReadPluginConfigurationRouteParameters = {}

export type PluginsCatalogReadPluginConfigurationRequestHeaders = {}

export type PluginsCatalogReadPluginConfigurationRequestParameters = PluginsCatalogReadPluginConfigurationRequestQuery & PluginsCatalogReadPluginConfigurationRouteParameters & PluginsCatalogReadPluginConfigurationRequestHeaders

export interface PluginsCatalogReadPluginConfigurationOperation<STATUS extends keyof PluginsCatalogReadPluginConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PluginsCatalogReadPluginConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PluginsCatalogReadPluginConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PluginsCatalogReadPluginConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PluginsCatalogReadPluginConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
