// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PluginsCatalogRemovePluginWithTypeResponseBodies {
  200: void
}

export interface PluginsCatalogRemovePluginWithTypeRequestBodies {}

export type PluginsCatalogRemovePluginWithTypeRequestQuery = {}

export type PluginsCatalogRemovePluginWithTypeRouteParameters = {}

export type PluginsCatalogRemovePluginWithTypeRequestHeaders = {}

export type PluginsCatalogRemovePluginWithTypeRequestParameters = PluginsCatalogRemovePluginWithTypeRequestQuery & PluginsCatalogRemovePluginWithTypeRouteParameters & PluginsCatalogRemovePluginWithTypeRequestHeaders

export interface PluginsCatalogRemovePluginWithTypeOperation<STATUS extends keyof PluginsCatalogRemovePluginWithTypeResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PluginsCatalogRemovePluginWithTypeRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PluginsCatalogRemovePluginWithTypeRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PluginsCatalogRemovePluginWithTypeRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PluginsCatalogRemovePluginWithTypeResponseBodies[STATUS]
}

/* @anchor:file:end */
