// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PoliciesReadAclPolicy2Response as PoliciesReadAclPolicy2ResponseSchema } from '../components/schemas/policies-read-acl-policy2-response.schema'

export interface PoliciesReadAclPolicy2ResponseBodies {
  200: PoliciesReadAclPolicy2ResponseSchema
}

export interface PoliciesReadAclPolicy2RequestBodies {}

export type PoliciesReadAclPolicy2RequestQuery = {
  list?: string
}

export type PoliciesReadAclPolicy2RouteParameters = {}

export type PoliciesReadAclPolicy2RequestHeaders = {}

export type PoliciesReadAclPolicy2RequestParameters = PoliciesReadAclPolicy2RequestQuery & PoliciesReadAclPolicy2RouteParameters & PoliciesReadAclPolicy2RequestHeaders

export interface PoliciesReadAclPolicy2Operation<STATUS extends keyof PoliciesReadAclPolicy2ResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PoliciesReadAclPolicy2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PoliciesReadAclPolicy2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PoliciesReadAclPolicy2RequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PoliciesReadAclPolicy2ResponseBodies[STATUS]
}

/* @anchor:file:end */
