// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PoliciesWriteAclPolicy2Request as PoliciesWriteAclPolicy2RequestSchema } from '../components/schemas/policies-write-acl-policy2-request.schema'

export interface PoliciesWriteAclPolicy2ResponseBodies {
  204: void
}

export interface PoliciesWriteAclPolicy2RequestBodies {
  'application/json': PoliciesWriteAclPolicy2RequestSchema
}

export type PoliciesWriteAclPolicy2RequestQuery = {}

export type PoliciesWriteAclPolicy2RouteParameters = {}

export type PoliciesWriteAclPolicy2RequestHeaders = {}

interface PoliciesWriteAclPolicy2ParameterBodies {
  'application/json': PoliciesWriteAclPolicy2RequestSchema & { [key: string]: any }
}

export type PoliciesWriteAclPolicy2RequestParameters = PoliciesWriteAclPolicy2RequestQuery & PoliciesWriteAclPolicy2RouteParameters & PoliciesWriteAclPolicy2RequestHeaders & PoliciesWriteAclPolicy2RequestBodies['application/json']

export interface PoliciesWriteAclPolicy2Operation<STATUS extends keyof PoliciesWriteAclPolicy2ResponseBodies, CONTENT_TYPE extends keyof PoliciesWriteAclPolicy2ParameterBodies> extends KeqOperation {
  requestParams: PoliciesWriteAclPolicy2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PoliciesWriteAclPolicy2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PoliciesWriteAclPolicy2RequestHeaders & { [key: string]: string | number }
  requestBody: PoliciesWriteAclPolicy2ParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: PoliciesWriteAclPolicy2ResponseBodies[STATUS]
}

/* @anchor:file:end */
