// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PoliciesDeletePasswordPolicyResponseBodies {
  204: void
}

export interface PoliciesDeletePasswordPolicyRequestBodies {}

export type PoliciesDeletePasswordPolicyRequestQuery = {}

export type PoliciesDeletePasswordPolicyRouteParameters = {}

export type PoliciesDeletePasswordPolicyRequestHeaders = {}

export type PoliciesDeletePasswordPolicyRequestParameters = PoliciesDeletePasswordPolicyRequestQuery & PoliciesDeletePasswordPolicyRouteParameters & PoliciesDeletePasswordPolicyRequestHeaders

export interface PoliciesDeletePasswordPolicyOperation<STATUS extends keyof PoliciesDeletePasswordPolicyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PoliciesDeletePasswordPolicyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PoliciesDeletePasswordPolicyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PoliciesDeletePasswordPolicyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PoliciesDeletePasswordPolicyResponseBodies[STATUS]
}

/* @anchor:file:end */
