// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PoliciesWriteAclPolicyRequest as PoliciesWriteAclPolicyRequestSchema } from '../components/schemas/policies-write-acl-policy-request.schema'

export interface PoliciesWriteAclPolicyResponseBodies {
  204: void
}

export interface PoliciesWriteAclPolicyRequestBodies {
  'application/json': PoliciesWriteAclPolicyRequestSchema
}

export type PoliciesWriteAclPolicyRequestQuery = {}

export type PoliciesWriteAclPolicyRouteParameters = {}

export type PoliciesWriteAclPolicyRequestHeaders = {}

interface PoliciesWriteAclPolicyParameterBodies {
  'application/json': PoliciesWriteAclPolicyRequestSchema & { [key: string]: any }
}

export type PoliciesWriteAclPolicyRequestParameters = PoliciesWriteAclPolicyRequestQuery & PoliciesWriteAclPolicyRouteParameters & PoliciesWriteAclPolicyRequestHeaders & PoliciesWriteAclPolicyRequestBodies['application/json']

export interface PoliciesWriteAclPolicyOperation<STATUS extends keyof PoliciesWriteAclPolicyResponseBodies, CONTENT_TYPE extends keyof PoliciesWriteAclPolicyParameterBodies> extends KeqOperation {
  requestParams: PoliciesWriteAclPolicyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PoliciesWriteAclPolicyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PoliciesWriteAclPolicyRequestHeaders & { [key: string]: string | number }
  requestBody: PoliciesWriteAclPolicyParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: PoliciesWriteAclPolicyResponseBodies[STATUS]
}

/* @anchor:file:end */
