// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PoliciesGeneratePasswordFromPasswordPolicyResponse as PoliciesGeneratePasswordFromPasswordPolicyResponseSchema } from '../components/schemas/policies-generate-password-from-password-policy-response.schema'

export interface PoliciesGeneratePasswordFromPasswordPolicyResponseBodies {
  200: PoliciesGeneratePasswordFromPasswordPolicyResponseSchema
}

export interface PoliciesGeneratePasswordFromPasswordPolicyRequestBodies {}

export type PoliciesGeneratePasswordFromPasswordPolicyRequestQuery = {}

export type PoliciesGeneratePasswordFromPasswordPolicyRouteParameters = {}

export type PoliciesGeneratePasswordFromPasswordPolicyRequestHeaders = {}

export type PoliciesGeneratePasswordFromPasswordPolicyRequestParameters = PoliciesGeneratePasswordFromPasswordPolicyRequestQuery & PoliciesGeneratePasswordFromPasswordPolicyRouteParameters & PoliciesGeneratePasswordFromPasswordPolicyRequestHeaders

export interface PoliciesGeneratePasswordFromPasswordPolicyOperation<STATUS extends keyof PoliciesGeneratePasswordFromPasswordPolicyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PoliciesGeneratePasswordFromPasswordPolicyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PoliciesGeneratePasswordFromPasswordPolicyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PoliciesGeneratePasswordFromPasswordPolicyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PoliciesGeneratePasswordFromPasswordPolicyResponseBodies[STATUS]
}

/* @anchor:file:end */
