// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { PoliciesWritePasswordPolicyRequest as PoliciesWritePasswordPolicyRequestSchema } from '../components/schemas/policies-write-password-policy-request.schema'

export interface PoliciesWritePasswordPolicyResponseBodies {
  204: void
}

export interface PoliciesWritePasswordPolicyRequestBodies {
  'application/json': PoliciesWritePasswordPolicyRequestSchema
}

export type PoliciesWritePasswordPolicyRequestQuery = {}

export type PoliciesWritePasswordPolicyRouteParameters = {}

export type PoliciesWritePasswordPolicyRequestHeaders = {}

interface PoliciesWritePasswordPolicyParameterBodies {
  'application/json': PoliciesWritePasswordPolicyRequestSchema & { [key: string]: any }
}

export type PoliciesWritePasswordPolicyRequestParameters = PoliciesWritePasswordPolicyRequestQuery & PoliciesWritePasswordPolicyRouteParameters & PoliciesWritePasswordPolicyRequestHeaders & PoliciesWritePasswordPolicyRequestBodies['application/json']

export interface PoliciesWritePasswordPolicyOperation<STATUS extends keyof PoliciesWritePasswordPolicyResponseBodies, CONTENT_TYPE extends keyof PoliciesWritePasswordPolicyParameterBodies> extends KeqOperation {
  requestParams: PoliciesWritePasswordPolicyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PoliciesWritePasswordPolicyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PoliciesWritePasswordPolicyRequestHeaders & { [key: string]: string | number }
  requestBody: PoliciesWritePasswordPolicyParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: PoliciesWritePasswordPolicyResponseBodies[STATUS]
}

/* @anchor:file:end */
