// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PprofBlockingResponseBodies {
  200: void
}

export interface PprofBlockingRequestBodies {}

export type PprofBlockingRequestQuery = {}

export type PprofBlockingRouteParameters = {}

export type PprofBlockingRequestHeaders = {}

export type PprofBlockingRequestParameters = PprofBlockingRequestQuery & PprofBlockingRouteParameters & PprofBlockingRequestHeaders

export interface PprofBlockingOperation<STATUS extends keyof PprofBlockingResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PprofBlockingRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PprofBlockingRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PprofBlockingRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PprofBlockingResponseBodies[STATUS]
}

/* @anchor:file:end */
