// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PprofThreadCreationsResponseBodies {
  200: void
}

export interface PprofThreadCreationsRequestBodies {}

export type PprofThreadCreationsRequestQuery = {}

export type PprofThreadCreationsRouteParameters = {}

export type PprofThreadCreationsRequestHeaders = {}

export type PprofThreadCreationsRequestParameters = PprofThreadCreationsRequestQuery & PprofThreadCreationsRouteParameters & PprofThreadCreationsRequestHeaders

export interface PprofThreadCreationsOperation<STATUS extends keyof PprofThreadCreationsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PprofThreadCreationsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PprofThreadCreationsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PprofThreadCreationsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PprofThreadCreationsResponseBodies[STATUS]
}

/* @anchor:file:end */
