// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PprofMemoryAllocationsResponseBodies {
  200: void
}

export interface PprofMemoryAllocationsRequestBodies {}

export type PprofMemoryAllocationsRequestQuery = {}

export type PprofMemoryAllocationsRouteParameters = {}

export type PprofMemoryAllocationsRequestHeaders = {}

export type PprofMemoryAllocationsRequestParameters = PprofMemoryAllocationsRequestQuery & PprofMemoryAllocationsRouteParameters & PprofMemoryAllocationsRequestHeaders

export interface PprofMemoryAllocationsOperation<STATUS extends keyof PprofMemoryAllocationsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PprofMemoryAllocationsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PprofMemoryAllocationsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PprofMemoryAllocationsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PprofMemoryAllocationsResponseBodies[STATUS]
}

/* @anchor:file:end */
