// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PprofIndexResponseBodies {
  200: void
}

export interface PprofIndexRequestBodies {}

export type PprofIndexRequestQuery = {}

export type PprofIndexRouteParameters = {}

export type PprofIndexRequestHeaders = {}

export type PprofIndexRequestParameters = PprofIndexRequestQuery & PprofIndexRouteParameters & PprofIndexRequestHeaders

export interface PprofIndexOperation<STATUS extends keyof PprofIndexResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PprofIndexRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PprofIndexRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PprofIndexRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PprofIndexResponseBodies[STATUS]
}

/* @anchor:file:end */
