// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PprofMutexesResponseBodies {
  200: void
}

export interface PprofMutexesRequestBodies {}

export type PprofMutexesRequestQuery = {}

export type PprofMutexesRouteParameters = {}

export type PprofMutexesRequestHeaders = {}

export type PprofMutexesRequestParameters = PprofMutexesRequestQuery & PprofMutexesRouteParameters & PprofMutexesRequestHeaders

export interface PprofMutexesOperation<STATUS extends keyof PprofMutexesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PprofMutexesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PprofMutexesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PprofMutexesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PprofMutexesResponseBodies[STATUS]
}

/* @anchor:file:end */
