// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PprofGoroutinesResponseBodies {
  200: void
}

export interface PprofGoroutinesRequestBodies {}

export type PprofGoroutinesRequestQuery = {}

export type PprofGoroutinesRouteParameters = {}

export type PprofGoroutinesRequestHeaders = {}

export type PprofGoroutinesRequestParameters = PprofGoroutinesRequestQuery & PprofGoroutinesRouteParameters & PprofGoroutinesRequestHeaders

export interface PprofGoroutinesOperation<STATUS extends keyof PprofGoroutinesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PprofGoroutinesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PprofGoroutinesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PprofGoroutinesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PprofGoroutinesResponseBodies[STATUS]
}

/* @anchor:file:end */
