// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface PprofSymbolsResponseBodies {
  200: void
}

export interface PprofSymbolsRequestBodies {}

export type PprofSymbolsRequestQuery = {}

export type PprofSymbolsRouteParameters = {}

export type PprofSymbolsRequestHeaders = {}

export type PprofSymbolsRequestParameters = PprofSymbolsRequestQuery & PprofSymbolsRouteParameters & PprofSymbolsRequestHeaders

export interface PprofSymbolsOperation<STATUS extends keyof PprofSymbolsResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: PprofSymbolsRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: PprofSymbolsRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: PprofSymbolsRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: PprofSymbolsResponseBodies[STATUS]
}

/* @anchor:file:end */
