// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { QueryTokenCapabilitiesRequest as QueryTokenCapabilitiesRequestSchema } from '../components/schemas/query-token-capabilities-request.schema'

export interface QueryTokenCapabilitiesResponseBodies {
  200: void
}

export interface QueryTokenCapabilitiesRequestBodies {
  'application/json': QueryTokenCapabilitiesRequestSchema
}

export type QueryTokenCapabilitiesRequestQuery = {}

export type QueryTokenCapabilitiesRouteParameters = {}

export type QueryTokenCapabilitiesRequestHeaders = {}

interface QueryTokenCapabilitiesParameterBodies {
  'application/json': QueryTokenCapabilitiesRequestSchema & { [key: string]: any }
}

export type QueryTokenCapabilitiesRequestParameters = QueryTokenCapabilitiesRequestQuery & QueryTokenCapabilitiesRouteParameters & QueryTokenCapabilitiesRequestHeaders & QueryTokenCapabilitiesRequestBodies['application/json']

export interface QueryTokenCapabilitiesOperation<STATUS extends keyof QueryTokenCapabilitiesResponseBodies, CONTENT_TYPE extends keyof QueryTokenCapabilitiesParameterBodies> extends KeqOperation {
  requestParams: QueryTokenCapabilitiesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: QueryTokenCapabilitiesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: QueryTokenCapabilitiesRequestHeaders & { [key: string]: string | number }
  requestBody: QueryTokenCapabilitiesParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: QueryTokenCapabilitiesResponseBodies[STATUS]
}

/* @anchor:file:end */
