// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RateLimitQuotasWriteRequest as RateLimitQuotasWriteRequestSchema } from '../components/schemas/rate-limit-quotas-write-request.schema'

export interface RateLimitQuotasWriteResponseBodies {
  204: void
}

export interface RateLimitQuotasWriteRequestBodies {
  'application/json': RateLimitQuotasWriteRequestSchema
}

export type RateLimitQuotasWriteRequestQuery = {}

export type RateLimitQuotasWriteRouteParameters = {}

export type RateLimitQuotasWriteRequestHeaders = {}

interface RateLimitQuotasWriteParameterBodies {
  'application/json': RateLimitQuotasWriteRequestSchema & { [key: string]: any }
}

export type RateLimitQuotasWriteRequestParameters = RateLimitQuotasWriteRequestQuery & RateLimitQuotasWriteRouteParameters & RateLimitQuotasWriteRequestHeaders & RateLimitQuotasWriteRequestBodies['application/json']

export interface RateLimitQuotasWriteOperation<STATUS extends keyof RateLimitQuotasWriteResponseBodies, CONTENT_TYPE extends keyof RateLimitQuotasWriteParameterBodies> extends KeqOperation {
  requestParams: RateLimitQuotasWriteRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RateLimitQuotasWriteRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RateLimitQuotasWriteRequestHeaders & { [key: string]: string | number }
  requestBody: RateLimitQuotasWriteParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RateLimitQuotasWriteResponseBodies[STATUS]
}

/* @anchor:file:end */
