// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RateLimitQuotasConfigureRequest as RateLimitQuotasConfigureRequestSchema } from '../components/schemas/rate-limit-quotas-configure-request.schema'

export interface RateLimitQuotasConfigureResponseBodies {
  204: void
}

export interface RateLimitQuotasConfigureRequestBodies {
  'application/json': RateLimitQuotasConfigureRequestSchema
}

export type RateLimitQuotasConfigureRequestQuery = {}

export type RateLimitQuotasConfigureRouteParameters = {}

export type RateLimitQuotasConfigureRequestHeaders = {}

interface RateLimitQuotasConfigureParameterBodies {
  'application/json': RateLimitQuotasConfigureRequestSchema & { [key: string]: any }
}

export type RateLimitQuotasConfigureRequestParameters = RateLimitQuotasConfigureRequestQuery & RateLimitQuotasConfigureRouteParameters & RateLimitQuotasConfigureRequestHeaders & RateLimitQuotasConfigureRequestBodies['application/json']

export interface RateLimitQuotasConfigureOperation<STATUS extends keyof RateLimitQuotasConfigureResponseBodies, CONTENT_TYPE extends keyof RateLimitQuotasConfigureParameterBodies> extends KeqOperation {
  requestParams: RateLimitQuotasConfigureRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RateLimitQuotasConfigureRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RateLimitQuotasConfigureRequestHeaders & { [key: string]: string | number }
  requestBody: RateLimitQuotasConfigureParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RateLimitQuotasConfigureResponseBodies[STATUS]
}

/* @anchor:file:end */
