// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RateLimitQuotasReadConfigurationResponse as RateLimitQuotasReadConfigurationResponseSchema } from '../components/schemas/rate-limit-quotas-read-configuration-response.schema'

export interface RateLimitQuotasReadConfigurationResponseBodies {
  200: RateLimitQuotasReadConfigurationResponseSchema
}

export interface RateLimitQuotasReadConfigurationRequestBodies {}

export type RateLimitQuotasReadConfigurationRequestQuery = {}

export type RateLimitQuotasReadConfigurationRouteParameters = {}

export type RateLimitQuotasReadConfigurationRequestHeaders = {}

export type RateLimitQuotasReadConfigurationRequestParameters = RateLimitQuotasReadConfigurationRequestQuery & RateLimitQuotasReadConfigurationRouteParameters & RateLimitQuotasReadConfigurationRequestHeaders

export interface RateLimitQuotasReadConfigurationOperation<STATUS extends keyof RateLimitQuotasReadConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RateLimitQuotasReadConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RateLimitQuotasReadConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RateLimitQuotasReadConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RateLimitQuotasReadConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
