// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface ReadSanitizedConfigurationStateResponseBodies {
  200: void
}

export interface ReadSanitizedConfigurationStateRequestBodies {}

export type ReadSanitizedConfigurationStateRequestQuery = {}

export type ReadSanitizedConfigurationStateRouteParameters = {}

export type ReadSanitizedConfigurationStateRequestHeaders = {}

export type ReadSanitizedConfigurationStateRequestParameters = ReadSanitizedConfigurationStateRequestQuery & ReadSanitizedConfigurationStateRouteParameters & ReadSanitizedConfigurationStateRequestHeaders

export interface ReadSanitizedConfigurationStateOperation<STATUS extends keyof ReadSanitizedConfigurationStateResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: ReadSanitizedConfigurationStateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: ReadSanitizedConfigurationStateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: ReadSanitizedConfigurationStateRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: ReadSanitizedConfigurationStateResponseBodies[STATUS]
}

/* @anchor:file:end */
