// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { ReadWrappingPropertiesRequest as ReadWrappingPropertiesRequestSchema } from '../components/schemas/read-wrapping-properties-request.schema'
import type { ReadWrappingPropertiesResponse as ReadWrappingPropertiesResponseSchema } from '../components/schemas/read-wrapping-properties-response.schema'

export interface ReadWrappingPropertiesResponseBodies {
  200: ReadWrappingPropertiesResponseSchema
}

export interface ReadWrappingPropertiesRequestBodies {
  'application/json': ReadWrappingPropertiesRequestSchema
}

export type ReadWrappingPropertiesRequestQuery = {}

export type ReadWrappingPropertiesRouteParameters = {}

export type ReadWrappingPropertiesRequestHeaders = {}

interface ReadWrappingPropertiesParameterBodies {
  'application/json': ReadWrappingPropertiesRequestSchema & { [key: string]: any }
}

export type ReadWrappingPropertiesRequestParameters = ReadWrappingPropertiesRequestQuery & ReadWrappingPropertiesRouteParameters & ReadWrappingPropertiesRequestHeaders & ReadWrappingPropertiesRequestBodies['application/json']

export interface ReadWrappingPropertiesOperation<STATUS extends keyof ReadWrappingPropertiesResponseBodies, CONTENT_TYPE extends keyof ReadWrappingPropertiesParameterBodies> extends KeqOperation {
  requestParams: ReadWrappingPropertiesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: ReadWrappingPropertiesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: ReadWrappingPropertiesRequestHeaders & { [key: string]: string | number }
  requestBody: ReadWrappingPropertiesParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: ReadWrappingPropertiesResponseBodies[STATUS]
}

/* @anchor:file:end */
