// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RekeyReadBackupKeyResponse as RekeyReadBackupKeyResponseSchema } from '../components/schemas/rekey-read-backup-key-response.schema'

export interface RekeyReadBackupKeyResponseBodies {
  200: RekeyReadBackupKeyResponseSchema
}

export interface RekeyReadBackupKeyRequestBodies {}

export type RekeyReadBackupKeyRequestQuery = {}

export type RekeyReadBackupKeyRouteParameters = {}

export type RekeyReadBackupKeyRequestHeaders = {}

export type RekeyReadBackupKeyRequestParameters = RekeyReadBackupKeyRequestQuery & RekeyReadBackupKeyRouteParameters & RekeyReadBackupKeyRequestHeaders

export interface RekeyReadBackupKeyOperation<STATUS extends keyof RekeyReadBackupKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RekeyReadBackupKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RekeyReadBackupKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RekeyReadBackupKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RekeyReadBackupKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
