// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RekeyVerificationUpdateRequest as RekeyVerificationUpdateRequestSchema } from '../components/schemas/rekey-verification-update-request.schema'
import type { RekeyVerificationUpdateResponse as RekeyVerificationUpdateResponseSchema } from '../components/schemas/rekey-verification-update-response.schema'

export interface RekeyVerificationUpdateResponseBodies {
  200: RekeyVerificationUpdateResponseSchema
}

export interface RekeyVerificationUpdateRequestBodies {
  'application/json': RekeyVerificationUpdateRequestSchema
}

export type RekeyVerificationUpdateRequestQuery = {}

export type RekeyVerificationUpdateRouteParameters = {}

export type RekeyVerificationUpdateRequestHeaders = {}

interface RekeyVerificationUpdateParameterBodies {
  'application/json': RekeyVerificationUpdateRequestSchema & { [key: string]: any }
}

export type RekeyVerificationUpdateRequestParameters = RekeyVerificationUpdateRequestQuery & RekeyVerificationUpdateRouteParameters & RekeyVerificationUpdateRequestHeaders & RekeyVerificationUpdateRequestBodies['application/json']

export interface RekeyVerificationUpdateOperation<STATUS extends keyof RekeyVerificationUpdateResponseBodies, CONTENT_TYPE extends keyof RekeyVerificationUpdateParameterBodies> extends KeqOperation {
  requestParams: RekeyVerificationUpdateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RekeyVerificationUpdateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RekeyVerificationUpdateRequestHeaders & { [key: string]: string | number }
  requestBody: RekeyVerificationUpdateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RekeyVerificationUpdateResponseBodies[STATUS]
}

/* @anchor:file:end */
