// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RekeyAttemptReadProgressResponse as RekeyAttemptReadProgressResponseSchema } from '../components/schemas/rekey-attempt-read-progress-response.schema'

export interface RekeyAttemptReadProgressResponseBodies {
  200: RekeyAttemptReadProgressResponseSchema
}

export interface RekeyAttemptReadProgressRequestBodies {}

export type RekeyAttemptReadProgressRequestQuery = {}

export type RekeyAttemptReadProgressRouteParameters = {}

export type RekeyAttemptReadProgressRequestHeaders = {}

export type RekeyAttemptReadProgressRequestParameters = RekeyAttemptReadProgressRequestQuery & RekeyAttemptReadProgressRouteParameters & RekeyAttemptReadProgressRequestHeaders

export interface RekeyAttemptReadProgressOperation<STATUS extends keyof RekeyAttemptReadProgressResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RekeyAttemptReadProgressRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RekeyAttemptReadProgressRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RekeyAttemptReadProgressRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RekeyAttemptReadProgressResponseBodies[STATUS]
}

/* @anchor:file:end */
