// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RekeyAttemptUpdateRequest as RekeyAttemptUpdateRequestSchema } from '../components/schemas/rekey-attempt-update-request.schema'
import type { RekeyAttemptUpdateResponse as RekeyAttemptUpdateResponseSchema } from '../components/schemas/rekey-attempt-update-response.schema'

export interface RekeyAttemptUpdateResponseBodies {
  200: RekeyAttemptUpdateResponseSchema
}

export interface RekeyAttemptUpdateRequestBodies {
  'application/json': RekeyAttemptUpdateRequestSchema
}

export type RekeyAttemptUpdateRequestQuery = {}

export type RekeyAttemptUpdateRouteParameters = {}

export type RekeyAttemptUpdateRequestHeaders = {}

interface RekeyAttemptUpdateParameterBodies {
  'application/json': RekeyAttemptUpdateRequestSchema & { [key: string]: any }
}

export type RekeyAttemptUpdateRequestParameters = RekeyAttemptUpdateRequestQuery & RekeyAttemptUpdateRouteParameters & RekeyAttemptUpdateRequestHeaders & RekeyAttemptUpdateRequestBodies['application/json']

export interface RekeyAttemptUpdateOperation<STATUS extends keyof RekeyAttemptUpdateResponseBodies, CONTENT_TYPE extends keyof RekeyAttemptUpdateParameterBodies> extends KeqOperation {
  requestParams: RekeyAttemptUpdateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RekeyAttemptUpdateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RekeyAttemptUpdateRequestHeaders & { [key: string]: string | number }
  requestBody: RekeyAttemptUpdateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RekeyAttemptUpdateResponseBodies[STATUS]
}

/* @anchor:file:end */
