// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RemountRequest as RemountRequestSchema } from '../components/schemas/remount-request.schema'
import type { RemountResponse as RemountResponseSchema } from '../components/schemas/remount-response.schema'

export interface RemountResponseBodies {
  200: RemountResponseSchema
}

export interface RemountRequestBodies {
  'application/json': RemountRequestSchema
}

export type RemountRequestQuery = {}

export type RemountRouteParameters = {}

export type RemountRequestHeaders = {}

interface RemountParameterBodies {
  'application/json': RemountRequestSchema & { [key: string]: any }
}

export type RemountRequestParameters = RemountRequestQuery & RemountRouteParameters & RemountRequestHeaders & RemountRequestBodies['application/json']

export interface RemountOperation<STATUS extends keyof RemountResponseBodies, CONTENT_TYPE extends keyof RemountParameterBodies> extends KeqOperation {
  requestParams: RemountRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RemountRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RemountRequestHeaders & { [key: string]: string | number }
  requestBody: RemountParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RemountResponseBodies[STATUS]
}

/* @anchor:file:end */
