// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RemountStatusResponse as RemountStatusResponseSchema } from '../components/schemas/remount-status-response.schema'

export interface RemountStatusResponseBodies {
  200: RemountStatusResponseSchema
}

export interface RemountStatusRequestBodies {}

export type RemountStatusRequestQuery = {}

export type RemountStatusRouteParameters = {}

export type RemountStatusRequestHeaders = {}

export type RemountStatusRequestParameters = RemountStatusRequestQuery & RemountStatusRouteParameters & RemountStatusRequestHeaders

export interface RemountStatusOperation<STATUS extends keyof RemountStatusResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RemountStatusRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RemountStatusRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RemountStatusRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RemountStatusResponseBodies[STATUS]
}

/* @anchor:file:end */
