// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RewrapRequest as RewrapRequestSchema } from '../components/schemas/rewrap-request.schema'

export interface RewrapResponseBodies {
  200: void
}

export interface RewrapRequestBodies {
  'application/json': RewrapRequestSchema
}

export type RewrapRequestQuery = {}

export type RewrapRouteParameters = {}

export type RewrapRequestHeaders = {}

interface RewrapParameterBodies {
  'application/json': RewrapRequestSchema & { [key: string]: any }
}

export type RewrapRequestParameters = RewrapRequestQuery & RewrapRouteParameters & RewrapRequestHeaders & RewrapRequestBodies['application/json']

export interface RewrapOperation<STATUS extends keyof RewrapResponseBodies, CONTENT_TYPE extends keyof RewrapParameterBodies> extends KeqOperation {
  requestParams: RewrapRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RewrapRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RewrapRequestHeaders & { [key: string]: string | number }
  requestBody: RewrapParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RewrapResponseBodies[STATUS]
}

/* @anchor:file:end */
