// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RootTokenGenerationInitialize2Request as RootTokenGenerationInitialize2RequestSchema } from '../components/schemas/root-token-generation-initialize2-request.schema'
import type { RootTokenGenerationInitialize2Response as RootTokenGenerationInitialize2ResponseSchema } from '../components/schemas/root-token-generation-initialize2-response.schema'

export interface RootTokenGenerationInitialize_2ResponseBodies {
  200: RootTokenGenerationInitialize2ResponseSchema
}

export interface RootTokenGenerationInitialize_2RequestBodies {
  'application/json': RootTokenGenerationInitialize2RequestSchema
}

export type RootTokenGenerationInitialize_2RequestQuery = {}

export type RootTokenGenerationInitialize_2RouteParameters = {}

export type RootTokenGenerationInitialize_2RequestHeaders = {}

interface RootTokenGenerationInitialize_2ParameterBodies {
  'application/json': RootTokenGenerationInitialize2RequestSchema & { [key: string]: any }
}

export type RootTokenGenerationInitialize_2RequestParameters = RootTokenGenerationInitialize_2RequestQuery & RootTokenGenerationInitialize_2RouteParameters & RootTokenGenerationInitialize_2RequestHeaders & RootTokenGenerationInitialize_2RequestBodies['application/json']

export interface RootTokenGenerationInitialize_2Operation<STATUS extends keyof RootTokenGenerationInitialize_2ResponseBodies, CONTENT_TYPE extends keyof RootTokenGenerationInitialize_2ParameterBodies> extends KeqOperation {
  requestParams: RootTokenGenerationInitialize_2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RootTokenGenerationInitialize_2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RootTokenGenerationInitialize_2RequestHeaders & { [key: string]: string | number }
  requestBody: RootTokenGenerationInitialize_2ParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RootTokenGenerationInitialize_2ResponseBodies[STATUS]
}

/* @anchor:file:end */
