// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RootTokenGenerationReadProgress2Response as RootTokenGenerationReadProgress2ResponseSchema } from '../components/schemas/root-token-generation-read-progress2-response.schema'

export interface RootTokenGenerationReadProgress2ResponseBodies {
  200: RootTokenGenerationReadProgress2ResponseSchema
}

export interface RootTokenGenerationReadProgress2RequestBodies {}

export type RootTokenGenerationReadProgress2RequestQuery = {}

export type RootTokenGenerationReadProgress2RouteParameters = {}

export type RootTokenGenerationReadProgress2RequestHeaders = {}

export type RootTokenGenerationReadProgress2RequestParameters = RootTokenGenerationReadProgress2RequestQuery & RootTokenGenerationReadProgress2RouteParameters & RootTokenGenerationReadProgress2RequestHeaders

export interface RootTokenGenerationReadProgress2Operation<STATUS extends keyof RootTokenGenerationReadProgress2ResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RootTokenGenerationReadProgress2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RootTokenGenerationReadProgress2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RootTokenGenerationReadProgress2RequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RootTokenGenerationReadProgress2ResponseBodies[STATUS]
}

/* @anchor:file:end */
