// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RootTokenGenerationReadProgressResponse as RootTokenGenerationReadProgressResponseSchema } from '../components/schemas/root-token-generation-read-progress-response.schema'

export interface RootTokenGenerationReadProgressResponseBodies {
  200: RootTokenGenerationReadProgressResponseSchema
}

export interface RootTokenGenerationReadProgressRequestBodies {}

export type RootTokenGenerationReadProgressRequestQuery = {}

export type RootTokenGenerationReadProgressRouteParameters = {}

export type RootTokenGenerationReadProgressRequestHeaders = {}

export type RootTokenGenerationReadProgressRequestParameters = RootTokenGenerationReadProgressRequestQuery & RootTokenGenerationReadProgressRouteParameters & RootTokenGenerationReadProgressRequestHeaders

export interface RootTokenGenerationReadProgressOperation<STATUS extends keyof RootTokenGenerationReadProgressResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RootTokenGenerationReadProgressRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RootTokenGenerationReadProgressRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RootTokenGenerationReadProgressRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RootTokenGenerationReadProgressResponseBodies[STATUS]
}

/* @anchor:file:end */
