// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface RootTokenGenerationCancel_2ResponseBodies {
  204: void
}

export interface RootTokenGenerationCancel_2RequestBodies {}

export type RootTokenGenerationCancel_2RequestQuery = {}

export type RootTokenGenerationCancel_2RouteParameters = {}

export type RootTokenGenerationCancel_2RequestHeaders = {}

export type RootTokenGenerationCancel_2RequestParameters = RootTokenGenerationCancel_2RequestQuery & RootTokenGenerationCancel_2RouteParameters & RootTokenGenerationCancel_2RequestHeaders

export interface RootTokenGenerationCancel_2Operation<STATUS extends keyof RootTokenGenerationCancel_2ResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RootTokenGenerationCancel_2RouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RootTokenGenerationCancel_2RequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RootTokenGenerationCancel_2RequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RootTokenGenerationCancel_2ResponseBodies[STATUS]
}

/* @anchor:file:end */
