// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RotateVerificationUpdateRotateRecoveryVerifyRequest as RotateVerificationUpdateRotateRecoveryVerifyRequestSchema } from '../components/schemas/rotate-verification-update-rotate-recovery-verify-request.schema'
import type { RotateVerificationUpdateRotateRecoveryVerifyResponse as RotateVerificationUpdateRotateRecoveryVerifyResponseSchema } from '../components/schemas/rotate-verification-update-rotate-recovery-verify-response.schema'

export interface RotateVerificationUpdateRotateRecoveryVerifyResponseBodies {
  200: RotateVerificationUpdateRotateRecoveryVerifyResponseSchema
}

export interface RotateVerificationUpdateRotateRecoveryVerifyRequestBodies {
  'application/json': RotateVerificationUpdateRotateRecoveryVerifyRequestSchema
}

export type RotateVerificationUpdateRotateRecoveryVerifyRequestQuery = {}

export type RotateVerificationUpdateRotateRecoveryVerifyRouteParameters = {}

export type RotateVerificationUpdateRotateRecoveryVerifyRequestHeaders = {}

interface RotateVerificationUpdateRotateRecoveryVerifyParameterBodies {
  'application/json': RotateVerificationUpdateRotateRecoveryVerifyRequestSchema & { [key: string]: any }
}

export type RotateVerificationUpdateRotateRecoveryVerifyRequestParameters = RotateVerificationUpdateRotateRecoveryVerifyRequestQuery & RotateVerificationUpdateRotateRecoveryVerifyRouteParameters & RotateVerificationUpdateRotateRecoveryVerifyRequestHeaders & RotateVerificationUpdateRotateRecoveryVerifyRequestBodies['application/json']

export interface RotateVerificationUpdateRotateRecoveryVerifyOperation<STATUS extends keyof RotateVerificationUpdateRotateRecoveryVerifyResponseBodies, CONTENT_TYPE extends keyof RotateVerificationUpdateRotateRecoveryVerifyParameterBodies> extends KeqOperation {
  requestParams: RotateVerificationUpdateRotateRecoveryVerifyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateVerificationUpdateRotateRecoveryVerifyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateVerificationUpdateRotateRecoveryVerifyRequestHeaders & { [key: string]: string | number }
  requestBody: RotateVerificationUpdateRotateRecoveryVerifyParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RotateVerificationUpdateRotateRecoveryVerifyResponseBodies[STATUS]
}

/* @anchor:file:end */
