// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RotateAttemptUpdateRotateRecoveryUpdateRequest as RotateAttemptUpdateRotateRecoveryUpdateRequestSchema } from '../components/schemas/rotate-attempt-update-rotate-recovery-update-request.schema'
import type { RotateAttemptUpdateRotateRecoveryUpdateResponse as RotateAttemptUpdateRotateRecoveryUpdateResponseSchema } from '../components/schemas/rotate-attempt-update-rotate-recovery-update-response.schema'

export interface RotateAttemptUpdateRotateRecoveryUpdateResponseBodies {
  200: RotateAttemptUpdateRotateRecoveryUpdateResponseSchema
}

export interface RotateAttemptUpdateRotateRecoveryUpdateRequestBodies {
  'application/json': RotateAttemptUpdateRotateRecoveryUpdateRequestSchema
}

export type RotateAttemptUpdateRotateRecoveryUpdateRequestQuery = {}

export type RotateAttemptUpdateRotateRecoveryUpdateRouteParameters = {}

export type RotateAttemptUpdateRotateRecoveryUpdateRequestHeaders = {}

interface RotateAttemptUpdateRotateRecoveryUpdateParameterBodies {
  'application/json': RotateAttemptUpdateRotateRecoveryUpdateRequestSchema & { [key: string]: any }
}

export type RotateAttemptUpdateRotateRecoveryUpdateRequestParameters = RotateAttemptUpdateRotateRecoveryUpdateRequestQuery & RotateAttemptUpdateRotateRecoveryUpdateRouteParameters & RotateAttemptUpdateRotateRecoveryUpdateRequestHeaders & RotateAttemptUpdateRotateRecoveryUpdateRequestBodies['application/json']

export interface RotateAttemptUpdateRotateRecoveryUpdateOperation<STATUS extends keyof RotateAttemptUpdateRotateRecoveryUpdateResponseBodies, CONTENT_TYPE extends keyof RotateAttemptUpdateRotateRecoveryUpdateParameterBodies> extends KeqOperation {
  requestParams: RotateAttemptUpdateRotateRecoveryUpdateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateAttemptUpdateRotateRecoveryUpdateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateAttemptUpdateRotateRecoveryUpdateRequestHeaders & { [key: string]: string | number }
  requestBody: RotateAttemptUpdateRotateRecoveryUpdateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RotateAttemptUpdateRotateRecoveryUpdateResponseBodies[STATUS]
}

/* @anchor:file:end */
