// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RotateVerificationCancelResponse as RotateVerificationCancelResponseSchema } from '../components/schemas/rotate-verification-cancel-response.schema'

export interface RotateVerificationCancelResponseBodies {
  200: RotateVerificationCancelResponseSchema
}

export interface RotateVerificationCancelRequestBodies {}

export type RotateVerificationCancelRequestQuery = {}

export type RotateVerificationCancelRouteParameters = {}

export type RotateVerificationCancelRequestHeaders = {}

export type RotateVerificationCancelRequestParameters = RotateVerificationCancelRequestQuery & RotateVerificationCancelRouteParameters & RotateVerificationCancelRequestHeaders

export interface RotateVerificationCancelOperation<STATUS extends keyof RotateVerificationCancelResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RotateVerificationCancelRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateVerificationCancelRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateVerificationCancelRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RotateVerificationCancelResponseBodies[STATUS]
}

/* @anchor:file:end */
