// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RotateVerificationReadRotateRecoveryVerifyResponse as RotateVerificationReadRotateRecoveryVerifyResponseSchema } from '../components/schemas/rotate-verification-read-rotate-recovery-verify-response.schema'

export interface RotateVerificationReadRotateRecoveryVerifyResponseBodies {
  200: RotateVerificationReadRotateRecoveryVerifyResponseSchema
}

export interface RotateVerificationReadRotateRecoveryVerifyRequestBodies {}

export type RotateVerificationReadRotateRecoveryVerifyRequestQuery = {}

export type RotateVerificationReadRotateRecoveryVerifyRouteParameters = {}

export type RotateVerificationReadRotateRecoveryVerifyRequestHeaders = {}

export type RotateVerificationReadRotateRecoveryVerifyRequestParameters = RotateVerificationReadRotateRecoveryVerifyRequestQuery & RotateVerificationReadRotateRecoveryVerifyRouteParameters & RotateVerificationReadRotateRecoveryVerifyRequestHeaders

export interface RotateVerificationReadRotateRecoveryVerifyOperation<STATUS extends keyof RotateVerificationReadRotateRecoveryVerifyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RotateVerificationReadRotateRecoveryVerifyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateVerificationReadRotateRecoveryVerifyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateVerificationReadRotateRecoveryVerifyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RotateVerificationReadRotateRecoveryVerifyResponseBodies[STATUS]
}

/* @anchor:file:end */
