// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface RotateAttemptCancelRotateRecoveryInitResponseBodies {
  204: void
}

export interface RotateAttemptCancelRotateRecoveryInitRequestBodies {}

export type RotateAttemptCancelRotateRecoveryInitRequestQuery = {}

export type RotateAttemptCancelRotateRecoveryInitRouteParameters = {}

export type RotateAttemptCancelRotateRecoveryInitRequestHeaders = {}

export type RotateAttemptCancelRotateRecoveryInitRequestParameters = RotateAttemptCancelRotateRecoveryInitRequestQuery & RotateAttemptCancelRotateRecoveryInitRouteParameters & RotateAttemptCancelRotateRecoveryInitRequestHeaders

export interface RotateAttemptCancelRotateRecoveryInitOperation<STATUS extends keyof RotateAttemptCancelRotateRecoveryInitResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RotateAttemptCancelRotateRecoveryInitRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateAttemptCancelRotateRecoveryInitRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateAttemptCancelRotateRecoveryInitRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RotateAttemptCancelRotateRecoveryInitResponseBodies[STATUS]
}

/* @anchor:file:end */
