// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface RotateDeleteRotateRecoveryBackupResponseBodies {
  204: void
}

export interface RotateDeleteRotateRecoveryBackupRequestBodies {}

export type RotateDeleteRotateRecoveryBackupRequestQuery = {}

export type RotateDeleteRotateRecoveryBackupRouteParameters = {}

export type RotateDeleteRotateRecoveryBackupRequestHeaders = {}

export type RotateDeleteRotateRecoveryBackupRequestParameters = RotateDeleteRotateRecoveryBackupRequestQuery & RotateDeleteRotateRecoveryBackupRouteParameters & RotateDeleteRotateRecoveryBackupRequestHeaders

export interface RotateDeleteRotateRecoveryBackupOperation<STATUS extends keyof RotateDeleteRotateRecoveryBackupResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RotateDeleteRotateRecoveryBackupRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateDeleteRotateRecoveryBackupRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateDeleteRotateRecoveryBackupRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RotateDeleteRotateRecoveryBackupResponseBodies[STATUS]
}

/* @anchor:file:end */
