// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RotateAttemptInitializeRotateRecoveryInitRequest as RotateAttemptInitializeRotateRecoveryInitRequestSchema } from '../components/schemas/rotate-attempt-initialize-rotate-recovery-init-request.schema'
import type { RotateAttemptInitializeRotateRecoveryInitResponse as RotateAttemptInitializeRotateRecoveryInitResponseSchema } from '../components/schemas/rotate-attempt-initialize-rotate-recovery-init-response.schema'

export interface RotateAttemptInitializeRotateRecoveryInitResponseBodies {
  200: RotateAttemptInitializeRotateRecoveryInitResponseSchema
}

export interface RotateAttemptInitializeRotateRecoveryInitRequestBodies {
  'application/json': RotateAttemptInitializeRotateRecoveryInitRequestSchema
}

export type RotateAttemptInitializeRotateRecoveryInitRequestQuery = {}

export type RotateAttemptInitializeRotateRecoveryInitRouteParameters = {}

export type RotateAttemptInitializeRotateRecoveryInitRequestHeaders = {}

interface RotateAttemptInitializeRotateRecoveryInitParameterBodies {
  'application/json': RotateAttemptInitializeRotateRecoveryInitRequestSchema & { [key: string]: any }
}

export type RotateAttemptInitializeRotateRecoveryInitRequestParameters = RotateAttemptInitializeRotateRecoveryInitRequestQuery & RotateAttemptInitializeRotateRecoveryInitRouteParameters & RotateAttemptInitializeRotateRecoveryInitRequestHeaders & RotateAttemptInitializeRotateRecoveryInitRequestBodies['application/json']

export interface RotateAttemptInitializeRotateRecoveryInitOperation<STATUS extends keyof RotateAttemptInitializeRotateRecoveryInitResponseBodies, CONTENT_TYPE extends keyof RotateAttemptInitializeRotateRecoveryInitParameterBodies> extends KeqOperation {
  requestParams: RotateAttemptInitializeRotateRecoveryInitRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateAttemptInitializeRotateRecoveryInitRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateAttemptInitializeRotateRecoveryInitRequestHeaders & { [key: string]: string | number }
  requestBody: RotateAttemptInitializeRotateRecoveryInitParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RotateAttemptInitializeRotateRecoveryInitResponseBodies[STATUS]
}

/* @anchor:file:end */
