// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RotateAttemptReadRotateRecoveryInitResponse as RotateAttemptReadRotateRecoveryInitResponseSchema } from '../components/schemas/rotate-attempt-read-rotate-recovery-init-response.schema'

export interface RotateAttemptReadRotateRecoveryInitResponseBodies {
  200: RotateAttemptReadRotateRecoveryInitResponseSchema
}

export interface RotateAttemptReadRotateRecoveryInitRequestBodies {}

export type RotateAttemptReadRotateRecoveryInitRequestQuery = {}

export type RotateAttemptReadRotateRecoveryInitRouteParameters = {}

export type RotateAttemptReadRotateRecoveryInitRequestHeaders = {}

export type RotateAttemptReadRotateRecoveryInitRequestParameters = RotateAttemptReadRotateRecoveryInitRequestQuery & RotateAttemptReadRotateRecoveryInitRouteParameters & RotateAttemptReadRotateRecoveryInitRequestHeaders

export interface RotateAttemptReadRotateRecoveryInitOperation<STATUS extends keyof RotateAttemptReadRotateRecoveryInitResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RotateAttemptReadRotateRecoveryInitRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateAttemptReadRotateRecoveryInitRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateAttemptReadRotateRecoveryInitRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RotateAttemptReadRotateRecoveryInitResponseBodies[STATUS]
}

/* @anchor:file:end */
