// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { RotateAttemptUpdateRequest as RotateAttemptUpdateRequestSchema } from '../components/schemas/rotate-attempt-update-request.schema'
import type { RotateAttemptUpdateResponse as RotateAttemptUpdateResponseSchema } from '../components/schemas/rotate-attempt-update-response.schema'

export interface RotateAttemptUpdateResponseBodies {
  200: RotateAttemptUpdateResponseSchema
}

export interface RotateAttemptUpdateRequestBodies {
  'application/json': RotateAttemptUpdateRequestSchema
}

export type RotateAttemptUpdateRequestQuery = {}

export type RotateAttemptUpdateRouteParameters = {}

export type RotateAttemptUpdateRequestHeaders = {}

interface RotateAttemptUpdateParameterBodies {
  'application/json': RotateAttemptUpdateRequestSchema & { [key: string]: any }
}

export type RotateAttemptUpdateRequestParameters = RotateAttemptUpdateRequestQuery & RotateAttemptUpdateRouteParameters & RotateAttemptUpdateRequestHeaders & RotateAttemptUpdateRequestBodies['application/json']

export interface RotateAttemptUpdateOperation<STATUS extends keyof RotateAttemptUpdateResponseBodies, CONTENT_TYPE extends keyof RotateAttemptUpdateParameterBodies> extends KeqOperation {
  requestParams: RotateAttemptUpdateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateAttemptUpdateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateAttemptUpdateRequestHeaders & { [key: string]: string | number }
  requestBody: RotateAttemptUpdateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: RotateAttemptUpdateResponseBodies[STATUS]
}

/* @anchor:file:end */
