// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface RotateDeleteBackupKeyResponseBodies {
  204: void
}

export interface RotateDeleteBackupKeyRequestBodies {}

export type RotateDeleteBackupKeyRequestQuery = {}

export type RotateDeleteBackupKeyRouteParameters = {}

export type RotateDeleteBackupKeyRequestHeaders = {}

export type RotateDeleteBackupKeyRequestParameters = RotateDeleteBackupKeyRequestQuery & RotateDeleteBackupKeyRouteParameters & RotateDeleteBackupKeyRequestHeaders

export interface RotateDeleteBackupKeyOperation<STATUS extends keyof RotateDeleteBackupKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: RotateDeleteBackupKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: RotateDeleteBackupKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: RotateDeleteBackupKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: RotateDeleteBackupKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
