// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { SealStatusResponse as SealStatusResponseSchema } from '../components/schemas/seal-status-response.schema'

export interface SealStatusResponseBodies {
  200: SealStatusResponseSchema
}

export interface SealStatusRequestBodies {}

export type SealStatusRequestQuery = {}

export type SealStatusRouteParameters = {}

export type SealStatusRequestHeaders = {}

export type SealStatusRequestParameters = SealStatusRequestQuery & SealStatusRouteParameters & SealStatusRequestHeaders

export interface SealStatusOperation<STATUS extends keyof SealStatusResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: SealStatusRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: SealStatusRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: SealStatusRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: SealStatusResponseBodies[STATUS]
}

/* @anchor:file:end */
