// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface SealResponseBodies {
  204: void
}

export interface SealRequestBodies {}

export type SealRequestQuery = {}

export type SealRouteParameters = {}

export type SealRequestHeaders = {}

export type SealRequestParameters = SealRequestQuery & SealRouteParameters & SealRequestHeaders

export interface SealOperation<STATUS extends keyof SealResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: SealRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: SealRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: SealRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: SealResponseBodies[STATUS]
}

/* @anchor:file:end */
