// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface StepDownLeaderResponseBodies {
  204: void
}

export interface StepDownLeaderRequestBodies {}

export type StepDownLeaderRequestQuery = {}

export type StepDownLeaderRouteParameters = {}

export type StepDownLeaderRequestHeaders = {}

export type StepDownLeaderRequestParameters = StepDownLeaderRequestQuery & StepDownLeaderRouteParameters & StepDownLeaderRequestHeaders

export interface StepDownLeaderOperation<STATUS extends keyof StepDownLeaderResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: StepDownLeaderRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: StepDownLeaderRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: StepDownLeaderRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: StepDownLeaderResponseBodies[STATUS]
}

/* @anchor:file:end */
