// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface SystemListPoliciesDetailedAclNameResponseBodies {
  200: void
}

export interface SystemListPoliciesDetailedAclNameRequestBodies {}

export type SystemListPoliciesDetailedAclNameRequestQuery = {
  list: 'true'
}

export type SystemListPoliciesDetailedAclNameRouteParameters = {}

export type SystemListPoliciesDetailedAclNameRequestHeaders = {}

export type SystemListPoliciesDetailedAclNameRequestParameters = SystemListPoliciesDetailedAclNameRequestQuery & SystemListPoliciesDetailedAclNameRouteParameters & SystemListPoliciesDetailedAclNameRequestHeaders

export interface SystemListPoliciesDetailedAclNameOperation<STATUS extends keyof SystemListPoliciesDetailedAclNameResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: SystemListPoliciesDetailedAclNameRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: SystemListPoliciesDetailedAclNameRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: SystemListPoliciesDetailedAclNameRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: SystemListPoliciesDetailedAclNameResponseBodies[STATUS]
}

/* @anchor:file:end */
