// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface SystemListPoliciesDetailedAclResponseBodies {
  200: void
}

export interface SystemListPoliciesDetailedAclRequestBodies {}

export type SystemListPoliciesDetailedAclRequestQuery = {
  list: 'true'
}

export type SystemListPoliciesDetailedAclRouteParameters = {}

export type SystemListPoliciesDetailedAclRequestHeaders = {}

export type SystemListPoliciesDetailedAclRequestParameters = SystemListPoliciesDetailedAclRequestQuery & SystemListPoliciesDetailedAclRouteParameters & SystemListPoliciesDetailedAclRequestHeaders

export interface SystemListPoliciesDetailedAclOperation<STATUS extends keyof SystemListPoliciesDetailedAclResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: SystemListPoliciesDetailedAclRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: SystemListPoliciesDetailedAclRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: SystemListPoliciesDetailedAclRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: SystemListPoliciesDetailedAclResponseBodies[STATUS]
}

/* @anchor:file:end */
