// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenLookupResponse as TokenLookupResponseSchema } from '../components/schemas/token-lookup-response.schema'

export interface TokenLookUpSelfGetResponseBodies {
  200: TokenLookupResponseSchema
}

export interface TokenLookUpSelfGetRequestBodies {}

export type TokenLookUpSelfGetRequestQuery = {}

export type TokenLookUpSelfGetRouteParameters = {}

export type TokenLookUpSelfGetRequestHeaders = {}

export type TokenLookUpSelfGetRequestParameters = TokenLookUpSelfGetRequestQuery & TokenLookUpSelfGetRouteParameters & TokenLookUpSelfGetRequestHeaders

export interface TokenLookUpSelfGetOperation<STATUS extends keyof TokenLookUpSelfGetResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TokenLookUpSelfGetRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenLookUpSelfGetRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenLookUpSelfGetRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TokenLookUpSelfGetResponseBodies[STATUS]
}

/* @anchor:file:end */
