// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenLookUpUpdateRequest as TokenLookUpUpdateRequestSchema } from '../components/schemas/token-look-up-update-request.schema'
import type { TokenLookupResponse as TokenLookupResponseSchema } from '../components/schemas/token-lookup-response.schema'

export interface TokenLookUpUpdateResponseBodies {
  200: TokenLookupResponseSchema
}

export interface TokenLookUpUpdateRequestBodies {
  'application/json': TokenLookUpUpdateRequestSchema
}

export type TokenLookUpUpdateRequestQuery = {}

export type TokenLookUpUpdateRouteParameters = {}

export type TokenLookUpUpdateRequestHeaders = {}

interface TokenLookUpUpdateParameterBodies {
  'application/json': TokenLookUpUpdateRequestSchema & { [key: string]: any }
}

export type TokenLookUpUpdateRequestParameters = TokenLookUpUpdateRequestQuery & TokenLookUpUpdateRouteParameters & TokenLookUpUpdateRequestHeaders & TokenLookUpUpdateRequestBodies['application/json']

export interface TokenLookUpUpdateOperation<STATUS extends keyof TokenLookUpUpdateResponseBodies, CONTENT_TYPE extends keyof TokenLookUpUpdateParameterBodies> extends KeqOperation {
  requestParams: TokenLookUpUpdateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenLookUpUpdateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenLookUpUpdateRequestHeaders & { [key: string]: string | number }
  requestBody: TokenLookUpUpdateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenLookUpUpdateResponseBodies[STATUS]
}

/* @anchor:file:end */
