// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenWriteRoleRequest as TokenWriteRoleRequestSchema } from '../components/schemas/token-write-role-request.schema'

export interface TokenWriteRoleResponseBodies {
  200: void
}

export interface TokenWriteRoleRequestBodies {
  'application/json': TokenWriteRoleRequestSchema
}

export type TokenWriteRoleRequestQuery = {}

export type TokenWriteRoleRouteParameters = {}

export type TokenWriteRoleRequestHeaders = {}

interface TokenWriteRoleParameterBodies {
  'application/json': TokenWriteRoleRequestSchema & { [key: string]: any }
}

export type TokenWriteRoleRequestParameters = TokenWriteRoleRequestQuery & TokenWriteRoleRouteParameters & TokenWriteRoleRequestHeaders & TokenWriteRoleRequestBodies['application/json']

export interface TokenWriteRoleOperation<STATUS extends keyof TokenWriteRoleResponseBodies, CONTENT_TYPE extends keyof TokenWriteRoleParameterBodies> extends KeqOperation {
  requestParams: TokenWriteRoleRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenWriteRoleRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenWriteRoleRequestHeaders & { [key: string]: string | number }
  requestBody: TokenWriteRoleParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenWriteRoleResponseBodies[STATUS]
}

/* @anchor:file:end */
