// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TokenRevokeSelfResponseBodies {
  200: void
}

export interface TokenRevokeSelfRequestBodies {}

export type TokenRevokeSelfRequestQuery = {}

export type TokenRevokeSelfRouteParameters = {}

export type TokenRevokeSelfRequestHeaders = {}

export type TokenRevokeSelfRequestParameters = TokenRevokeSelfRequestQuery & TokenRevokeSelfRouteParameters & TokenRevokeSelfRequestHeaders

export interface TokenRevokeSelfOperation<STATUS extends keyof TokenRevokeSelfResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TokenRevokeSelfRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenRevokeSelfRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenRevokeSelfRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TokenRevokeSelfResponseBodies[STATUS]
}

/* @anchor:file:end */
