// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenLookUpSelfUpdateRequest as TokenLookUpSelfUpdateRequestSchema } from '../components/schemas/token-look-up-self-update-request.schema'
import type { TokenLookupResponse as TokenLookupResponseSchema } from '../components/schemas/token-lookup-response.schema'

export interface TokenLookUpSelfUpdateResponseBodies {
  200: TokenLookupResponseSchema
}

export interface TokenLookUpSelfUpdateRequestBodies {
  'application/json': TokenLookUpSelfUpdateRequestSchema
}

export type TokenLookUpSelfUpdateRequestQuery = {}

export type TokenLookUpSelfUpdateRouteParameters = {}

export type TokenLookUpSelfUpdateRequestHeaders = {}

interface TokenLookUpSelfUpdateParameterBodies {
  'application/json': TokenLookUpSelfUpdateRequestSchema & { [key: string]: any }
}

export type TokenLookUpSelfUpdateRequestParameters = TokenLookUpSelfUpdateRequestQuery & TokenLookUpSelfUpdateRouteParameters & TokenLookUpSelfUpdateRequestHeaders & TokenLookUpSelfUpdateRequestBodies['application/json']

export interface TokenLookUpSelfUpdateOperation<STATUS extends keyof TokenLookUpSelfUpdateResponseBodies, CONTENT_TYPE extends keyof TokenLookUpSelfUpdateParameterBodies> extends KeqOperation {
  requestParams: TokenLookUpSelfUpdateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenLookUpSelfUpdateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenLookUpSelfUpdateRequestHeaders & { [key: string]: string | number }
  requestBody: TokenLookUpSelfUpdateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenLookUpSelfUpdateResponseBodies[STATUS]
}

/* @anchor:file:end */
