// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenLookupResponse as TokenLookupResponseSchema } from '../components/schemas/token-lookup-response.schema'

export interface TokenLookUpGetResponseBodies {
  200: TokenLookupResponseSchema
}

export interface TokenLookUpGetRequestBodies {}

export type TokenLookUpGetRequestQuery = {}

export type TokenLookUpGetRouteParameters = {}

export type TokenLookUpGetRequestHeaders = {}

export type TokenLookUpGetRequestParameters = TokenLookUpGetRequestQuery & TokenLookUpGetRouteParameters & TokenLookUpGetRequestHeaders

export interface TokenLookUpGetOperation<STATUS extends keyof TokenLookUpGetResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TokenLookUpGetRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenLookUpGetRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenLookUpGetRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TokenLookUpGetResponseBodies[STATUS]
}

/* @anchor:file:end */
