// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenRenewRequest as TokenRenewRequestSchema } from '../components/schemas/token-renew-request.schema'

export interface TokenRenewResponseBodies {
  200: void
}

export interface TokenRenewRequestBodies {
  'application/json': TokenRenewRequestSchema
}

export type TokenRenewRequestQuery = {}

export type TokenRenewRouteParameters = {}

export type TokenRenewRequestHeaders = {}

interface TokenRenewParameterBodies {
  'application/json': TokenRenewRequestSchema & { [key: string]: any }
}

export type TokenRenewRequestParameters = TokenRenewRequestQuery & TokenRenewRouteParameters & TokenRenewRequestHeaders & TokenRenewRequestBodies['application/json']

export interface TokenRenewOperation<STATUS extends keyof TokenRenewResponseBodies, CONTENT_TYPE extends keyof TokenRenewParameterBodies> extends KeqOperation {
  requestParams: TokenRenewRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenRenewRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenRenewRequestHeaders & { [key: string]: string | number }
  requestBody: TokenRenewParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenRenewResponseBodies[STATUS]
}

/* @anchor:file:end */
