// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenRenewSelfRequest as TokenRenewSelfRequestSchema } from '../components/schemas/token-renew-self-request.schema'

export interface TokenRenewSelfResponseBodies {
  200: void
}

export interface TokenRenewSelfRequestBodies {
  'application/json': TokenRenewSelfRequestSchema
}

export type TokenRenewSelfRequestQuery = {}

export type TokenRenewSelfRouteParameters = {}

export type TokenRenewSelfRequestHeaders = {}

interface TokenRenewSelfParameterBodies {
  'application/json': TokenRenewSelfRequestSchema & { [key: string]: any }
}

export type TokenRenewSelfRequestParameters = TokenRenewSelfRequestQuery & TokenRenewSelfRouteParameters & TokenRenewSelfRequestHeaders & TokenRenewSelfRequestBodies['application/json']

export interface TokenRenewSelfOperation<STATUS extends keyof TokenRenewSelfResponseBodies, CONTENT_TYPE extends keyof TokenRenewSelfParameterBodies> extends KeqOperation {
  requestParams: TokenRenewSelfRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenRenewSelfRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenRenewSelfRequestHeaders & { [key: string]: string | number }
  requestBody: TokenRenewSelfParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenRenewSelfResponseBodies[STATUS]
}

/* @anchor:file:end */
