// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TokenListRolesResponseBodies {
  200: void
}

export interface TokenListRolesRequestBodies {}

export type TokenListRolesRequestQuery = {
  list: ('true')
}

export type TokenListRolesRouteParameters = {}

export type TokenListRolesRequestHeaders = {}

export type TokenListRolesRequestParameters = TokenListRolesRequestQuery & TokenListRolesRouteParameters & TokenListRolesRequestHeaders

export interface TokenListRolesOperation<STATUS extends keyof TokenListRolesResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TokenListRolesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenListRolesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenListRolesRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TokenListRolesResponseBodies[STATUS]
}

/* @anchor:file:end */
