// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenLookUpByAccessorRequest as TokenLookUpByAccessorRequestSchema } from '../components/schemas/token-look-up-by-accessor-request.schema'
import type { TokenLookupResponse as TokenLookupResponseSchema } from '../components/schemas/token-lookup-response.schema'

export interface TokenLookUpByAccessorResponseBodies {
  200: TokenLookupResponseSchema
}

export interface TokenLookUpByAccessorRequestBodies {
  'application/json': TokenLookUpByAccessorRequestSchema
}

export type TokenLookUpByAccessorRequestQuery = {}

export type TokenLookUpByAccessorRouteParameters = {}

export type TokenLookUpByAccessorRequestHeaders = {}

interface TokenLookUpByAccessorParameterBodies {
  'application/json': TokenLookUpByAccessorRequestSchema & { [key: string]: any }
}

export type TokenLookUpByAccessorRequestParameters = TokenLookUpByAccessorRequestQuery & TokenLookUpByAccessorRouteParameters & TokenLookUpByAccessorRequestHeaders & TokenLookUpByAccessorRequestBodies['application/json']

export interface TokenLookUpByAccessorOperation<STATUS extends keyof TokenLookUpByAccessorResponseBodies, CONTENT_TYPE extends keyof TokenLookUpByAccessorParameterBodies> extends KeqOperation {
  requestParams: TokenLookUpByAccessorRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenLookUpByAccessorRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenLookUpByAccessorRequestHeaders & { [key: string]: string | number }
  requestBody: TokenLookUpByAccessorParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenLookUpByAccessorResponseBodies[STATUS]
}

/* @anchor:file:end */
