// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenCreateRequest as TokenCreateRequestSchema } from '../components/schemas/token-create-request.schema'

export interface TokenCreateResponseBodies {
  200: void
}

export interface TokenCreateRequestBodies {
  'application/json': TokenCreateRequestSchema
}

export type TokenCreateRequestQuery = {}

export type TokenCreateRouteParameters = {}

export type TokenCreateRequestHeaders = {}

interface TokenCreateParameterBodies {
  'application/json': TokenCreateRequestSchema & { [key: string]: any }
}

export type TokenCreateRequestParameters = TokenCreateRequestQuery & TokenCreateRouteParameters & TokenCreateRequestHeaders & TokenCreateRequestBodies['application/json']

export interface TokenCreateOperation<STATUS extends keyof TokenCreateResponseBodies, CONTENT_TYPE extends keyof TokenCreateParameterBodies> extends KeqOperation {
  requestParams: TokenCreateRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenCreateRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenCreateRequestHeaders & { [key: string]: string | number }
  requestBody: TokenCreateParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenCreateResponseBodies[STATUS]
}

/* @anchor:file:end */
