// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenCreateOrphanRequest as TokenCreateOrphanRequestSchema } from '../components/schemas/token-create-orphan-request.schema'

export interface TokenCreateOrphanResponseBodies {
  200: void
}

export interface TokenCreateOrphanRequestBodies {
  'application/json': TokenCreateOrphanRequestSchema
}

export type TokenCreateOrphanRequestQuery = {}

export type TokenCreateOrphanRouteParameters = {}

export type TokenCreateOrphanRequestHeaders = {}

interface TokenCreateOrphanParameterBodies {
  'application/json': TokenCreateOrphanRequestSchema & { [key: string]: any }
}

export type TokenCreateOrphanRequestParameters = TokenCreateOrphanRequestQuery & TokenCreateOrphanRouteParameters & TokenCreateOrphanRequestHeaders & TokenCreateOrphanRequestBodies['application/json']

export interface TokenCreateOrphanOperation<STATUS extends keyof TokenCreateOrphanResponseBodies, CONTENT_TYPE extends keyof TokenCreateOrphanParameterBodies> extends KeqOperation {
  requestParams: TokenCreateOrphanRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenCreateOrphanRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenCreateOrphanRequestHeaders & { [key: string]: string | number }
  requestBody: TokenCreateOrphanParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenCreateOrphanResponseBodies[STATUS]
}

/* @anchor:file:end */
