// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TokenRevokeOrphanRequest as TokenRevokeOrphanRequestSchema } from '../components/schemas/token-revoke-orphan-request.schema'

export interface TokenRevokeOrphanResponseBodies {
  200: void
}

export interface TokenRevokeOrphanRequestBodies {
  'application/json': TokenRevokeOrphanRequestSchema
}

export type TokenRevokeOrphanRequestQuery = {}

export type TokenRevokeOrphanRouteParameters = {}

export type TokenRevokeOrphanRequestHeaders = {}

interface TokenRevokeOrphanParameterBodies {
  'application/json': TokenRevokeOrphanRequestSchema & { [key: string]: any }
}

export type TokenRevokeOrphanRequestParameters = TokenRevokeOrphanRequestQuery & TokenRevokeOrphanRouteParameters & TokenRevokeOrphanRequestHeaders & TokenRevokeOrphanRequestBodies['application/json']

export interface TokenRevokeOrphanOperation<STATUS extends keyof TokenRevokeOrphanResponseBodies, CONTENT_TYPE extends keyof TokenRevokeOrphanParameterBodies> extends KeqOperation {
  requestParams: TokenRevokeOrphanRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TokenRevokeOrphanRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TokenRevokeOrphanRequestHeaders & { [key: string]: string | number }
  requestBody: TokenRevokeOrphanParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TokenRevokeOrphanResponseBodies[STATUS]
}

/* @anchor:file:end */
