// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitRestoreKeyRequest as TransitRestoreKeyRequestSchema } from '../components/schemas/transit-restore-key-request.schema'

export interface TransitRestoreKeyResponseBodies {
  200: void
}

export interface TransitRestoreKeyRequestBodies {
  'application/json': TransitRestoreKeyRequestSchema
}

export type TransitRestoreKeyRequestQuery = {}

export type TransitRestoreKeyRouteParameters = {}

export type TransitRestoreKeyRequestHeaders = {}

interface TransitRestoreKeyParameterBodies {
  'application/json': TransitRestoreKeyRequestSchema & { [key: string]: any }
}

export type TransitRestoreKeyRequestParameters = TransitRestoreKeyRequestQuery & TransitRestoreKeyRouteParameters & TransitRestoreKeyRequestHeaders & TransitRestoreKeyRequestBodies['application/json']

export interface TransitRestoreKeyOperation<STATUS extends keyof TransitRestoreKeyResponseBodies, CONTENT_TYPE extends keyof TransitRestoreKeyParameterBodies> extends KeqOperation {
  requestParams: TransitRestoreKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitRestoreKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitRestoreKeyRequestHeaders & { [key: string]: string | number }
  requestBody: TransitRestoreKeyParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitRestoreKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
