// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitHashRequest as TransitHashRequestSchema } from '../components/schemas/transit-hash-request.schema'

export interface TransitHashResponseBodies {
  200: void
}

export interface TransitHashRequestBodies {
  'application/json': TransitHashRequestSchema
}

export type TransitHashRequestQuery = {}

export type TransitHashRouteParameters = {}

export type TransitHashRequestHeaders = {}

interface TransitHashParameterBodies {
  'application/json': TransitHashRequestSchema & { [key: string]: any }
}

export type TransitHashRequestParameters = TransitHashRequestQuery & TransitHashRouteParameters & TransitHashRequestHeaders & TransitHashRequestBodies['application/json']

export interface TransitHashOperation<STATUS extends keyof TransitHashResponseBodies, CONTENT_TYPE extends keyof TransitHashParameterBodies> extends KeqOperation {
  requestParams: TransitHashRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitHashRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitHashRequestHeaders & { [key: string]: string | number }
  requestBody: TransitHashParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitHashResponseBodies[STATUS]
}

/* @anchor:file:end */
