// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitSoftDeleteRestoreKeyResponseBodies {
  200: void
}

export interface TransitSoftDeleteRestoreKeyRequestBodies {}

export type TransitSoftDeleteRestoreKeyRequestQuery = {}

export type TransitSoftDeleteRestoreKeyRouteParameters = {}

export type TransitSoftDeleteRestoreKeyRequestHeaders = {}

export type TransitSoftDeleteRestoreKeyRequestParameters = TransitSoftDeleteRestoreKeyRequestQuery & TransitSoftDeleteRestoreKeyRouteParameters & TransitSoftDeleteRestoreKeyRequestHeaders

export interface TransitSoftDeleteRestoreKeyOperation<STATUS extends keyof TransitSoftDeleteRestoreKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitSoftDeleteRestoreKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitSoftDeleteRestoreKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitSoftDeleteRestoreKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitSoftDeleteRestoreKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
