// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitHashWithAlgorithmRequest as TransitHashWithAlgorithmRequestSchema } from '../components/schemas/transit-hash-with-algorithm-request.schema'

export interface TransitHashWithAlgorithmResponseBodies {
  200: void
}

export interface TransitHashWithAlgorithmRequestBodies {
  'application/json': TransitHashWithAlgorithmRequestSchema
}

export type TransitHashWithAlgorithmRequestQuery = {}

export type TransitHashWithAlgorithmRouteParameters = {}

export type TransitHashWithAlgorithmRequestHeaders = {}

interface TransitHashWithAlgorithmParameterBodies {
  'application/json': TransitHashWithAlgorithmRequestSchema & { [key: string]: any }
}

export type TransitHashWithAlgorithmRequestParameters = TransitHashWithAlgorithmRequestQuery & TransitHashWithAlgorithmRouteParameters & TransitHashWithAlgorithmRequestHeaders & TransitHashWithAlgorithmRequestBodies['application/json']

export interface TransitHashWithAlgorithmOperation<STATUS extends keyof TransitHashWithAlgorithmResponseBodies, CONTENT_TYPE extends keyof TransitHashWithAlgorithmParameterBodies> extends KeqOperation {
  requestParams: TransitHashWithAlgorithmRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitHashWithAlgorithmRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitHashWithAlgorithmRequestHeaders & { [key: string]: string | number }
  requestBody: TransitHashWithAlgorithmParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitHashWithAlgorithmResponseBodies[STATUS]
}

/* @anchor:file:end */
