// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitConfigureKeysRequest as TransitConfigureKeysRequestSchema } from '../components/schemas/transit-configure-keys-request.schema'

export interface TransitConfigureKeysResponseBodies {
  200: void
}

export interface TransitConfigureKeysRequestBodies {
  'application/json': TransitConfigureKeysRequestSchema
}

export type TransitConfigureKeysRequestQuery = {}

export type TransitConfigureKeysRouteParameters = {}

export type TransitConfigureKeysRequestHeaders = {}

interface TransitConfigureKeysParameterBodies {
  'application/json': TransitConfigureKeysRequestSchema & { [key: string]: any }
}

export type TransitConfigureKeysRequestParameters = TransitConfigureKeysRequestQuery & TransitConfigureKeysRouteParameters & TransitConfigureKeysRequestHeaders & TransitConfigureKeysRequestBodies['application/json']

export interface TransitConfigureKeysOperation<STATUS extends keyof TransitConfigureKeysResponseBodies, CONTENT_TYPE extends keyof TransitConfigureKeysParameterBodies> extends KeqOperation {
  requestParams: TransitConfigureKeysRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitConfigureKeysRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitConfigureKeysRequestHeaders & { [key: string]: string | number }
  requestBody: TransitConfigureKeysParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitConfigureKeysResponseBodies[STATUS]
}

/* @anchor:file:end */
