// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitReadKeyResponseBodies {
  200: void
}

export interface TransitReadKeyRequestBodies {}

export type TransitReadKeyRequestQuery = {}

export type TransitReadKeyRouteParameters = {}

export type TransitReadKeyRequestHeaders = {}

export type TransitReadKeyRequestParameters = TransitReadKeyRequestQuery & TransitReadKeyRouteParameters & TransitReadKeyRequestHeaders

export interface TransitReadKeyOperation<STATUS extends keyof TransitReadKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitReadKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitReadKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitReadKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitReadKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
