// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitConfigureKeyRequest as TransitConfigureKeyRequestSchema } from '../components/schemas/transit-configure-key-request.schema'

export interface TransitConfigureKeyResponseBodies {
  200: void
}

export interface TransitConfigureKeyRequestBodies {
  'application/json': TransitConfigureKeyRequestSchema
}

export type TransitConfigureKeyRequestQuery = {}

export type TransitConfigureKeyRouteParameters = {}

export type TransitConfigureKeyRequestHeaders = {}

interface TransitConfigureKeyParameterBodies {
  'application/json': TransitConfigureKeyRequestSchema & { [key: string]: any }
}

export type TransitConfigureKeyRequestParameters = TransitConfigureKeyRequestQuery & TransitConfigureKeyRouteParameters & TransitConfigureKeyRequestHeaders & TransitConfigureKeyRequestBodies['application/json']

export interface TransitConfigureKeyOperation<STATUS extends keyof TransitConfigureKeyResponseBodies, CONTENT_TYPE extends keyof TransitConfigureKeyParameterBodies> extends KeqOperation {
  requestParams: TransitConfigureKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitConfigureKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitConfigureKeyRequestHeaders & { [key: string]: string | number }
  requestBody: TransitConfigureKeyParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitConfigureKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
