// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitTrimKeyRequest as TransitTrimKeyRequestSchema } from '../components/schemas/transit-trim-key-request.schema'

export interface TransitTrimKeyResponseBodies {
  200: void
}

export interface TransitTrimKeyRequestBodies {
  'application/json': TransitTrimKeyRequestSchema
}

export type TransitTrimKeyRequestQuery = {}

export type TransitTrimKeyRouteParameters = {}

export type TransitTrimKeyRequestHeaders = {}

interface TransitTrimKeyParameterBodies {
  'application/json': TransitTrimKeyRequestSchema & { [key: string]: any }
}

export type TransitTrimKeyRequestParameters = TransitTrimKeyRequestQuery & TransitTrimKeyRouteParameters & TransitTrimKeyRequestHeaders & TransitTrimKeyRequestBodies['application/json']

export interface TransitTrimKeyOperation<STATUS extends keyof TransitTrimKeyResponseBodies, CONTENT_TYPE extends keyof TransitTrimKeyParameterBodies> extends KeqOperation {
  requestParams: TransitTrimKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitTrimKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitTrimKeyRequestHeaders & { [key: string]: string | number }
  requestBody: TransitTrimKeyParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitTrimKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
