// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitDecryptRequest as TransitDecryptRequestSchema } from '../components/schemas/transit-decrypt-request.schema'

export interface TransitDecryptResponseBodies {
  200: void
}

export interface TransitDecryptRequestBodies {
  'application/json': TransitDecryptRequestSchema
}

export type TransitDecryptRequestQuery = {}

export type TransitDecryptRouteParameters = {}

export type TransitDecryptRequestHeaders = {}

interface TransitDecryptParameterBodies {
  'application/json': TransitDecryptRequestSchema & { [key: string]: any }
}

export type TransitDecryptRequestParameters = TransitDecryptRequestQuery & TransitDecryptRouteParameters & TransitDecryptRequestHeaders & TransitDecryptRequestBodies['application/json']

export interface TransitDecryptOperation<STATUS extends keyof TransitDecryptResponseBodies, CONTENT_TYPE extends keyof TransitDecryptParameterBodies> extends KeqOperation {
  requestParams: TransitDecryptRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitDecryptRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitDecryptRequestHeaders & { [key: string]: string | number }
  requestBody: TransitDecryptParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitDecryptResponseBodies[STATUS]
}

/* @anchor:file:end */
