// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitConfigureCacheRequest as TransitConfigureCacheRequestSchema } from '../components/schemas/transit-configure-cache-request.schema'

export interface TransitConfigureCacheResponseBodies {
  200: void
}

export interface TransitConfigureCacheRequestBodies {
  'application/json': TransitConfigureCacheRequestSchema
}

export type TransitConfigureCacheRequestQuery = {}

export type TransitConfigureCacheRouteParameters = {}

export type TransitConfigureCacheRequestHeaders = {}

interface TransitConfigureCacheParameterBodies {
  'application/json': TransitConfigureCacheRequestSchema & { [key: string]: any }
}

export type TransitConfigureCacheRequestParameters = TransitConfigureCacheRequestQuery & TransitConfigureCacheRouteParameters & TransitConfigureCacheRequestHeaders & TransitConfigureCacheRequestBodies['application/json']

export interface TransitConfigureCacheOperation<STATUS extends keyof TransitConfigureCacheResponseBodies, CONTENT_TYPE extends keyof TransitConfigureCacheParameterBodies> extends KeqOperation {
  requestParams: TransitConfigureCacheRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitConfigureCacheRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitConfigureCacheRequestHeaders & { [key: string]: string | number }
  requestBody: TransitConfigureCacheParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitConfigureCacheResponseBodies[STATUS]
}

/* @anchor:file:end */
