// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitReadCacheConfigurationResponseBodies {
  200: void
}

export interface TransitReadCacheConfigurationRequestBodies {}

export type TransitReadCacheConfigurationRequestQuery = {}

export type TransitReadCacheConfigurationRouteParameters = {}

export type TransitReadCacheConfigurationRequestHeaders = {}

export type TransitReadCacheConfigurationRequestParameters = TransitReadCacheConfigurationRequestQuery & TransitReadCacheConfigurationRouteParameters & TransitReadCacheConfigurationRequestHeaders

export interface TransitReadCacheConfigurationOperation<STATUS extends keyof TransitReadCacheConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitReadCacheConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitReadCacheConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitReadCacheConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitReadCacheConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
