// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitRewrapRequest as TransitRewrapRequestSchema } from '../components/schemas/transit-rewrap-request.schema'

export interface TransitRewrapResponseBodies {
  200: void
}

export interface TransitRewrapRequestBodies {
  'application/json': TransitRewrapRequestSchema
}

export type TransitRewrapRequestQuery = {}

export type TransitRewrapRouteParameters = {}

export type TransitRewrapRequestHeaders = {}

interface TransitRewrapParameterBodies {
  'application/json': TransitRewrapRequestSchema & { [key: string]: any }
}

export type TransitRewrapRequestParameters = TransitRewrapRequestQuery & TransitRewrapRouteParameters & TransitRewrapRequestHeaders & TransitRewrapRequestBodies['application/json']

export interface TransitRewrapOperation<STATUS extends keyof TransitRewrapResponseBodies, CONTENT_TYPE extends keyof TransitRewrapParameterBodies> extends KeqOperation {
  requestParams: TransitRewrapRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitRewrapRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitRewrapRequestHeaders & { [key: string]: string | number }
  requestBody: TransitRewrapParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitRewrapResponseBodies[STATUS]
}

/* @anchor:file:end */
