// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitReadWrappingKeyResponseBodies {
  200: void
}

export interface TransitReadWrappingKeyRequestBodies {}

export type TransitReadWrappingKeyRequestQuery = {}

export type TransitReadWrappingKeyRouteParameters = {}

export type TransitReadWrappingKeyRequestHeaders = {}

export type TransitReadWrappingKeyRequestParameters = TransitReadWrappingKeyRequestQuery & TransitReadWrappingKeyRouteParameters & TransitReadWrappingKeyRequestHeaders

export interface TransitReadWrappingKeyOperation<STATUS extends keyof TransitReadWrappingKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitReadWrappingKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitReadWrappingKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitReadWrappingKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitReadWrappingKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
