// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitBackUpKeyResponseBodies {
  200: void
}

export interface TransitBackUpKeyRequestBodies {}

export type TransitBackUpKeyRequestQuery = {}

export type TransitBackUpKeyRouteParameters = {}

export type TransitBackUpKeyRequestHeaders = {}

export type TransitBackUpKeyRequestParameters = TransitBackUpKeyRequestQuery & TransitBackUpKeyRouteParameters & TransitBackUpKeyRequestHeaders

export interface TransitBackUpKeyOperation<STATUS extends keyof TransitBackUpKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitBackUpKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitBackUpKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitBackUpKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitBackUpKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
