// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitGenerateDataKeyRequest as TransitGenerateDataKeyRequestSchema } from '../components/schemas/transit-generate-data-key-request.schema'

export interface TransitGenerateDataKeyResponseBodies {
  200: void
}

export interface TransitGenerateDataKeyRequestBodies {
  'application/json': TransitGenerateDataKeyRequestSchema
}

export type TransitGenerateDataKeyRequestQuery = {}

export type TransitGenerateDataKeyRouteParameters = {}

export type TransitGenerateDataKeyRequestHeaders = {}

interface TransitGenerateDataKeyParameterBodies {
  'application/json': TransitGenerateDataKeyRequestSchema & { [key: string]: any }
}

export type TransitGenerateDataKeyRequestParameters = TransitGenerateDataKeyRequestQuery & TransitGenerateDataKeyRouteParameters & TransitGenerateDataKeyRequestHeaders & TransitGenerateDataKeyRequestBodies['application/json']

export interface TransitGenerateDataKeyOperation<STATUS extends keyof TransitGenerateDataKeyResponseBodies, CONTENT_TYPE extends keyof TransitGenerateDataKeyParameterBodies> extends KeqOperation {
  requestParams: TransitGenerateDataKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitGenerateDataKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitGenerateDataKeyRequestHeaders & { [key: string]: string | number }
  requestBody: TransitGenerateDataKeyParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitGenerateDataKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
