// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitImportKeyVersionRequest as TransitImportKeyVersionRequestSchema } from '../components/schemas/transit-import-key-version-request.schema'

export interface TransitImportKeyVersionResponseBodies {
  200: void
}

export interface TransitImportKeyVersionRequestBodies {
  'application/json': TransitImportKeyVersionRequestSchema
}

export type TransitImportKeyVersionRequestQuery = {}

export type TransitImportKeyVersionRouteParameters = {}

export type TransitImportKeyVersionRequestHeaders = {}

interface TransitImportKeyVersionParameterBodies {
  'application/json': TransitImportKeyVersionRequestSchema & { [key: string]: any }
}

export type TransitImportKeyVersionRequestParameters = TransitImportKeyVersionRequestQuery & TransitImportKeyVersionRouteParameters & TransitImportKeyVersionRequestHeaders & TransitImportKeyVersionRequestBodies['application/json']

export interface TransitImportKeyVersionOperation<STATUS extends keyof TransitImportKeyVersionResponseBodies, CONTENT_TYPE extends keyof TransitImportKeyVersionParameterBodies> extends KeqOperation {
  requestParams: TransitImportKeyVersionRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitImportKeyVersionRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitImportKeyVersionRequestHeaders & { [key: string]: string | number }
  requestBody: TransitImportKeyVersionParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitImportKeyVersionResponseBodies[STATUS]
}

/* @anchor:file:end */
