// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitGenerateRandomWithSourceAndBytesRequest as TransitGenerateRandomWithSourceAndBytesRequestSchema } from '../components/schemas/transit-generate-random-with-source-and-bytes-request.schema'

export interface TransitGenerateRandomWithSourceAndBytesResponseBodies {
  200: void
}

export interface TransitGenerateRandomWithSourceAndBytesRequestBodies {
  'application/json': TransitGenerateRandomWithSourceAndBytesRequestSchema
}

export type TransitGenerateRandomWithSourceAndBytesRequestQuery = {}

export type TransitGenerateRandomWithSourceAndBytesRouteParameters = {}

export type TransitGenerateRandomWithSourceAndBytesRequestHeaders = {}

interface TransitGenerateRandomWithSourceAndBytesParameterBodies {
  'application/json': TransitGenerateRandomWithSourceAndBytesRequestSchema & { [key: string]: any }
}

export type TransitGenerateRandomWithSourceAndBytesRequestParameters = TransitGenerateRandomWithSourceAndBytesRequestQuery & TransitGenerateRandomWithSourceAndBytesRouteParameters & TransitGenerateRandomWithSourceAndBytesRequestHeaders & TransitGenerateRandomWithSourceAndBytesRequestBodies['application/json']

export interface TransitGenerateRandomWithSourceAndBytesOperation<STATUS extends keyof TransitGenerateRandomWithSourceAndBytesResponseBodies, CONTENT_TYPE extends keyof TransitGenerateRandomWithSourceAndBytesParameterBodies> extends KeqOperation {
  requestParams: TransitGenerateRandomWithSourceAndBytesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitGenerateRandomWithSourceAndBytesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitGenerateRandomWithSourceAndBytesRequestHeaders & { [key: string]: string | number }
  requestBody: TransitGenerateRandomWithSourceAndBytesParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitGenerateRandomWithSourceAndBytesResponseBodies[STATUS]
}

/* @anchor:file:end */
