// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitImportKeyRequest as TransitImportKeyRequestSchema } from '../components/schemas/transit-import-key-request.schema'

export interface TransitImportKeyResponseBodies {
  200: void
}

export interface TransitImportKeyRequestBodies {
  'application/json': TransitImportKeyRequestSchema
}

export type TransitImportKeyRequestQuery = {}

export type TransitImportKeyRouteParameters = {}

export type TransitImportKeyRequestHeaders = {}

interface TransitImportKeyParameterBodies {
  'application/json': TransitImportKeyRequestSchema & { [key: string]: any }
}

export type TransitImportKeyRequestParameters = TransitImportKeyRequestQuery & TransitImportKeyRouteParameters & TransitImportKeyRequestHeaders & TransitImportKeyRequestBodies['application/json']

export interface TransitImportKeyOperation<STATUS extends keyof TransitImportKeyResponseBodies, CONTENT_TYPE extends keyof TransitImportKeyParameterBodies> extends KeqOperation {
  requestParams: TransitImportKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitImportKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitImportKeyRequestHeaders & { [key: string]: string | number }
  requestBody: TransitImportKeyParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitImportKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
