// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitGenerateHmacRequest as TransitGenerateHmacRequestSchema } from '../components/schemas/transit-generate-hmac-request.schema'

export interface TransitGenerateHmacResponseBodies {
  200: void
}

export interface TransitGenerateHmacRequestBodies {
  'application/json': TransitGenerateHmacRequestSchema
}

export type TransitGenerateHmacRequestQuery = {}

export type TransitGenerateHmacRouteParameters = {}

export type TransitGenerateHmacRequestHeaders = {}

interface TransitGenerateHmacParameterBodies {
  'application/json': TransitGenerateHmacRequestSchema & { [key: string]: any }
}

export type TransitGenerateHmacRequestParameters = TransitGenerateHmacRequestQuery & TransitGenerateHmacRouteParameters & TransitGenerateHmacRequestHeaders & TransitGenerateHmacRequestBodies['application/json']

export interface TransitGenerateHmacOperation<STATUS extends keyof TransitGenerateHmacResponseBodies, CONTENT_TYPE extends keyof TransitGenerateHmacParameterBodies> extends KeqOperation {
  requestParams: TransitGenerateHmacRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitGenerateHmacRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitGenerateHmacRequestHeaders & { [key: string]: string | number }
  requestBody: TransitGenerateHmacParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitGenerateHmacResponseBodies[STATUS]
}

/* @anchor:file:end */
