// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitByokKeyVersionResponseBodies {
  200: void
}

export interface TransitByokKeyVersionRequestBodies {}

export type TransitByokKeyVersionRequestQuery = {}

export type TransitByokKeyVersionRouteParameters = {}

export type TransitByokKeyVersionRequestHeaders = {}

export type TransitByokKeyVersionRequestParameters = TransitByokKeyVersionRequestQuery & TransitByokKeyVersionRouteParameters & TransitByokKeyVersionRequestHeaders

export interface TransitByokKeyVersionOperation<STATUS extends keyof TransitByokKeyVersionResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitByokKeyVersionRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitByokKeyVersionRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitByokKeyVersionRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitByokKeyVersionResponseBodies[STATUS]
}

/* @anchor:file:end */
