// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitByokKeyResponseBodies {
  200: void
}

export interface TransitByokKeyRequestBodies {}

export type TransitByokKeyRequestQuery = {}

export type TransitByokKeyRouteParameters = {}

export type TransitByokKeyRequestHeaders = {}

export type TransitByokKeyRequestParameters = TransitByokKeyRequestQuery & TransitByokKeyRouteParameters & TransitByokKeyRequestHeaders

export interface TransitByokKeyOperation<STATUS extends keyof TransitByokKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitByokKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitByokKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitByokKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitByokKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
