// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitSoftDeleteKeyResponseBodies {
  204: void
}

export interface TransitSoftDeleteKeyRequestBodies {}

export type TransitSoftDeleteKeyRequestQuery = {}

export type TransitSoftDeleteKeyRouteParameters = {}

export type TransitSoftDeleteKeyRequestHeaders = {}

export type TransitSoftDeleteKeyRequestParameters = TransitSoftDeleteKeyRequestQuery & TransitSoftDeleteKeyRouteParameters & TransitSoftDeleteKeyRequestHeaders

export interface TransitSoftDeleteKeyOperation<STATUS extends keyof TransitSoftDeleteKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitSoftDeleteKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitSoftDeleteKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitSoftDeleteKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitSoftDeleteKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
