// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface TransitDeleteKeyResponseBodies {
  204: void
}

export interface TransitDeleteKeyRequestBodies {}

export type TransitDeleteKeyRequestQuery = {}

export type TransitDeleteKeyRouteParameters = {}

export type TransitDeleteKeyRequestHeaders = {}

export type TransitDeleteKeyRequestParameters = TransitDeleteKeyRequestQuery & TransitDeleteKeyRouteParameters & TransitDeleteKeyRequestHeaders

export interface TransitDeleteKeyOperation<STATUS extends keyof TransitDeleteKeyResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: TransitDeleteKeyRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitDeleteKeyRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitDeleteKeyRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: TransitDeleteKeyResponseBodies[STATUS]
}

/* @anchor:file:end */
