// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { TransitGenerateHmacWithAlgorithmRequest as TransitGenerateHmacWithAlgorithmRequestSchema } from '../components/schemas/transit-generate-hmac-with-algorithm-request.schema'

export interface TransitGenerateHmacWithAlgorithmResponseBodies {
  200: void
}

export interface TransitGenerateHmacWithAlgorithmRequestBodies {
  'application/json': TransitGenerateHmacWithAlgorithmRequestSchema
}

export type TransitGenerateHmacWithAlgorithmRequestQuery = {}

export type TransitGenerateHmacWithAlgorithmRouteParameters = {}

export type TransitGenerateHmacWithAlgorithmRequestHeaders = {}

interface TransitGenerateHmacWithAlgorithmParameterBodies {
  'application/json': TransitGenerateHmacWithAlgorithmRequestSchema & { [key: string]: any }
}

export type TransitGenerateHmacWithAlgorithmRequestParameters = TransitGenerateHmacWithAlgorithmRequestQuery & TransitGenerateHmacWithAlgorithmRouteParameters & TransitGenerateHmacWithAlgorithmRequestHeaders & TransitGenerateHmacWithAlgorithmRequestBodies['application/json']

export interface TransitGenerateHmacWithAlgorithmOperation<STATUS extends keyof TransitGenerateHmacWithAlgorithmResponseBodies, CONTENT_TYPE extends keyof TransitGenerateHmacWithAlgorithmParameterBodies> extends KeqOperation {
  requestParams: TransitGenerateHmacWithAlgorithmRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: TransitGenerateHmacWithAlgorithmRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: TransitGenerateHmacWithAlgorithmRequestHeaders & { [key: string]: string | number }
  requestBody: TransitGenerateHmacWithAlgorithmParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: TransitGenerateHmacWithAlgorithmResponseBodies[STATUS]
}

/* @anchor:file:end */
