// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface UiHeadersDeleteConfigurationResponseBodies {
  204: void
}

export interface UiHeadersDeleteConfigurationRequestBodies {}

export type UiHeadersDeleteConfigurationRequestQuery = {}

export type UiHeadersDeleteConfigurationRouteParameters = {}

export type UiHeadersDeleteConfigurationRequestHeaders = {}

export type UiHeadersDeleteConfigurationRequestParameters = UiHeadersDeleteConfigurationRequestQuery & UiHeadersDeleteConfigurationRouteParameters & UiHeadersDeleteConfigurationRequestHeaders

export interface UiHeadersDeleteConfigurationOperation<STATUS extends keyof UiHeadersDeleteConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: UiHeadersDeleteConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UiHeadersDeleteConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UiHeadersDeleteConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: UiHeadersDeleteConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
