// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { UiHeadersReadConfigurationResponse as UiHeadersReadConfigurationResponseSchema } from '../components/schemas/ui-headers-read-configuration-response.schema'

export interface UiHeadersReadConfigurationResponseBodies {
  200: UiHeadersReadConfigurationResponseSchema
}

export interface UiHeadersReadConfigurationRequestBodies {}

export type UiHeadersReadConfigurationRequestQuery = {}

export type UiHeadersReadConfigurationRouteParameters = {}

export type UiHeadersReadConfigurationRequestHeaders = {}

export type UiHeadersReadConfigurationRequestParameters = UiHeadersReadConfigurationRequestQuery & UiHeadersReadConfigurationRouteParameters & UiHeadersReadConfigurationRequestHeaders

export interface UiHeadersReadConfigurationOperation<STATUS extends keyof UiHeadersReadConfigurationResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: UiHeadersReadConfigurationRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UiHeadersReadConfigurationRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UiHeadersReadConfigurationRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: UiHeadersReadConfigurationResponseBodies[STATUS]
}

/* @anchor:file:end */
