// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { UiHeadersConfigureRequest as UiHeadersConfigureRequestSchema } from '../components/schemas/ui-headers-configure-request.schema'

export interface UiHeadersConfigureResponseBodies {
  200: void
}

export interface UiHeadersConfigureRequestBodies {
  'application/json': UiHeadersConfigureRequestSchema
}

export type UiHeadersConfigureRequestQuery = {}

export type UiHeadersConfigureRouteParameters = {}

export type UiHeadersConfigureRequestHeaders = {}

interface UiHeadersConfigureParameterBodies {
  'application/json': UiHeadersConfigureRequestSchema & { [key: string]: any }
}

export type UiHeadersConfigureRequestParameters = UiHeadersConfigureRequestQuery & UiHeadersConfigureRouteParameters & UiHeadersConfigureRequestHeaders & UiHeadersConfigureRequestBodies['application/json']

export interface UiHeadersConfigureOperation<STATUS extends keyof UiHeadersConfigureResponseBodies, CONTENT_TYPE extends keyof UiHeadersConfigureParameterBodies> extends KeqOperation {
  requestParams: UiHeadersConfigureRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UiHeadersConfigureRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UiHeadersConfigureRequestHeaders & { [key: string]: string | number }
  requestBody: UiHeadersConfigureParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: UiHeadersConfigureResponseBodies[STATUS]
}

/* @anchor:file:end */
