// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { UnsealRequest as UnsealRequestSchema } from '../components/schemas/unseal-request.schema'
import type { UnsealResponse as UnsealResponseSchema } from '../components/schemas/unseal-response.schema'

export interface UnsealResponseBodies {
  200: UnsealResponseSchema
}

export interface UnsealRequestBodies {
  'application/json': UnsealRequestSchema
}

export type UnsealRequestQuery = {}

export type UnsealRouteParameters = {}

export type UnsealRequestHeaders = {}

interface UnsealParameterBodies {
  'application/json': UnsealRequestSchema & { [key: string]: any }
}

export type UnsealRequestParameters = UnsealRequestQuery & UnsealRouteParameters & UnsealRequestHeaders & UnsealRequestBodies['application/json']

export interface UnsealOperation<STATUS extends keyof UnsealResponseBodies, CONTENT_TYPE extends keyof UnsealParameterBodies> extends KeqOperation {
  requestParams: UnsealRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UnsealRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UnsealRequestHeaders & { [key: string]: string | number }
  requestBody: UnsealParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: UnsealResponseBodies[STATUS]
}

/* @anchor:file:end */
