// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { UnwrapRequest as UnwrapRequestSchema } from '../components/schemas/unwrap-request.schema'

export interface UnwrapResponseBodies {
  200: void
  204: void
}

export interface UnwrapRequestBodies {
  'application/json': UnwrapRequestSchema
}

export type UnwrapRequestQuery = {}

export type UnwrapRouteParameters = {}

export type UnwrapRequestHeaders = {}

interface UnwrapParameterBodies {
  'application/json': UnwrapRequestSchema & { [key: string]: any }
}

export type UnwrapRequestParameters = UnwrapRequestQuery & UnwrapRouteParameters & UnwrapRequestHeaders & UnwrapRequestBodies['application/json']

export interface UnwrapOperation<STATUS extends keyof UnwrapResponseBodies, CONTENT_TYPE extends keyof UnwrapParameterBodies> extends KeqOperation {
  requestParams: UnwrapRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UnwrapRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UnwrapRequestHeaders & { [key: string]: string | number }
  requestBody: UnwrapParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: UnwrapResponseBodies[STATUS]
}

/* @anchor:file:end */
