// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { UserpassUpdatePoliciesRequest as UserpassUpdatePoliciesRequestSchema } from '../components/schemas/userpass-update-policies-request.schema'

export interface UserpassUpdatePoliciesResponseBodies {
  200: void
}

export interface UserpassUpdatePoliciesRequestBodies {
  'application/json': UserpassUpdatePoliciesRequestSchema
}

export type UserpassUpdatePoliciesRequestQuery = {}

export type UserpassUpdatePoliciesRouteParameters = {}

export type UserpassUpdatePoliciesRequestHeaders = {}

interface UserpassUpdatePoliciesParameterBodies {
  'application/json': UserpassUpdatePoliciesRequestSchema & { [key: string]: any }
}

export type UserpassUpdatePoliciesRequestParameters = UserpassUpdatePoliciesRequestQuery & UserpassUpdatePoliciesRouteParameters & UserpassUpdatePoliciesRequestHeaders & UserpassUpdatePoliciesRequestBodies['application/json']

export interface UserpassUpdatePoliciesOperation<STATUS extends keyof UserpassUpdatePoliciesResponseBodies, CONTENT_TYPE extends keyof UserpassUpdatePoliciesParameterBodies> extends KeqOperation {
  requestParams: UserpassUpdatePoliciesRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UserpassUpdatePoliciesRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UserpassUpdatePoliciesRequestHeaders & { [key: string]: string | number }
  requestBody: UserpassUpdatePoliciesParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: UserpassUpdatePoliciesResponseBodies[STATUS]
}

/* @anchor:file:end */
