// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface UserpassListUsersResponseBodies {
  200: void
}

export interface UserpassListUsersRequestBodies {}

export type UserpassListUsersRequestQuery = {
  list: 'true'
}

export type UserpassListUsersRouteParameters = {}

export type UserpassListUsersRequestHeaders = {}

export type UserpassListUsersRequestParameters = UserpassListUsersRequestQuery & UserpassListUsersRouteParameters & UserpassListUsersRequestHeaders

export interface UserpassListUsersOperation<STATUS extends keyof UserpassListUsersResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: UserpassListUsersRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UserpassListUsersRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UserpassListUsersRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: UserpassListUsersResponseBodies[STATUS]
}

/* @anchor:file:end */
