// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface UserpassDeleteUserResponseBodies {
  204: void
}

export interface UserpassDeleteUserRequestBodies {}

export type UserpassDeleteUserRequestQuery = {}

export type UserpassDeleteUserRouteParameters = {}

export type UserpassDeleteUserRequestHeaders = {}

export type UserpassDeleteUserRequestParameters = UserpassDeleteUserRequestQuery & UserpassDeleteUserRouteParameters & UserpassDeleteUserRequestHeaders

export interface UserpassDeleteUserOperation<STATUS extends keyof UserpassDeleteUserResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: UserpassDeleteUserRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UserpassDeleteUserRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UserpassDeleteUserRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: UserpassDeleteUserResponseBodies[STATUS]
}

/* @anchor:file:end */
