// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface UserpassReadUserResponseBodies {
  200: void
}

export interface UserpassReadUserRequestBodies {}

export type UserpassReadUserRequestQuery = {}

export type UserpassReadUserRouteParameters = {}

export type UserpassReadUserRequestHeaders = {}

export type UserpassReadUserRequestParameters = UserpassReadUserRequestQuery & UserpassReadUserRouteParameters & UserpassReadUserRequestHeaders

export interface UserpassReadUserOperation<STATUS extends keyof UserpassReadUserResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: UserpassReadUserRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UserpassReadUserRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UserpassReadUserRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: UserpassReadUserResponseBodies[STATUS]
}

/* @anchor:file:end */
