// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { UserpassResetPasswordRequest as UserpassResetPasswordRequestSchema } from '../components/schemas/userpass-reset-password-request.schema'

export interface UserpassResetPasswordResponseBodies {
  200: void
}

export interface UserpassResetPasswordRequestBodies {
  'application/json': UserpassResetPasswordRequestSchema
}

export type UserpassResetPasswordRequestQuery = {}

export type UserpassResetPasswordRouteParameters = {}

export type UserpassResetPasswordRequestHeaders = {}

interface UserpassResetPasswordParameterBodies {
  'application/json': UserpassResetPasswordRequestSchema & { [key: string]: any }
}

export type UserpassResetPasswordRequestParameters = UserpassResetPasswordRequestQuery & UserpassResetPasswordRouteParameters & UserpassResetPasswordRequestHeaders & UserpassResetPasswordRequestBodies['application/json']

export interface UserpassResetPasswordOperation<STATUS extends keyof UserpassResetPasswordResponseBodies, CONTENT_TYPE extends keyof UserpassResetPasswordParameterBodies> extends KeqOperation {
  requestParams: UserpassResetPasswordRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UserpassResetPasswordRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UserpassResetPasswordRequestHeaders & { [key: string]: string | number }
  requestBody: UserpassResetPasswordParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: UserpassResetPasswordResponseBodies[STATUS]
}

/* @anchor:file:end */
