// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { UserpassWriteUserRequest as UserpassWriteUserRequestSchema } from '../components/schemas/userpass-write-user-request.schema'

export interface UserpassWriteUserResponseBodies {
  200: void
}

export interface UserpassWriteUserRequestBodies {
  'application/json': UserpassWriteUserRequestSchema
}

export type UserpassWriteUserRequestQuery = {}

export type UserpassWriteUserRouteParameters = {}

export type UserpassWriteUserRequestHeaders = {}

interface UserpassWriteUserParameterBodies {
  'application/json': UserpassWriteUserRequestSchema & { [key: string]: any }
}

export type UserpassWriteUserRequestParameters = UserpassWriteUserRequestQuery & UserpassWriteUserRouteParameters & UserpassWriteUserRequestHeaders & UserpassWriteUserRequestBodies['application/json']

export interface UserpassWriteUserOperation<STATUS extends keyof UserpassWriteUserResponseBodies, CONTENT_TYPE extends keyof UserpassWriteUserParameterBodies> extends KeqOperation {
  requestParams: UserpassWriteUserRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UserpassWriteUserRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UserpassWriteUserRequestHeaders & { [key: string]: string | number }
  requestBody: UserpassWriteUserParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: UserpassWriteUserResponseBodies[STATUS]
}

/* @anchor:file:end */
