// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { UserpassLoginRequest as UserpassLoginRequestSchema } from '../components/schemas/userpass-login-request.schema'

export interface UserpassLoginResponseBodies {
  200: void
}

export interface UserpassLoginRequestBodies {
  'application/json': UserpassLoginRequestSchema
}

export type UserpassLoginRequestQuery = {}

export type UserpassLoginRouteParameters = {}

export type UserpassLoginRequestHeaders = {}

interface UserpassLoginParameterBodies {
  'application/json': UserpassLoginRequestSchema & { [key: string]: any }
}

export type UserpassLoginRequestParameters = UserpassLoginRequestQuery & UserpassLoginRouteParameters & UserpassLoginRequestHeaders & UserpassLoginRequestBodies['application/json']

export interface UserpassLoginOperation<STATUS extends keyof UserpassLoginResponseBodies, CONTENT_TYPE extends keyof UserpassLoginParameterBodies> extends KeqOperation {
  requestParams: UserpassLoginRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: UserpassLoginRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: UserpassLoginRequestHeaders & { [key: string]: string | number }
  requestBody: UserpassLoginParameterBodies[CONTENT_TYPE] | BodyInit
  responseBody: UserpassLoginResponseBodies[STATUS]
}

/* @anchor:file:end */
