// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'
import type { VersionHistoryResponse as VersionHistoryResponseSchema } from '../components/schemas/version-history-response.schema'

export interface VersionHistoryResponseBodies {
  200: VersionHistoryResponseSchema
}

export interface VersionHistoryRequestBodies {}

export type VersionHistoryRequestQuery = {
  list: ('true')
}

export type VersionHistoryRouteParameters = {}

export type VersionHistoryRequestHeaders = {}

export type VersionHistoryRequestParameters = VersionHistoryRequestQuery & VersionHistoryRouteParameters & VersionHistoryRequestHeaders

export interface VersionHistoryOperation<STATUS extends keyof VersionHistoryResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: VersionHistoryRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: VersionHistoryRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: VersionHistoryRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: VersionHistoryResponseBodies[STATUS]
}

/* @anchor:file:end */
