// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.
// Code generated by @keq-request/cli. DO NOT EDIT.

/* @anchor:file:start */

import type { KeqOperation, KeqPathParameterInit, KeqQueryInit, ServerSentEvent } from 'keq'

export interface WrapResponseBodies {
  200: void
}

export interface WrapRequestBodies {}

export type WrapRequestQuery = {}

export type WrapRouteParameters = {}

export type WrapRequestHeaders = {}

export type WrapRequestParameters = WrapRequestQuery & WrapRouteParameters & WrapRequestHeaders

export interface WrapOperation<STATUS extends keyof WrapResponseBodies, CONTENT_TYPE extends string> extends KeqOperation {
  requestParams: WrapRouteParameters & { [key: string]: KeqPathParameterInit }
  requestQuery: WrapRequestQuery & { [key: string]: KeqQueryInit }
  requestHeaders: WrapRequestHeaders & { [key: string]: string | number }
  requestBody: object | BodyInit
  responseBody: WrapResponseBodies[STATUS]
}

/* @anchor:file:end */
